/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, BadgeDollarSign, CheckCircle2, Save } from "lucide-react";
import { useAuth } from "@/components/providers/auth-provider";
import { notify } from "@/components/toast-viewport";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { usePlatformPlan, usePlatformPlanMutation } from "@/lib/services/platform-plans-hooks";
import type { PlanAction, PlanFeature, PlanInput, PlanInterval } from "@/lib/services/platform-plans-service";

const tabs = ["Informações gerais", "Preços", "Recursos e limites", "Landing", "Checkout", "Clientes vinculados", "Histórico"];
const blank: PlanInput & { code: string } = { code: "", slug: "", name: "", title: "", shortDescription: "", description: "", sortOrder: 0, trialDays: 0, featured: false, publicVisible: false, availableForSale: false, checkoutDescription: "", buttonLabel: "Começar agora", badgeLabel: "" };
export function PlanForm({ planId }: { planId?: string }) {
  const { user } = useAuth(); const router = useRouter(); const query = usePlatformPlan(planId); const mutation = usePlatformPlanMutation();
  const [tab,setTab]=useState(tabs[0]); const [form,setForm]=useState(blank); const [features,setFeatures]=useState<PlanFeature[]>([]);
  const [price,setPrice]=useState({ interval:"MONTHLY", amount:"", currency:"BRL", validFrom:new Date().toISOString().slice(0,10), applicationPolicy:"NEW_CUSTOMERS_ONLY" });
  useEffect(()=>{if(query.data){const p=query.data;setForm({code:p.code,slug:p.slug,name:p.name,title:p.title||"",shortDescription:p.shortDescription||"",description:p.description||"",sortOrder:p.sortOrder,trialDays:p.trialDays,featured:p.featured,publicVisible:p.publicVisible,availableForSale:p.availableForSale,checkoutDescription:p.checkoutDescription||"",buttonLabel:p.buttonLabel,badgeLabel:p.badgeLabel||""});setFeatures(p.features)}},[query.data]);
  const allowed=useMemo(()=>["PLATFORM_ADMIN","PLATFORM_SUPER_ADMIN"].includes(user?.role||""),[user]);
  if(!allowed)return <Card className="p-8 text-center font-bold">Acesso exclusivo da administração da plataforma.</Card>;
  if(planId&&query.isLoading)return <div className="h-96 animate-pulse rounded-2xl bg-white/60"/>;
  const field=(key:keyof typeof form,value:unknown)=>setForm(current=>({...current,[key]:value}));
  const save=()=>mutation.mutate(planId?{kind:"update",id:planId,data:form}:{kind:"create",data:form},{onSuccess:(saved)=>{notify({title:"Plano salvo",tone:"success"});if(!planId&&"code" in saved)router.replace(`/platform/plans/${saved.id}`)},onError:e=>notify({title:"Falha ao salvar",description:e.message,tone:"error"})});
  const action=(name:PlanAction)=>{if(!planId)return;mutation.mutate({kind:"action",id:planId,action:name},{onSuccess:()=>notify({title:"Status atualizado",tone:"success"}),onError:e=>notify({title:"Falha na ação",description:e.message,tone:"error"})})};
  const addPrice=()=>{if(!planId)return;mutation.mutate({kind:"price",id:planId,data:{...price,interval:price.interval as PlanInterval,amountCents:Math.round(Number(price.amount.replace(",","."))*100),validFrom:new Date(`${price.validFrom}T00:00:00`).toISOString()}},{onSuccess:()=>{notify({title:"Nova versão de preço criada",tone:"success"});setPrice(x=>({...x,amount:""}))},onError:e=>notify({title:"Preço inválido",description:e.message,tone:"error"})})};
  const saveFeatures=()=>{if(!planId)return;mutation.mutate({kind:"features",id:planId,data:features},{onSuccess:()=>notify({title:"Recursos atualizados",tone:"success"}),onError:e=>notify({title:"Falha nos recursos",description:e.message,tone:"error"})})};
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-widest text-subtle">Gestão de Planos</p><h1 className="text-3xl font-extrabold">{planId?form.name||"Editar plano":"Novo plano"}</h1></div><div className="flex flex-wrap gap-2"><Button variant="lime" onClick={save} disabled={mutation.isPending}><Save className="h-4 w-4"/>Salvar</Button>{planId&&<><Button variant="outline" onClick={()=>action("publish")}><CheckCircle2 className="h-4 w-4"/>Publicar</Button><Button variant="danger" onClick={()=>confirm("Arquivar este plano?")&&action("archive")}><Archive className="h-4 w-4"/>Arquivar</Button></>}</div></div>
    <div className="flex gap-2 overflow-x-auto">{tabs.map(value=><button key={value} onClick={()=>setTab(value)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${tab===value?"bg-ink text-white":"bg-white text-subtle"}`}>{value}</button>)}</div>
    {tab==="Informações gerais"&&<Card className="grid gap-4 p-5 md:grid-cols-2"><Input label="Código interno" disabled={!!planId} value={form.code} onChange={e=>field("code",e.target.value.toUpperCase())}/><Input label="Slug" value={form.slug} onChange={e=>field("slug",e.target.value)}/><Input label="Nome" value={form.name} onChange={e=>field("name",e.target.value)}/><Input label="Título comercial" value={form.title||""} onChange={e=>field("title",e.target.value)}/><Input label="Descrição curta" value={form.shortDescription||""} onChange={e=>field("shortDescription",e.target.value)}/><Input label="Ordem" type="number" value={form.sortOrder} onChange={e=>field("sortOrder",Number(e.target.value))}/><Input label="Dias de teste" type="number" value={form.trialDays} onChange={e=>field("trialDays",Number(e.target.value))}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.featured} onChange={e=>field("featured",e.target.checked)}/>Plano recomendado</label></Card>}
    {tab==="Preços"&&<Card className="space-y-4 p-5"><div className="grid gap-4 md:grid-cols-4"><label className="text-xs font-bold">Intervalo<select className="mt-2 h-11 w-full rounded-xl border px-3" value={price.interval} onChange={e=>setPrice(x=>({...x,interval:e.target.value}))}><option value="MONTHLY">Mensal</option><option value="YEARLY">Anual</option></select></label><Input label="Novo valor (R$)" value={price.amount} onChange={e=>setPrice(x=>({...x,amount:e.target.value}))}/><Input label="Válido a partir de" type="date" value={price.validFrom} onChange={e=>setPrice(x=>({...x,validFrom:e.target.value}))}/><label className="text-xs font-bold">Aplicar para<select className="mt-2 h-11 w-full rounded-xl border px-3" value={price.applicationPolicy} onChange={e=>setPrice(x=>({...x,applicationPolicy:e.target.value}))}><option value="NEW_CUSTOMERS_ONLY">Apenas novos clientes</option><option value="ALL_NEXT_RENEWAL">Todos na próxima renovação</option><option value="SELECTED_CUSTOMERS">Clientes selecionados</option><option value="SCHEDULED">Agendar</option></select></label></div><Button disabled={!planId||!price.amount} onClick={addPrice}><BadgeDollarSign className="h-4 w-4"/>Criar versão de preço</Button><div className="divide-y text-xs">{query.data?.priceHistory.map(p=><div className="flex justify-between py-3" key={p.id}><span>{(p as any).interval} · {new Date(p.validFrom).toLocaleDateString("pt-BR")}</span><b>{new Intl.NumberFormat("pt-BR",{style:"currency",currency:p.currency}).format(p.amountCents/100)}</b></div>)}</div></Card>}
    {tab==="Recursos e limites"&&<Card className="space-y-3 p-5">{features.map((feature,index)=><div className="grid gap-2 md:grid-cols-[1fr_2fr_1fr_1fr_auto]" key={`${feature.code}-${index}`}><Input value={feature.code} onChange={e=>setFeatures(x=>x.map((f,i)=>i===index?{...f,code:e.target.value.toUpperCase()}:f))}/><Input value={feature.label} onChange={e=>setFeatures(x=>x.map((f,i)=>i===index?{...f,label:e.target.value}:f))}/><select className="rounded-xl border px-3" value={feature.valueType} onChange={e=>setFeatures(x=>x.map((f,i)=>i===index?{...f,valueType:e.target.value as any}:f))}><option>BOOLEAN</option><option>INTEGER</option><option>TEXT</option><option>UNLIMITED</option></select><Input value={feature.value||""} onChange={e=>setFeatures(x=>x.map((f,i)=>i===index?{...f,value:e.target.value}:f))}/><Button variant="danger" onClick={()=>setFeatures(x=>x.filter((_,i)=>i!==index))}>Remover</Button></div>)}<div className="flex gap-2"><Button variant="outline" onClick={()=>setFeatures(x=>[...x,{code:"",label:"",valueType:"BOOLEAN",value:"true",visible:true,sortOrder:x.length}])}>Adicionar recurso</Button><Button disabled={!planId} onClick={saveFeatures}>Salvar recursos</Button></div></Card>}
    {tab==="Landing"&&<Card className="grid gap-4 p-5 md:grid-cols-2"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.publicVisible} onChange={e=>field("publicVisible",e.target.checked)}/>Visível na landing</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.availableForSale} onChange={e=>field("availableForSale",e.target.checked)}/>Disponível para contratação</label><Input label="Selo" value={form.badgeLabel||""} onChange={e=>field("badgeLabel",e.target.value)}/><Input label="Texto do botão" value={form.buttonLabel} onChange={e=>field("buttonLabel",e.target.value)}/></Card>}
    {tab==="Checkout"&&<Card className="p-5"><Input label="Descrição enviada ao checkout" value={form.checkoutDescription||""} onChange={e=>field("checkoutDescription",e.target.value)}/><p className="mt-3 text-xs text-subtle">O checkout receberá somente o plano e o intervalo; o valor será resolvido no backend pela versão vigente.</p></Card>}
    {tab==="Clientes vinculados"&&<Card className="p-8 text-center text-sm text-subtle">{query.data?.subscribers||0} assinatura(s) vinculada(s). Migrações serão controladas por política de preço.</Card>}
    {tab==="Histórico"&&<Card className="p-5 text-sm text-subtle">Alterações críticas são registradas em auditoria. O histórico financeiro e as versões de preço são imutáveis.</Card>}
  </div>;
}
