export {
  applyProductFiscalRule,
  analyzeNcm,
  autoFixProduct,
  createProduct,
  deleteProduct,
  getProductStock,
  getNextCode,
  getProduct,
  listProductDocuments,
  listProducts,
  lookupNcm,
  simulateFiscal,
  suggestProductCest,
  suggestProductNcm,
  updateProduct,
  updateProductMarketplace,
  updateProductPricing,
  updateProductStockSettings,
  validateProduct,
  validarProdutoFiscal,
} from "@/lib/services/product-service";
