"use client";

import * as React from "react";
import { AlertCircle, ArrowRight, CalendarClock, Check, CheckCircle2, CircleAlert, Clock3, Crown, Gauge, Infinity as InfinityIcon, Loader2, RefreshCw, Sparkles, TriangleAlert, X } from "lucide-react";
import { useMemo, useRef, useState } from "react";

import { notify } from "@/components/toast-viewport";
import { useCompanyContext } from "@/components/providers/company-provider";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { createSubscriptionIdempotencyKey, useSubscription, useSubscriptionActions, useSubscriptionCatalog, useSubscriptionUsage } from "@/lib/services/subscription-hooks";
import type { BillingCycle, SubscriptionContext, SubscriptionPlan, UsageItem } from "@/lib/services/subscription-service";
import { cn } from "@/lib/utils";
import { annualSavings, errorPresentation, featureName, formatCycle, formatDate, formatMoney, isEnabledFeature, planAction, planActionCopy, statusPresentation, usagePresentation, type PlanAction } from "./subscription-ui";

type Selection = { plan: SubscriptionPlan; action: PlanAction; idempotencyKey: string };
type CancelIntent = { mode: "PERIOD_END" | "IMMEDIATE"; idempotencyKey: string };

export function SubscriptionView() {
  const [cycle, setCycle] = useState<BillingCycle>("MONTHLY");
  const [selection, setSelection] = useState<Selection | null>(null);
  const [cancelIntent, setCancelIntent] = useState<CancelIntent | null>(null);
  const [reactivateKey, setReactivateKey] = useState<string | null>(null);
  const [retrying, setRetrying] = useState(false);
  const plansRef = useRef<HTMLElement>(null);
  const { activeCompanyId, isLoading: companyLoading, isSuccess: companyReady } = useCompanyContext();
  const current = useSubscription(activeCompanyId);
  const catalog = useSubscriptionCatalog(activeCompanyId);
  const usage = useSubscriptionUsage(activeCompanyId);
  const actions = useSubscriptionActions();
  const plans = useMemo(() => catalog.data?.plans ?? [], [catalog.data]);
  const context = current.data;
  const queryErrors = [current.error, catalog.error, usage.error].filter(Boolean);
  const hasUsableData = Boolean(current.data || catalog.data || usage.data);

  const scrollToPlans = () => plansRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  const refresh = async () => {
    if (retrying) return;
    setRetrying(true);
    try {
      await Promise.allSettled([current.refetch(), catalog.refetch(), usage.refetch()]);
    } finally {
      setRetrying(false);
    }
  };
  const openCancel = () => { actions.cancel.reset(); setCancelIntent({ mode: "PERIOD_END", idempotencyKey: createSubscriptionIdempotencyKey("cancel-period-end") }); };

  if (companyLoading || (!hasUsableData && current.isLoading && catalog.isLoading && usage.isLoading)) return <SubscriptionSkeleton />;
  if (companyReady && !activeCompanyId) return <CompanyContextRequired />;
  if (queryErrors.length === 3 && !hasUsableData) return <PageError error={queryErrors[0]} onRetry={refresh} retrying={retrying} />;

  return (
    <div className="space-y-6 pb-8" aria-live="polite">
      <PageHeader context={context} onManage={scrollToPlans} onRefresh={refresh} refreshing={retrying} onCancel={openCancel} onReactivate={() => { actions.reactivate.reset(); setReactivateKey(createSubscriptionIdempotencyKey("reactivate")); }} />
      {current.isLoading ? <SectionLoading label="Carregando plano atual" /> : current.error ? <PartialError title="Não foi possível carregar sua assinatura" error={current.error} onRetry={refresh} retrying={retrying} /> : context?.subscription ? <><Banners context={context} onCompare={scrollToPlans} /><CurrentPlan context={context} onManage={scrollToPlans} onCancel={openCancel} /></> : <EmptySubscription onCompare={scrollToPlans} />}
      {usage.isLoading ? <SectionLoading label="Carregando uso no período" /> : usage.error ? <PartialError title="Não foi possível carregar o uso no período" error={usage.error} onRetry={refresh} retrying={retrying} /> : <UsageSection items={usage.data?.items ?? []} onCompare={scrollToPlans} />}
      {catalog.isLoading ? <SectionLoading label="Carregando catálogo de planos" /> : catalog.error ? <PartialError title="Não foi possível carregar o catálogo de planos" error={catalog.error} onRetry={refresh} retrying={retrying} /> : <PlanGrid ref={plansRef} plans={plans} cycle={cycle} context={context} onCycle={(value) => { setCycle(value); setSelection(null); actions.change.reset(); }} onSelect={(plan) => { const action = planAction(plan, cycle, context); if (action === "CURRENT" || action === "UNAVAILABLE") return; actions.change.reset(); setSelection({ plan, action, idempotencyKey: createSubscriptionIdempotencyKey(`change-${plan.code.toLowerCase()}-${cycle.toLowerCase()}`) }); }} />}
      <ChangeDialog selection={selection} cycle={cycle} context={context} plans={plans} pending={actions.change.isPending} error={actions.change.error} onClose={() => { if (!actions.change.isPending) { setSelection(null); actions.change.reset(); } }} onConfirm={() => { if (!selection) return; actions.change.mutate({ targetPlanCode: selection.plan.code, targetBillingCycle: cycle, idempotencyKey: selection.idempotencyKey }, { onSuccess: (response) => { notify({ title: response.result === "SCHEDULED" ? "Alteração agendada" : "Plano atualizado", description: response.result === "SCHEDULED" ? "A mudança será aplicada no próximo período." : "A alteração já está refletida na assinatura." }); setSelection(null); }, onError: (error) => showMutationError(error) }); }} />
      <CancelDialog intent={cancelIntent} context={context} pending={actions.cancel.isPending} error={actions.cancel.error} onMode={(mode) => { actions.cancel.reset(); setCancelIntent({ mode, idempotencyKey: createSubscriptionIdempotencyKey(`cancel-${mode.toLowerCase()}`) }); }} onClose={() => { if (!actions.cancel.isPending) { setCancelIntent(null); actions.cancel.reset(); } }} onConfirm={() => { if (!cancelIntent) return; actions.cancel.mutate(cancelIntent, { onSuccess: () => { notify({ title: cancelIntent.mode === "PERIOD_END" ? "Cancelamento programado" : "Assinatura cancelada", description: cancelIntent.mode === "PERIOD_END" ? "O acesso permanece ativo até o fim do período." : "O acesso aos recursos foi encerrado." }); setCancelIntent(null); }, onError: (error) => showMutationError(error) }); }} />
      <ReactivateDialog open={Boolean(reactivateKey)} context={context} pending={actions.reactivate.isPending} error={actions.reactivate.error} onClose={() => { if (!actions.reactivate.isPending) { setReactivateKey(null); actions.reactivate.reset(); } }} onConfirm={() => { if (!reactivateKey) return; actions.reactivate.mutate({ idempotencyKey: reactivateKey }, { onSuccess: () => { notify({ title: "Assinatura mantida", description: "O cancelamento programado foi removido." }); setReactivateKey(null); }, onError: (error) => showMutationError(error) }); }} />
    </div>
  );
}

function showMutationError(error: unknown) { const copy = errorPresentation(error); notify({ title: copy.title, description: copy.message, tone: "error" }); }

function PageHeader({ context, onManage, onRefresh, refreshing, onCancel, onReactivate }: { context?: SubscriptionContext; onManage: () => void; onRefresh: () => void; refreshing: boolean; onCancel: () => void; onReactivate: () => void }) {
  return <header className="rounded-3xl border border-line bg-white px-5 py-6 shadow-soft sm:px-7 lg:flex lg:items-end lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-lime-dark">Configurações</p><h1 className="mt-2 text-2xl font-extrabold tracking-tight text-ink sm:text-3xl">Assinatura e plano</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-subtle">Gerencie seu plano, recursos disponíveis e limites de utilização.</p></div><div className="mt-5 flex flex-wrap gap-2 lg:mt-0"><Button variant="outline" onClick={onRefresh} disabled={refreshing}>{refreshing ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} {refreshing ? "Tentando novamente..." : "Atualizar dados"}</Button>{context?.capabilities.canReactivate ? <Button variant="lime" onClick={onReactivate}>Manter assinatura</Button> : context?.capabilities.canCancel ? <Button variant="outline" onClick={onCancel}>Cancelar assinatura</Button> : null}<Button onClick={onManage}>Gerenciar plano</Button></div></header>;
}

function Banners({ context, onCompare }: { context: SubscriptionContext; onCompare: () => void }) {
  const subscription = context.subscription; if (!subscription) return null;
  return <div className="space-y-3">{subscription.status === "TRIALING" && subscription.trialEndsAt ? <Banner icon={Sparkles} title="Período de teste" action="Escolher plano" onAction={onCompare}>Seu período de teste termina em {formatDate(subscription.trialEndsAt)}.</Banner> : null}{context.nextPlan ? <Banner icon={CalendarClock} title="Mudança agendada">Seu plano será alterado para {context.nextPlan.name} em {formatDate(context.nextPlan.effectiveAt)}.</Banner> : null}{subscription.cancelAtPeriodEnd ? <Banner icon={TriangleAlert} title="Cancelamento programado" warning>Sua assinatura será encerrada em {formatDate(subscription.currentPeriodEnd)}. Você pode mantê-la até essa data.</Banner> : null}{subscription.status === "PAST_DUE" ? <Banner icon={CircleAlert} title="Pagamento pendente" warning>A assinatura precisa de atenção. Nenhuma cobrança automática é confirmada por esta tela.</Banner> : null}{subscription.status === "SUSPENDED" ? <Banner icon={CircleAlert} title="Assinatura suspensa" warning action="Comparar planos" onAction={onCompare}>Alguns recursos podem estar indisponíveis. Revise as opções ou fale com o suporte.</Banner> : null}</div>;
}

function Banner({ icon: Icon, title, warning = false, action, onAction, children }: { icon: typeof AlertCircle; title: string; warning?: boolean; action?: string; onAction?: () => void; children: React.ReactNode }) {
  return <div className={cn("flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center", warning ? "border-amber-200 bg-amber-50" : "border-indigo-100 bg-indigo-50")}><Icon className={cn("h-5 w-5 shrink-0", warning ? "text-amber-600" : "text-indigo-600")} /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">{title}</p><p className="mt-0.5 text-xs leading-5 text-subtle">{children}</p></div>{action && onAction ? <Button size="sm" variant="outline" onClick={onAction}>{action}</Button> : null}</div>;
}

function CurrentPlan({ context, onManage, onCancel }: { context: SubscriptionContext; onManage: () => void; onCancel: () => void }) {
  const subscription = context.subscription; if (!subscription) return null;
  const status = statusPresentation(subscription.status, subscription.cancelAtPeriodEnd);
  const features = Object.entries(context.entitlements).filter(([, value]) => isEnabledFeature(value)).slice(0, 6);
  const terminated = ["CANCELED", "EXPIRED"].includes(subscription.status);
  const trialDays = subscription.trialEndsAt ? Math.max(0, Math.ceil((new Date(subscription.trialEndsAt).getTime() - Date.now()) / 86_400_000)) : null;
  return <Card className="overflow-hidden"><div className="grid lg:grid-cols-[1.15fr_.85fr]"><div className="p-5 sm:p-7"><div className="flex flex-wrap items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-lime"><Crown className="h-5 w-5" /></div><div><p className="text-[11px] font-extrabold uppercase tracking-[0.14em] text-subtle">Plano atual</p><h2 className="text-2xl font-extrabold">{context.plan?.name ?? "Plano indisponível"}</h2></div><Badge variant={status.tone} className="ml-auto normal-case tracking-normal">{status.label}</Badge></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Summary label="Valor" value={context.price ? formatMoney(context.price.amountCents, context.price.currency) : "Não informado"} /><Summary label="Cobrança" value={context.price ? formatCycle(context.price.billingCycle) : "Não informada"} /><Summary label={terminated ? "Encerramento" : "Próxima renovação"} value={formatDate(terminated ? subscription.endedAt : subscription.currentPeriodEnd)} /></div><div className="mt-5 flex flex-wrap gap-2 text-xs text-subtle"><span className="inline-flex items-center gap-1.5 rounded-full bg-muted px-3 py-1.5"><Clock3 className="h-3.5 w-3.5" /> Período: {formatDate(subscription.currentPeriodStart)} a {formatDate(subscription.currentPeriodEnd)}</span>{trialDays !== null && subscription.status === "TRIALING" ? <span className="rounded-full bg-indigo-50 px-3 py-1.5 text-indigo-700">{trialDays} {trialDays === 1 ? "dia restante" : "dias restantes"}</span> : null}</div><div className="mt-6 flex flex-wrap gap-2"><Button variant="lime" onClick={onManage}>{terminated ? "Contratar plano" : "Alterar plano"}<ArrowRight className="h-4 w-4" /></Button>{context.capabilities.canCancel && !subscription.cancelAtPeriodEnd ? <Button variant="ghost" onClick={onCancel}>Cancelar assinatura</Button> : null}</div></div><div className="border-t border-line bg-muted/50 p-5 sm:p-7 lg:border-l lg:border-t-0"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-subtle">Principais recursos</p>{features.length ? <ul className="mt-4 space-y-3">{features.map(([code, value]) => <li key={code} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{featureName(code)}{typeof value === "number" ? `: ${value}` : ""}</li>)}</ul> : <p className="mt-4 text-sm text-subtle">Os recursos do plano aparecerão aqui.</p>}</div></div></Card>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-subtle">{label}</p><p className="mt-1 text-sm font-extrabold">{value}</p></div>; }
function EmptySubscription({ onCompare }: { onCompare: () => void }) { return <Card className="border-dashed p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-lime/40"><Crown className="h-6 w-6" /></div><h2 className="mt-4 text-xl font-extrabold">Sua empresa ainda não possui uma assinatura</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-subtle">Compare as opções disponíveis para escolher o plano adequado à sua operação.</p><Button className="mt-5" onClick={onCompare}>Comparar planos</Button></Card>; }

function CompanyContextRequired() { return <Card className="mx-auto max-w-2xl p-8 text-center"><CircleAlert className="mx-auto h-8 w-8 text-amber-500" /><h1 className="mt-4 text-xl font-extrabold">Selecione uma empresa</h1><p className="mt-2 text-sm leading-6 text-subtle">Escolha uma empresa no seletor superior para consultar planos, assinatura e uso.</p></Card>; }

function SectionLoading({ label }: { label: string }) { return <Card className="h-40 animate-pulse bg-white" aria-busy="true" aria-label={label} />; }

function PartialError({ title, error, onRetry, retrying }: { title: string; error: unknown; onRetry: () => void; retrying: boolean }) { const copy = errorPresentation(error); return <Card className="p-6" role="alert"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><CircleAlert className="h-6 w-6 shrink-0 text-amber-500" /><div className="min-w-0 flex-1"><h2 className="font-extrabold">{title}</h2><p className="mt-1 text-sm font-bold text-ink">{copy.title}</p><p className="mt-1 text-sm leading-6 text-subtle">{copy.message}</p>{copy.requestId ? <p className="mt-2 text-[10px] text-subtle">Identificador da solicitação: {copy.requestId}</p> : null}</div><Button variant="outline" onClick={onRetry} disabled={retrying}>{retrying ? <><Loader2 className="h-4 w-4 animate-spin" /> Tentando novamente...</> : <><RefreshCw className="h-4 w-4" /> Tentar novamente</>}</Button></div></Card>; }

function UsageSection({ items, onCompare }: { items: UsageItem[]; onCompare: () => void }) {
  return <section aria-labelledby="subscription-usage-title"><div className="mb-4"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-subtle">Limites</p><h2 id="subscription-usage-title" className="mt-1 text-xl font-extrabold">Uso no período atual</h2></div>{items.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <UsageCard key={item.featureCode} item={item} onCompare={onCompare} />)}</div> : <Card className="p-6 text-sm text-subtle">Nenhum consumo registrado neste período.</Card>}</section>;
}
function UsageCard({ item, onCompare }: { item: UsageItem; onCompare: () => void }) {
  const state = usagePresentation(item); const Icon = state.tone === "limit" || state.tone === "blocked" ? CircleAlert : state.tone === "normal" ? Gauge : TriangleAlert; const color = state.tone === "limit" || state.tone === "blocked" ? "bg-red-500" : state.tone === "near" ? "bg-orange-500" : state.tone === "attention" ? "bg-amber-400" : "bg-lime-dark";
  return <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{featureName(item.featureName || item.featureCode)}</p><p className="mt-1 text-[11px] text-subtle">{formatDate(item.periodStart)} a {formatDate(item.periodEnd)}</p></div><Icon className="h-5 w-5 text-amber-600" /></div><div className="mt-5 flex items-end justify-between"><div><p className="text-2xl font-extrabold">{item.used}</p><p className="text-[11px] text-subtle">utilizados</p></div><div className="text-right">{item.unlimited ? <p className="inline-flex items-center gap-1 text-sm font-extrabold"><InfinityIcon className="h-4 w-4" /> Ilimitado</p> : <><p className="text-sm font-extrabold">{item.remaining ?? 0} restantes</p><p className="text-[11px] text-subtle">limite de {item.limit ?? 0}</p></>}</div></div>{!item.unlimited ? <div className="mt-4"><div className="h-2.5 overflow-hidden rounded-full bg-muted" role="progressbar" aria-label={`Uso de ${featureName(item.featureCode)}`} aria-valuenow={state.percentage} aria-valuemin={0} aria-valuemax={100}><div className={cn("h-full rounded-full", color)} style={{ width: `${state.percentage}%` }} /></div><div className="mt-2 flex justify-between text-[11px]"><span className="font-bold text-subtle">{state.label}</span><strong>{state.percentage}%</strong></div></div> : <p className="mt-4 text-[11px] font-bold text-emerald-700">Sem limite de utilização</p>}{["limit", "near", "blocked"].includes(state.tone) ? <Button className="mt-4 w-full" size="sm" variant="outline" onClick={onCompare}>Comparar planos</Button> : null}</Card>;
}

const PlanGrid = React.forwardRef<HTMLElement, { plans: SubscriptionPlan[]; cycle: BillingCycle; context?: SubscriptionContext; onCycle: (cycle: BillingCycle) => void; onSelect: (plan: SubscriptionPlan) => void }>(function PlanGrid({ plans, cycle, context, onCycle, onSelect }, ref) {
  return <section ref={ref} aria-labelledby="subscription-plans-title" className="scroll-mt-4"><div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-subtle">Escolha com transparência</p><h2 id="subscription-plans-title" className="mt-1 text-xl font-extrabold">Compare os planos</h2><p className="mt-1 text-sm text-subtle">Todos incluem o Portal Contábil.</p></div><div className="inline-flex w-fit rounded-xl border border-line bg-white p-1" role="group" aria-label="Ciclo de cobrança">{(["MONTHLY", "ANNUAL"] as const).map((item) => <button key={item} type="button" aria-pressed={cycle === item} onClick={() => onCycle(item)} className={cn("rounded-lg px-4 py-2 text-xs font-extrabold", cycle === item ? "bg-lime shadow-sm" : "text-subtle")}>{formatCycle(item)}</button>)}</div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <PlanCard key={plan.id} plan={plan} cycle={cycle} context={context} onSelect={() => onSelect(plan)} />)}</div></section>;
});

function PlanCard({ plan, cycle, context, onSelect }: { plan: SubscriptionPlan; cycle: BillingCycle; context?: SubscriptionContext; onSelect: () => void }) {
  const price = plan.prices.find((item) => item.billingCycle === cycle); const action = planAction(plan, cycle, context); const savings = annualSavings(plan); const recommended = plan.code === "BUSINESS";
  return <Card className={cn("relative flex min-w-0 flex-col overflow-hidden p-5", recommended && "border-ink shadow-card", action === "CURRENT" && "ring-2 ring-lime-dark/40")}>{recommended ? <div className="-mx-5 -mt-5 mb-5 bg-ink px-5 py-2 text-center text-[10px] font-extrabold uppercase tracking-[0.14em] text-lime">Mais recomendado</div> : null}<div className="flex items-start justify-between gap-2"><div><h3 className="text-lg font-extrabold">{plan.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-subtle">{plan.description ?? "Recursos para sua operação fiscal."}</p></div>{action === "CURRENT" ? <Badge variant="lime">Atual</Badge> : null}</div><div className="mt-5"><p className="text-3xl font-extrabold tracking-tight">{price ? formatMoney(price.amountCents, price.currency) : "Indisponível"}</p><p className="mt-1 text-[11px] text-subtle">{cycle === "MONTHLY" ? "por mês" : "por ano"}</p>{cycle === "ANNUAL" && savings > 0 ? <p className="mt-2 text-xs font-extrabold text-emerald-700">Economize {formatMoney(savings)} por ano</p> : null}</div><ul className="my-6 flex-1 space-y-3">{Object.entries(plan.features).slice(0, 8).map(([code, value]) => { const enabled = isEnabledFeature(value); return <li key={code} className={cn("flex items-start gap-2 text-xs leading-5", !enabled && "text-subtle")}><span className={cn("mt-0.5 grid h-4 w-4 shrink-0 place-items-center rounded-full", enabled ? "bg-lime/50" : "bg-muted")}>{enabled ? <Check className="h-3 w-3" /> : <X className="h-3 w-3" />}</span><span>{featureName(code)}{typeof value === "number" ? `: ${value}` : ""}</span></li>; })}</ul><Button className="w-full" variant={recommended && action !== "CURRENT" ? "lime" : "outline"} disabled={action === "CURRENT" || action === "UNAVAILABLE" || !price} onClick={onSelect}>{planActionCopy(action)}</Button>{action === "UPGRADE" ? <p className="mt-2 text-center text-[10px] text-subtle">Aplicação imediata</p> : action === "DOWNGRADE" || action === "CYCLE" ? <p className="mt-2 text-center text-[10px] text-subtle">Aplicação no próximo período</p> : null}</Card>;
}

function ChangeDialog({ selection, cycle, context, plans, pending, error, onClose, onConfirm }: { selection: Selection | null; cycle: BillingCycle; context?: SubscriptionContext; plans: SubscriptionPlan[]; pending: boolean; error: unknown; onClose: () => void; onConfirm: () => void }) {
  const targetPrice = selection?.plan.prices.find((item) => item.billingCycle === cycle); const currentPlan = plans.find((plan) => plan.code === context?.plan?.code); const currentFeatures = new Set(Object.entries(currentPlan?.features ?? {}).filter(([, value]) => isEnabledFeature(value)).map(([code]) => code)); const targetFeatures = new Set(Object.entries(selection?.plan.features ?? {}).filter(([, value]) => isEnabledFeature(value)).map(([code]) => code)); const added = [...targetFeatures].filter((code) => !currentFeatures.has(code)).slice(0, 5); const removed = [...currentFeatures].filter((code) => !targetFeatures.has(code)).slice(0, 5); const title = selection?.action === "UPGRADE" ? "Confirmar upgrade" : selection?.action === "DOWNGRADE" ? "Agendar downgrade" : "Alterar ciclo de cobrança";
  return <Dialog open={Boolean(selection)} onOpenChange={(open) => { if (!open && !pending) onClose(); }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl" aria-describedby="plan-change-description"><DialogTitle>{title}</DialogTitle><DialogDescription id="plan-change-description">Revise a mudança antes de confirmar.</DialogDescription>{selection ? <div className="mt-5 space-y-5"><div className="grid gap-3 rounded-2xl bg-muted p-4 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><PlanSnapshot label="Plano atual" name={context?.plan?.name ?? "Sem plano"} price={context?.price ? formatMoney(context.price.amountCents, context.price.currency) : "—"} cycle={context?.subscription ? formatCycle(context.subscription.billingCycle) : "—"} /><ArrowRight className="hidden h-5 w-5 text-subtle sm:block" /><PlanSnapshot label="Novo plano" name={selection.plan.name} price={targetPrice ? formatMoney(targetPrice.amountCents, targetPrice.currency) : "—"} cycle={formatCycle(cycle)} /></div>{selection.action === "UPGRADE" ? <div className="rounded-2xl border border-lime-dark/20 bg-lime/20 p-4 text-sm leading-6"><strong>A alteração será aplicada imediatamente.</strong> Nenhuma cobrança será realizada automaticamente nesta etapa. Não haverá prorrata automática.</div> : <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-4 text-sm leading-6">O plano atual continua disponível até {formatDate(context?.subscription?.currentPeriodEnd)}. A mudança será aplicada no período seguinte.</div>}{added.length ? <FeatureDelta title="Recursos adicionados" items={added} positive /> : null}{removed.length ? <FeatureDelta title="Recursos que deixarão de estar disponíveis" items={removed} /> : null}<MutationError error={error} /><DialogActions pending={pending} onClose={onClose} onConfirm={onConfirm} confirm={selection.action === "UPGRADE" ? "Confirmar upgrade" : selection.action === "DOWNGRADE" ? "Agendar downgrade" : "Confirmar novo ciclo"} /></div> : null}</DialogContent></Dialog>;
}
function PlanSnapshot({ label, name, price, cycle }: { label: string; name: string; price: string; cycle: string }) { return <div><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-subtle">{label}</p><p className="mt-1 font-extrabold">{name}</p><p className="mt-1 text-xs text-subtle">{price} · {cycle}</p></div>; }
function FeatureDelta({ title, items, positive = false }: { title: string; items: string[]; positive?: boolean }) { return <div><p className="text-xs font-extrabold uppercase tracking-[0.1em] text-subtle">{title}</p><ul className="mt-2 space-y-2">{items.map((item) => <li key={item} className="flex items-center gap-2 text-sm">{positive ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : <X className="h-4 w-4 text-red-500" />}{featureName(item)}</li>)}</ul></div>; }

function CancelDialog({ intent, context, pending, error, onMode, onClose, onConfirm }: { intent: CancelIntent | null; context?: SubscriptionContext; pending: boolean; error: unknown; onMode: (mode: CancelIntent["mode"]) => void; onClose: () => void; onConfirm: () => void }) {
  const [confirmation, setConfirmation] = useState(""); const immediate = intent?.mode === "IMMEDIATE"; const valid = !immediate || confirmation.trim().toUpperCase() === "CANCELAR";
  return <Dialog open={Boolean(intent)} onOpenChange={(open) => { if (!open && !pending) { setConfirmation(""); onClose(); } }}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl" aria-describedby="cancel-description"><DialogTitle>Cancelar assinatura</DialogTitle><DialogDescription id="cancel-description">Escolha quando o acesso deve ser encerrado.</DialogDescription>{intent ? <div className="mt-5 space-y-4"><label className={cn("block cursor-pointer rounded-2xl border p-4", !immediate && "border-lime-dark bg-lime/15")}><span className="flex gap-3"><input type="radio" name="cancel-mode" checked={!immediate} onChange={() => { setConfirmation(""); onMode("PERIOD_END"); }} /><span><strong className="block text-sm">Cancelar no fim do período</strong><span className="mt-1 block text-xs leading-5 text-subtle">O acesso permanece até {formatDate(context?.subscription?.currentPeriodEnd)} e pode ser reativado. Mudanças agendadas serão removidas.</span></span></span></label><label className={cn("block cursor-pointer rounded-2xl border p-4", immediate && "border-red-300 bg-red-50")}><span className="flex gap-3"><input type="radio" name="cancel-mode" checked={immediate} onChange={() => onMode("IMMEDIATE")} /><span><strong className="block text-sm text-red-700">Cancelar imediatamente</strong><span className="mt-1 block text-xs leading-5 text-subtle">O acesso é encerrado agora e não há reativação simples. Dados e histórico permanecem; nenhuma devolução financeira é criada automaticamente.</span></span></span></label>{immediate ? <Input label="Digite CANCELAR para confirmar" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" helperText="Esta confirmação evita cancelamentos acidentais." /> : null}<MutationError error={error} /><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={onClose} disabled={pending}>Manter assinatura</Button><Button type="button" variant={immediate ? "destructive" : "default"} onClick={onConfirm} disabled={pending || !valid}>{pending ? <><Loader2 className="h-4 w-4 animate-spin" /> Processando...</> : immediate ? "Cancelar imediatamente" : "Programar cancelamento"}</Button></div></div> : null}</DialogContent></Dialog>;
}
function ReactivateDialog({ open, context, pending, error, onClose, onConfirm }: { open: boolean; context?: SubscriptionContext; pending: boolean; error: unknown; onClose: () => void; onConfirm: () => void }) { return <Dialog open={open} onOpenChange={(next) => { if (!next && !pending) onClose(); }}><DialogContent aria-describedby="reactivate-description"><DialogTitle>Manter assinatura</DialogTitle><DialogDescription id="reactivate-description">Remova o cancelamento programado e continue com o plano atual.</DialogDescription><div className="mt-5 space-y-5"><div className="rounded-2xl bg-lime/20 p-4 text-sm leading-6">Seu plano {context?.plan?.name} será mantido. O encerramento previsto para {formatDate(context?.subscription?.currentPeriodEnd)} será cancelado.</div><MutationError error={error} /><DialogActions pending={pending} onClose={onClose} onConfirm={onConfirm} confirm="Manter assinatura" /></div></DialogContent></Dialog>; }

function MutationError({ error }: { error: unknown }) { if (!error) return null; const copy = errorPresentation(error); return <div className="rounded-2xl border border-red-200 bg-red-50 p-4" role="alert"><div className="flex gap-3"><CircleAlert className="h-5 w-5 shrink-0 text-red-600" /><div><p className="text-sm font-extrabold text-red-800">{copy.title}</p><p className="mt-1 text-xs leading-5 text-red-700">{copy.message}</p>{copy.requestId ? <p className="mt-2 text-[10px] text-red-600">Identificador da solicitação: {copy.requestId}</p> : null}</div></div></div>; }
function DialogActions({ pending, onClose, onConfirm, confirm }: { pending: boolean; onClose: () => void; onConfirm: () => void; confirm: string }) { return <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={onClose} disabled={pending}>Voltar</Button><Button onClick={onConfirm} disabled={pending}>{pending ? <><Loader2 className="h-4 w-4 animate-spin" /> Processando...</> : confirm}</Button></div>; }
function PageError({ error, onRetry, retrying }: { error: unknown; onRetry: () => void; retrying: boolean }) { const copy = errorPresentation(error); return <Card className="mx-auto max-w-2xl p-8 text-center"><CircleAlert className="mx-auto h-8 w-8 text-amber-500" /><h1 className="mt-4 text-xl font-extrabold">{copy.title}</h1><p className="mt-2 text-sm leading-6 text-subtle">{copy.message}</p>{copy.requestId ? <p className="mt-3 text-[10px] text-subtle">Identificador da solicitação: {copy.requestId}</p> : null}<Button className="mt-6" onClick={onRetry} disabled={retrying}>{retrying ? <><Loader2 className="h-4 w-4 animate-spin" /> Tentando novamente...</> : <><RefreshCw className="h-4 w-4" /> Tentar novamente</>}</Button></Card>; }
function SubscriptionSkeleton() { return <div className="space-y-6" aria-busy="true" aria-label="Carregando assinatura"><div className="h-40 animate-pulse rounded-3xl bg-white" /><div className="h-64 animate-pulse rounded-2xl bg-white" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-52 animate-pulse rounded-2xl bg-white" />)}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-[430px] animate-pulse rounded-2xl bg-white" />)}</div></div>; }
