ALTER TABLE "marketplace_listing_links" ADD COLUMN "promotional_price" DECIMAL(15,2);
ALTER TABLE "marketplace_listing_links" ADD COLUMN "product_id" UUID;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "stock" INTEGER;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "category" TEXT;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "condition" TEXT;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "listing_type" TEXT;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "reserved_stock" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_listing_links" ADD COLUMN "last_error" TEXT;
ALTER TABLE "marketplace_orders" ADD COLUMN "commission_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "fixed_fee_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "tax_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "ads_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "product_cost" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "refund_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "chargeback_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "marketplace_orders" ADD COLUMN "financial_receivable_id" UUID;
ALTER TABLE "marketplace_orders" ADD COLUMN "reconciliation_id" UUID;
ALTER TABLE "marketplace_orders" ADD COLUMN "stock_reserved_at" TIMESTAMP(3);
ALTER TABLE "marketplace_orders" ADD COLUMN "internal_canceled_at" TIMESTAMP(3);
ALTER TABLE "marketplace_order_items" ADD COLUMN "product_id" UUID;
ALTER TABLE "marketplace_order_items" ADD COLUMN "unit_cost" DECIMAL(15,2) NOT NULL DEFAULT 0;
CREATE TABLE "commerce_pricing_strategies" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" TEXT NOT NULL,"inputs" JSONB NOT NULL,"result" JSONB NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "commerce_pricing_strategies_pkey" PRIMARY KEY("id"));
CREATE INDEX "commerce_pricing_strategies_company_id_created_at_idx" ON "commerce_pricing_strategies"("company_id","created_at");
CREATE TABLE "commerce_competition_records" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"product_id" UUID,"listing_id" UUID,"competitor" TEXT NOT NULL,"price" DECIMAL(15,2) NOT NULL,"freight" DECIMAL(15,2) NOT NULL DEFAULT 0,"reputation" TEXT,"rating" DECIMAL(5,2),"delivery_days" INTEGER,"position" INTEGER,"source_url" TEXT,"source" TEXT NOT NULL DEFAULT 'MANUAL',"collected_at" TIMESTAMP(3) NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "commerce_competition_records_pkey" PRIMARY KEY("id"));
CREATE INDEX "commerce_competition_records_company_id_product_id_collected_at_idx" ON "commerce_competition_records"("company_id","product_id","collected_at");
CREATE TABLE "commerce_opportunities" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"type" VARCHAR(60) NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"evidence" JSONB NOT NULL,"impact" DECIMAL(15,2) NOT NULL DEFAULT 0,"priority" VARCHAR(20) NOT NULL,"provider" TEXT,"product_id" UUID,"listing_id" UUID,"assignee" TEXT,"status" VARCHAR(30) NOT NULL DEFAULT 'OPEN',"justification" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "commerce_opportunities_pkey" PRIMARY KEY("id"));
CREATE INDEX "commerce_opportunities_company_id_status_priority_idx" ON "commerce_opportunities"("company_id","status","priority");
CREATE TABLE "commerce_ad_metrics" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"connection_id" UUID,"provider_campaign_id" TEXT NOT NULL,"campaign_name" TEXT NOT NULL,"listing_id" UUID,"period_start" TIMESTAMP(3) NOT NULL,"period_end" TIMESTAMP(3) NOT NULL,"investment" DECIMAL(15,2) NOT NULL,"attributed_revenue" DECIMAL(15,2),"attributed_orders" INTEGER,"status" VARCHAR(30) NOT NULL,"promotion" JSONB,"source" TEXT NOT NULL DEFAULT 'PROVIDER_API',"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "commerce_ad_metrics_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "commerce_ad_metrics_company_id_provider_campaign_id_period_start_period_end_key" ON "commerce_ad_metrics"("company_id","provider_campaign_id","period_start","period_end");
CREATE INDEX "commerce_ad_metrics_company_id_period_start_period_end_idx" ON "commerce_ad_metrics"("company_id","period_start","period_end");
