"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useMemo, useRef, useState } from "react";
import { ArrowLeft, CircleDollarSign, ExternalLink, Pencil, Plus, RefreshCw, RotateCcw, Search, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/page-header";
import { notify } from "@/components/toast-viewport";
import { ApiError, getSessionUser } from "@/lib/api";
import { formatCurrency } from "@/lib/utils";
import { useCancelPayable, useCreatePayable, usePayable, usePayableOptions, usePayables, useReopenPayable, useReversePayable, useSettlePayable, useUpdatePayable } from "@/lib/services/payables/payable-hooks";
import { validatePayable, type PayableErrors } from "@/lib/services/payables/payable-schemas";
import type { Payable, PayableInput } from "@/lib/services/payables/payable-types";

const statusLabels: Record<string,string>={PENDING:"Em aberto",OPEN:"Em aberto",OVERDUE:"Vencida",PARTIALLY_PAID:"Parcialmente paga",PAID:"Paga",CANCELED:"Cancelada",DRAFT:"Rascunho"};
const sourceLabels: Record<string,string>={PURCHASE_ORDER:"Pedido de compra",NFE_ENTRY:"NF-e de entrada",MANUAL:"Lançamento manual"};
const date=(value?:string|null)=>value?new Intl.DateTimeFormat("pt-BR").format(new Date(value)):"—";
const dateTime=(value?:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
const money=(value?:string|null)=>formatCurrency(Number(value||0));
const badge=(status:string)=><Badge variant={status==="PAID"?"success":status==="CANCELED"?"neutral":status==="OVERDUE"?"danger":"warning"}>{statusLabels[status]||status}</Badge>;
const originLabel=(item:Payable)=>sourceLabels[item.sourceType||item.source]||item.sourceType||item.source||"Manual";
function originHref(item:Payable){if(!item.sourceId)return null;if(item.sourceType==="PURCHASE_ORDER")return`/operacao/compras/${item.sourceId}`;if(item.sourceType==="NFE_ENTRY")return`/documents/incoming?id=${item.sourceId}`;return null}
const selectClass="h-11 w-full rounded-xl border border-line bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-ink/10";

function Loading(){return <div aria-label="Carregando" className="grid gap-3 md:grid-cols-3">{Array.from({length:6},(_,i)=><Card key={i} className="h-24 animate-pulse bg-muted"/>)}</div>}
function ErrorState({message,retry}:{message:string;retry:()=>void}){return <Card className="p-8 text-center"><p className="text-sm text-red-700">{message}</p><Button className="mt-4" variant="outline" onClick={retry}><RefreshCw className="h-4 w-4"/>Tentar novamente</Button></Card>}

export function PayablesList(){
 const router=useRouter(),[q,setQ]=useState(""),[status,setStatus]=useState(""),[source,setSource]=useState(""),[page,setPage]=useState(1),[sort,setSort]=useState("dueDate"),[settling,setSettling]=useState<Payable|null>(null),canWrite=getSessionUser()?.role!=="VIEWER";
 const query=usePayables({q,status,source,page,pageSize:20}),rows=useMemo(()=>[...(query.data?.data||[])].sort((a,b)=>sort==="amount"?Number(b.amount)-Number(a.amount):new Date(a.dueDate).getTime()-new Date(b.dueDate).getTime()),[query.data,sort]);
 const metrics=useMemo(()=>({open:rows.filter(x=>!["PAID","CANCELED"].includes(x.status)).reduce((s,x)=>s+Number(x.balance),0),overdue:rows.filter(x=>x.status==="OVERDUE").reduce((s,x)=>s+Number(x.balance),0),future:rows.filter(x=>x.status==="PENDING").reduce((s,x)=>s+Number(x.balance),0),paid:rows.reduce((s,x)=>s+Number(x.paidAmount||0),0),count:query.data?.pagination.total||0,overdueCount:rows.filter(x=>x.status==="OVERDUE").length}),[rows,query.data]);
 return <>
  <PageHeader eyebrow="Financeiro" title="Contas a pagar" description="Obrigações, vencimentos, baixas e rastreabilidade financeira." icon={CircleDollarSign} action={canWrite?<Button variant="lime" asChild><Link href="/financeiro/contas-a-pagar/nova"><Plus className="h-4 w-4"/>Nova conta</Link></Button>:undefined}/>
  <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Total em aberto",metrics.open],["Total vencido",metrics.overdue],["Total a vencer",metrics.future],["Pago",metrics.paid],["Contas",metrics.count],["Vencidas",metrics.overdueCount]].map(([label,value],i)=><Card className="p-4" key={String(label)}><p className="text-xs text-subtle">{label}</p><p className="mt-2 text-lg font-extrabold">{i<4?money(String(value)):value}</p></Card>)}</div>
  <Card className="mb-4 grid gap-3 p-4 md:grid-cols-5"><label className="relative md:col-span-2"><span className="sr-only">Buscar</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-subtle"/><input className={`${selectClass} pl-9`} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Descrição ou fornecedor"/></label><select aria-label="Status" className={selectClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos os status</option>{["PENDING","OVERDUE","PARTIALLY_PAID","PAID","CANCELED"].map(x=><option key={x} value={x}>{statusLabels[x]}</option>)}</select><select aria-label="Origem" className={selectClass} value={source} onChange={e=>{setSource(e.target.value);setPage(1)}}><option value="">Todas as origens</option><option value="MANUAL">Manual</option><option value="PURCHASE_ORDER">Pedido de compra</option><option value="NFE_ENTRY">NF-e de entrada</option></select><select aria-label="Ordenação" className={selectClass} value={sort} onChange={e=>setSort(e.target.value)}><option value="dueDate">Vencimento</option><option value="amount">Maior valor</option></select></Card>
  {query.isLoading?<Loading/>:query.isError?<ErrorState message={query.error.message} retry={()=>query.refetch()}/>:<Card className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-muted text-subtle"><tr>{["Descrição","Fornecedor","Parcela","Origem","Emissão","Vencimento","Valor","Pago","Saldo","Status","Ações"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(item=><tr className="border-t" key={item.id}><td className="p-3 font-bold">{item.description||"Sem descrição"}</td><td className="p-3">{item.supplierName||"—"}</td><td className="p-3">{item.installmentNumber}/{item.totalInstallments}</td><td className="p-3">{originLabel(item)}</td><td className="p-3">{date(item.issueDate)}</td><td className="p-3">{date(item.dueDate)}</td><td className="p-3">{money(item.amount)}</td><td className="p-3">{money(item.paidAmount)}</td><td className="p-3 font-bold">{money(item.balance)}</td><td className="p-3">{badge(item.status)}</td><td className="p-3"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>router.push(`/financeiro/contas-a-pagar/${item.id}`)}>Visualizar</Button>{canWrite&&!['PAID','CANCELED'].includes(item.status)&&<Button size="sm" variant="lime" onClick={()=>setSettling(item)}>Baixar</Button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={11} className="p-12 text-center text-subtle">Nenhuma conta a pagar encontrada.</td></tr>}</tbody></table><div className="flex items-center justify-end gap-3 border-t p-3"><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Anterior</Button><span>{page}/{query.data?.pagination.totalPages||1}</span><Button variant="outline" size="sm" disabled={page>=(query.data?.pagination.totalPages||1)} onClick={()=>setPage(x=>x+1)}>Próxima</Button></div></Card>}
  <SettlementDialog payable={settling} open={Boolean(settling)} onOpenChange={open=>!open&&setSettling(null)}/>
 </>
}

const empty:PayableInput={description:"",supplierName:"",issueDate:new Date().toISOString().slice(0,10),dueDate:"",amount:"",categoryId:"",costCenterId:"",financialAccountId:"",notes:""};
export function PayableForm({payableId}:{payableId?:string}){
 const router=useRouter(),detail=usePayable(payableId||""),options=usePayableOptions(),create=useCreatePayable(),update=useUpdatePayable(),[form,setForm]=useState<PayableInput>(empty),[loaded,setLoaded]=useState(false),[errors,setErrors]=useState<PayableErrors>({}),saveAndOpen=useRef(false),setSaveAndOpen=(value:boolean)=>{saveAndOpen.current=value},canWrite=getSessionUser()?.role!=="VIEWER";
 if(payableId&&detail.data&&!loaded){const x=detail.data;setForm({description:x.description||"",supplierId:x.supplierId,supplierName:x.supplierName||"",issueDate:x.issueDate?.slice(0,10)||"",dueDate:x.dueDate.slice(0,10),amount:x.amount,categoryId:x.categoryId||"",costCenterId:x.costCenterId||"",financialAccountId:x.financialAccountId||"",notes:x.notes||""});setLoaded(true)}
 const blocked=Boolean(payableId&&detail.data&&(["PAID","CANCELED"].includes(detail.data.status)||!canWrite)),automatic=Boolean(detail.data?.sourceType&&detail.data.sourceType!=="MANUAL");
 const set=(key:keyof PayableInput,value:string)=>setForm(v=>({...v,[key]:value||null}));
 const submit=(event:FormEvent)=>{
  event.preventDefault();
  const next=validatePayable(form);setErrors(next);if(Object.keys(next).length)return;
  const callbacks={
   onSuccess:(result:unknown)=>{const id=payableId||((result as {data:Payable[]}).data[0]?.id);notify({title:payableId?"Conta atualizada":"Conta criada",tone:"success"});router.push((payableId||saveAndOpen.current)&&id?`/financeiro/contas-a-pagar/${id}`:"/financeiro/contas-a-pagar")},
   onError:(error:Error)=>notify({title:"Não foi possível salvar",description:error.message,tone:"error"}),
  };
  if(payableId)update.mutate({id:payableId,input:form},callbacks);else create.mutate(form,callbacks);
 };
 if(payableId&&detail.isLoading)return <Loading/>;if(payableId&&detail.isError)return <ErrorState message={detail.error.message} retry={()=>detail.refetch()}/>;
 return <form onSubmit={submit}><PageHeader eyebrow="Contas a pagar" title={payableId?"Editar conta":"Nova conta"} description={automatic?`Origem protegida: ${originLabel(detail.data!)}`:"Lançamento manual; a origem é definida pelo sistema."} icon={WalletCards}/><Card className="grid gap-4 p-5 md:grid-cols-2"><Input label="Descrição" value={form.description} disabled={blocked} error={errors.description} onChange={e=>set("description",e.target.value)}/><Input label="Fornecedor" value={form.supplierName||""} disabled={blocked} onChange={e=>set("supplierName",e.target.value)}/><Input label="Data de emissão" type="date" value={form.issueDate||""} disabled={blocked} onChange={e=>set("issueDate",e.target.value)}/><Input label="Vencimento" type="date" value={form.dueDate} disabled={blocked} error={errors.dueDate} onChange={e=>set("dueDate",e.target.value)}/><Input label="Valor (R$)" inputMode="decimal" value={form.amount} disabled={blocked||automatic} error={errors.amount} onChange={e=>set("amount",e.target.value.replace(",","."))}/><FieldSelect label="Categoria" value={form.categoryId||""} disabled={blocked} options={options.data?.categories} onChange={value=>set("categoryId",value)}/><FieldSelect label="Centro de custo" value={form.costCenterId||""} disabled={blocked} options={options.data?.centers} onChange={value=>set("costCenterId",value)}/><FieldSelect label="Conta financeira" value={form.financialAccountId||""} disabled={blocked} options={options.data?.accounts} onChange={value=>set("financialAccountId",value)}/><label className="md:col-span-2 text-sm font-medium">Observações<textarea className="mt-1 min-h-28 w-full rounded-xl border border-line p-3 font-normal" value={form.notes||""} disabled={blocked} onChange={e=>set("notes",e.target.value)}/></label>{automatic&&<div className="md:col-span-2 rounded-xl bg-muted p-3 text-xs">{originLabel(detail.data!)} · {detail.data?.sourceId}. A origem e seus identificadores não podem ser alterados.</div>}</Card><div className="mt-5 flex flex-wrap justify-end gap-3"><Button type="button" variant="outline" onClick={()=>router.back()}>Cancelar</Button>{!blocked&&<><Button type="submit" disabled={create.isPending||update.isPending} onClick={()=>setSaveAndOpen(false)}>Salvar</Button>{!payableId&&<Button type="submit" variant="lime" disabled={create.isPending} onClick={()=>setSaveAndOpen(true)}>Salvar e abrir</Button>}</>}</div></form>
}
function FieldSelect({label,value,options,onChange,disabled}:{label:string;value:string;options?:Array<{id:string;name:string}>;onChange:(v:string)=>void;disabled?:boolean}){return <label className="text-sm font-medium">{label}<select className={`${selectClass} mt-1 font-normal`} value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Não informado</option>{options?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}

export function PayableDetail({payableId}:{payableId:string}){
 const query=usePayable(payableId),cancel=useCancelPayable(),reverse=useReversePayable(),reopen=useReopenPayable(),[settle,setSettle]=useState(false),[reopenOpen,setReopenOpen]=useState(false),canWrite=getSessionUser()?.role!=="VIEWER";
 if(query.isLoading)return <Loading/>;if(query.isError)return <ErrorState message={query.error instanceof ApiError&&query.error.status===404?"Conta a pagar não encontrada.":query.error.message} retry={()=>query.refetch()}/>;const item=query.data!;const origin=originHref(item),events=item.history||[],payments=events.filter(x=>/settled|reversed/.test(x.action));
 const cancelItem=()=>{const reason=window.prompt("Justificativa do cancelamento (mínimo 10 caracteres):");if(reason)cancel.mutate({id:item.id,reason},{onSuccess:()=>notify({title:"Conta cancelada"}),onError:e=>notify({title:"Cancelamento bloqueado",description:e.message,tone:"error"})})};
 const reverseItem=()=>{if(!window.confirm("Estornar as baixas desta conta?"))return;const reason=window.prompt("Justificativa do estorno (mínimo 10 caracteres):");if(reason)reverse.mutate({id:item.id,reason},{onSuccess:()=>notify({title:"Baixa estornada"}),onError:e=>notify({title:"Estorno bloqueado",description:e.message,tone:"error"})})};
 const reopenItem=(reason:string)=>reopen.mutate({id:item.id,reason},{onSuccess:()=>{notify({title:"Conta reaberta"});setReopenOpen(false)},onError:e=>notify({title:"Reabertura bloqueada",description:e.message,tone:"error"})});
 return <><PageHeader eyebrow="Contas a pagar" title={item.description||"Detalhe da conta"} description={`${originLabel(item)} · atualizada em ${dateTime(item.updatedAt)}`} icon={CircleDollarSign} action={<div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link href="/financeiro/contas-a-pagar"><ArrowLeft className="h-4 w-4"/>Voltar</Link></Button>{canWrite&&!['PAID','CANCELED'].includes(item.status)&&<Button variant="outline" asChild><Link href={`/financeiro/contas-a-pagar/${item.id}/editar`}><Pencil className="h-4 w-4"/>Editar</Link></Button>}{canWrite&&!['PAID','CANCELED'].includes(item.status)&&<Button variant="lime" onClick={()=>setSettle(true)}>Baixar</Button>}{canWrite&&item.status==="CANCELED"&&<Button variant="lime" onClick={()=>setReopenOpen(true)}><RotateCcw className="h-4 w-4"/>Reabrir</Button>}</div>}/>
 <div className="grid gap-5 xl:grid-cols-3"><Card className="p-5 xl:col-span-2"><div className="flex justify-between"><h2 className="font-extrabold">Resumo</h2>{badge(item.status)}</div><dl className="mt-5 grid gap-4 sm:grid-cols-3">{[["Fornecedor",item.supplierName||"—"],["Parcela",`${item.installmentNumber}/${item.totalInstallments}`],["Emissão",date(item.issueDate)],["Vencimento",date(item.dueDate)],["Valor original",money(item.amount)],["Valor pago",money(item.paidAmount)],["Saldo",money(item.balance)],["Método",item.paymentMethod||"—"],["Criada em",dateTime(item.createdAt)]].map(([k,v])=><div key={k}><dt className="text-xs text-subtle">{k}</dt><dd className="mt-1 font-bold">{v}</dd></div>)}</dl>{item.cancellationReason&&<p className="mt-5 rounded-xl bg-muted p-3 text-sm"><strong>Cancelada:</strong> {item.cancellationReason}</p>}{item.notes&&<p className="mt-5 rounded-xl bg-muted p-3 text-sm">{item.notes}</p>}</Card><Card className="p-5"><h2 className="font-extrabold">Origem</h2><p className="mt-3 text-sm">{originLabel(item)}</p><p className="mt-1 break-all text-xs text-subtle">{item.sourceId||"Identificador interno manual"}</p>{origin?<Button className="mt-4" variant="outline" asChild><Link href={origin}><ExternalLink className="h-4 w-4"/>Abrir origem</Link></Button>:<p className="mt-4 text-xs text-subtle">Origem não disponível para navegação.</p>}</Card></div>
 <Card className="mt-5 overflow-x-auto p-5"><h2 className="font-extrabold">Pagamentos e movimentos</h2>{payments.length?<table className="mt-4 w-full min-w-[700px] text-left text-xs"><thead><tr>{["Data","Evento","Valor","Movimento","Justificativa"].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{payments.map(x=><tr className="border-t" key={x.id}><td className="p-2">{dateTime(x.createdAt)}</td><td className="p-2">{eventLabel(x.action)}</td><td className="p-2">{money(String(x.metadata?.amount||0))}</td><td className="p-2">{String(x.metadata?.movementId||"—")}</td><td className="p-2">{x.justification||"—"}</td></tr>)}</tbody></table>:<p className="mt-4 text-sm text-subtle">Nenhuma baixa registrada.</p>}{canWrite&&Number(item.paidAmount)>0&&item.status!=="CANCELED"&&<Button className="mt-4" variant="danger" disabled={reverse.isPending} onClick={reverseItem}><RotateCcw className="h-4 w-4"/>Estornar baixa</Button>}</Card>
 <Card className="mt-5 p-5"><h2 className="font-extrabold">Timeline e auditoria</h2><ol className="mt-4 space-y-4">{events.map(x=><li className="border-l-2 border-lime pl-4" key={x.id}><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{eventLabel(x.action)}</p><time className="text-xs text-subtle">{dateTime(x.createdAt)}</time></div>{x.justification&&<p className="mt-1 text-sm text-subtle">{x.justification}</p>}</li>)}{!events.length&&<li className="text-sm text-subtle">Nenhum evento disponível.</li>}</ol></Card>
 {canWrite&&item.status==="CANCELED"&&<div className="mt-5"><ReopenPayableDialog open={reopenOpen} onOpenChange={setReopenOpen} onSubmit={reopenItem} pending={reopen.isPending}/></div>}
 {canWrite&&!['PAID','CANCELED'].includes(item.status)&&<div className="mt-5 flex justify-end"><Button variant="danger" disabled={cancel.isPending} onClick={cancelItem}>Cancelar conta</Button></div>}<SettlementDialog payable={item} open={settle} onOpenChange={setSettle}/></>
}
const eventLabel=(action:string)=>({"payable.created":"Conta criada","payable.updated":"Conta atualizada","payable.partially_settled":"Baixa parcial","payable.settled":"Baixa total","payable.canceled":"Conta cancelada","payable.reversed":"Baixa estornada","payable.reopened":"Conta reaberta","payable.settlement_rejected":"Baixa rejeitada"}[action]||action.replaceAll("_"," "));

function ReopenPayableDialog({open,onOpenChange,onSubmit,pending}:{open:boolean;onOpenChange:(open:boolean)=>void;onSubmit:(reason:string)=>void;pending?:boolean}){
 const[reason,setReason]=useState(""),input=useRef<HTMLInputElement>(null),close=(value:boolean)=>{onOpenChange(value);if(!value)setReason("")};
 return <Dialog open={open} onOpenChange={close}><DialogContent onOpenAutoFocus={()=>setTimeout(()=>input.current?.focus(),0)}><DialogTitle>Reabrir conta a pagar</DialogTitle><DialogDescription>A conta retornará ao status de aberta. Justificativa obrigatória (mínimo 10 caracteres).</DialogDescription><div className="mt-5 grid gap-4"><Input ref={input} label="Justificativa" value={reason} error={reason&&reason.trim().length<10?"Informe ao menos 10 caracteres.":undefined} onChange={e=>setReason(e.target.value)}/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>close(false)}>Voltar</Button><Button variant="lime" disabled={reason.trim().length<10||Boolean(pending)} onClick={()=>onSubmit(reason.trim())}>{pending?"Reabrindo…":"Confirmar reabertura"}</Button></div></div></DialogContent></Dialog>
}

function SettlementDialog({payable,open,onOpenChange}:{payable:Payable|null;open:boolean;onOpenChange:(open:boolean)=>void}){
 const mutation=useSettlePayable(),options=usePayableOptions(),[amount,setAmount]=useState(""),[dateValue,setDate]=useState(new Date().toISOString().slice(0,10)),[account,setAccount]=useState(""),[method,setMethod]=useState("PIX"),input=useRef<HTMLInputElement>(null),balance=Number(payable?.balance||0),after=Math.max(0,balance-Number(amount||0)),invalid=!amount||Number(amount)<=0||Number(amount)>balance||!account;
 const close=(value:boolean)=>{onOpenChange(value);if(!value){setAmount("");setAccount("")}};
 const submit=()=>{if(!payable||invalid)return;mutation.mutate({id:payable.id,amount,date:dateValue,financialAccountId:account,method},{onSuccess:()=>{notify({title:Number(amount)===balance?"Baixa total registrada":"Baixa parcial registrada"});close(false)},onError:e=>notify({title:"Baixa rejeitada",description:e.message,tone:"error"})})};
 return <Dialog open={open} onOpenChange={close}><DialogContent onOpenAutoFocus={()=>setTimeout(()=>input.current?.focus(),0)}><DialogTitle>Registrar baixa</DialogTitle><DialogDescription>Saldo atual {money(payable?.balance)}. Após a baixa: {money(String(after))} ({Number(amount)===balance?"total":"parcial"}).</DialogDescription><div className="mt-5 grid gap-4"><Input ref={input} label="Valor (R$)" inputMode="decimal" value={amount} error={Number(amount)>balance?"O valor supera o saldo.":undefined} onChange={e=>setAmount(e.target.value.replace(",","."))}/><Input label="Data" type="date" value={dateValue} onChange={e=>setDate(e.target.value)}/><FieldSelect label="Conta financeira" value={account} options={options.data?.accounts} onChange={setAccount}/><label className="text-sm font-medium">Método<select className={`${selectClass} mt-1`} value={method} onChange={e=>setMethod(e.target.value)}><option>PIX</option><option>BOLETO</option><option>TRANSFERÊNCIA</option><option>DINHEIRO</option><option>CARTÃO</option></select></label><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>close(false)}>Voltar</Button><Button variant="lime" disabled={invalid||mutation.isPending} onClick={submit}>{mutation.isPending?"Registrando…":"Confirmar baixa"}</Button></div></div></DialogContent></Dialog>
}
