export interface Fornecedor {
  id: string;
  companyId: string;
  tipoPessoa: "PJ" | "PF";
  nome: string | null;
  razaoSocial: string | null;
  nomeFantasia: string | null;
  cpf: string | null;
  cnpj: string | null;
  inscricaoEstadual: string | null;
  inscricaoMunicipal: string | null;
  regimeTributario: string | null;
  crt: string | null;
  indicadorIe: string | null;
  tipoContribuinte: string | null;
  contribuinteIcms: boolean | null;
  cnae: string | null;
  atividadeEconomica: string | null;
  naturezaJuridica: string | null;
  situacaoCadastral: string | null;
  porte: string | null;
  optanteSimples: boolean | null;
  mei: boolean | null;
  tipoFornecedor: string | null;
  categoria: string | null;
  condicaoPagamento: string | null;
  prazoMedioDias: number | null;
  limiteCredito: string | null;
  banco: string | null;
  agencia: string | null;
  contaBancaria: string | null;
  chavePix: string | null;
  responsavelComercial: string | null;
  emailFiscal: string | null;
  emailFinanceiro: string | null;
  retemImpostos: boolean | null;
  recorrente: boolean | null;
  emiteNfe: boolean | null;
  emiteNfse: boolean | null;
  exigePedidoCompra: boolean | null;
  cep: string | null;
  logradouro: string | null;
  numero: string | null;
  complemento: string | null;
  bairro: string | null;
  municipio: string | null;
  uf: string | null;
  codigoIbge: string | null;
  codigoUfIbge: string | null;
  pais: string | null;
  email: string | null;
  telefone: string | null;
  whatsapp: string | null;
  observacoes: string | null;
  fonteDados: string | null;
  ativo: boolean;
  dadosOriginaisJson: unknown;
  createdAt: string;
  updatedAt: string;
}
