export interface Transportadora {
  id: string;
  companyId: string;
  tipoPessoa: "PJ" | "PF";
  nome: string | null;
  razaoSocial: string | null;
  nomeFantasia: string | null;
  cpf: string | null;
  cnpj: string | null;
  inscricaoEstadual: string | null;
  inscricaoMunicipal: string | null;
  regimeTributario: string | null;
  crt: string | null;
  indicadorIe: string | null;
  tipoContribuinte: string | null;
  contribuinteIcms: boolean | null;
  antt: string | null;
  rntrc: string | null;
  tipoTransportadora: string | null;
  placaVeiculo: string | null;
  ufPlaca: string | null;
  tipoVeiculo: string | null;
  modalidadeFrete: string | null;
  permiteColeta: boolean | null;
  permiteEntrega: boolean | null;
  cargaPerigosa: boolean | null;
  temSeguro: boolean | null;
  apoliceSeguro: string | null;
  cep: string | null;
  logradouro: string | null;
  numero: string | null;
  complemento: string | null;
  bairro: string | null;
  municipio: string | null;
  uf: string | null;
  codigoIbge: string | null;
  codigoUfIbge: string | null;
  pais: string | null;
  email: string | null;
  telefone: string | null;
  whatsapp: string | null;
  observacoes: string | null;
  fonteDados: string | null;
  ativo: boolean;
  dadosOriginaisJson: unknown;
  createdAt: string;
  updatedAt: string;
}
