/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useSettings, useSettingsMutation } from "@/lib/services/settings/hooks";
import type { AuditItem, IntegrationSetting, SettingsKind } from "@/lib/services/settings/types";
const meta:Record<SettingsKind,[string,string]>={overview:["Configurações","Central de configuração da empresa e segurança."],company:["Empresa","Dados cadastrais e ambiente operacional."],fiscal:["Fiscal","Parâmetros e bloqueios para emissão fiscal."],certificate:["Certificado Digital","Validade e segurança do certificado A1."],integrations:["Integrações","Providers externos e serviços locais."],users:["Usuários e Permissões","Acessos efetivos da empresa."],security:["Segurança e Auditoria","Histórico sanitizado de ações do sistema."]};
export function SettingsView({kind}:{kind:SettingsKind}){
 const query=useSettings(kind); const mutation=useSettingsMutation(); const [form,setForm]=useState<Record<string,string>>({});
 useEffect(()=>{if(kind==="company"&&query.data)setForm(Object.fromEntries(Object.entries(query.data).filter(([,v])=>typeof v==="string")) as Record<string,string>);},[kind,query.data]);
 const data=query.data||{};
 return <><PageHeader eyebrow="Configurações" title={meta[kind][0]} description={meta[kind][1]}/>
 {query.isLoading?<div className="grid gap-3 md:grid-cols-3">{[1,2,3].map(i=><Card key={i} className="h-28 animate-pulse bg-slate-100"/>)}</div>:query.isError?<Card className="p-8"><p>Não foi possível carregar.</p><Button onClick={()=>query.refetch()}>Tentar novamente</Button></Card>:
 kind==="overview"?<Overview data={data}/>:kind==="company"?<CompanyForm form={form} setForm={setForm} save={()=>mutation.mutate({type:"company",body:{legalName:form.legalName,tradeName:form.tradeName||null,stateRegistration:form.stateRegistration||null,uf:form.uf,city:form.city||null,environment:form.environment as "production"|"homologation",taxRegime:form.taxRegime,confirmCriticalChange:true}})} pending={mutation.isPending}/>:kind==="fiscal"?<Fiscal data={data}/>:kind==="certificate"?<Certificate data={data} revoke={()=>{if(confirm("Revogar internamente este certificado?"))mutation.mutate({type:"revoke"});}}/>:kind==="integrations"?<Integrations items={(data.items||[]) as IntegrationSetting[]} run={(provider,action)=>mutation.mutate({type:"integration",provider,action})}/>:kind==="users"?<Users items={(data.items||[]) as Array<Record<string,unknown>>}/>:<Audit items={(data.items||[]) as AuditItem[]}/>}
 </>;
}
function Overview({data: _data}:{data:Record<string,unknown>}){const links=[["Empresa","/settings/company"],["Fiscal","/settings/fiscal"],["Certificado","/settings/certificate"],["Integrações","/settings/integrations"],["Usuários","/settings/users"],["Segurança/Auditoria","/settings/security"]];return <div className="grid gap-4 md:grid-cols-3">{links.map(([label,href])=><Card key={href} className="p-5"><h2 className="font-bold">{label}</h2><Button className="mt-4" variant="outline" asChild><Link href={href}>Abrir</Link></Button></Card>)}</div>}
function CompanyForm({form,setForm,save,pending}:{form:Record<string,string>;setForm:(v:Record<string,string>)=>void;save:()=>void;pending:boolean}){const fields=[["legalName","Razão social"],["tradeName","Nome fantasia"],["stateRegistration","Inscrição estadual"],["uf","UF"],["city","Município"],["taxRegime","Regime tributário"]];return <Card className="grid gap-4 p-6 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className="text-sm font-bold">{label}<Input className="mt-1" value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="text-sm font-bold">Ambiente<select className="mt-1 h-10 w-full rounded-xl border bg-white px-3" value={form.environment||"homologation"} onChange={e=>setForm({...form,environment:e.target.value})}><option value="homologation">Homologação</option><option value="production">Produção</option></select></label><div className="md:col-span-2"><Button disabled={pending} onClick={save}>{pending?"Salvando…":"Salvar com confirmação"}</Button></div></Card>}
function Fiscal({data}:{data:Record<string,unknown>}){const issues=(data.issues||[]) as Array<{code:string;message:string;severity:string}>;return <><Card className="mb-4 p-5"><p>Ambiente: <Badge>{String(data.environment)}</Badge></p><p className="mt-2">Transmissão: <Badge>{data.transmissionAllowed?"LIBERADA":"BLOQUEADA"}</Badge></p></Card><div className="space-y-3">{issues.length?issues.map(i=><Card className="p-4" key={i.code}><Badge>{i.severity}</Badge><p className="mt-2">{i.message}</p></Card>):<Card className="p-6">Nenhuma pendência fiscal bloqueante.</Card>}</div></>}
function Certificate({data,revoke}:{data:Record<string,unknown>;revoke:()=>void}){return <Card className="p-6"><Badge>{String(data.status)}</Badge><h2 className="mt-3 font-bold">{String(data.subject||"Certificado não configurado")}</h2><p>Emissor: {String(data.issuer||"—")}</p><p>Dias restantes: {String(data.daysRemaining??"—")}</p><div className="mt-4 flex gap-2"><Button asChild><Link href="/certificate">Gerenciar A1</Link></Button>{data.status!=="NOT_CONFIGURED"&&<Button variant="outline" onClick={revoke}>Revogar internamente</Button>}</div></Card>}
function Integrations({items,run}:{items:IntegrationSetting[];run:(p:string,a:string)=>void}){return <div className="grid gap-4 md:grid-cols-2">{items.map(i=><Card key={i.provider} className="p-5"><div className="flex justify-between"><h2 className="font-bold">{i.provider}</h2><Badge>{i.status}</Badge></div><p className="text-sm text-subtle">{i.module}</p>{i.lastError&&<p className="mt-2 text-sm text-red-700">{i.lastError}</p>}<div className="mt-4 flex gap-2"><Button size="sm" variant="outline" disabled={i.status==="CONFIGURATION_REQUIRED"} onClick={()=>run(i.provider,"test")}>Testar</Button><Button size="sm" variant="outline" onClick={()=>run(i.provider,"deactivate")}>Desativar</Button></div></Card>)}</div>}
function Users({items}:{items:Array<Record<string,unknown>>}){return <Card className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-4">Usuário</th><th>E-mail</th><th>Perfil</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr className="border-t" key={String(i.id)}><td className="p-4">{String(i.name)}</td><td>{String(i.email)}</td><td><Badge>{String(i.role)}</Badge></td><td>{String(i.status)}</td></tr>)}</tbody></table></Card>}
function Audit({items}:{items:AuditItem[]}){return <Card className="overflow-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr><th className="p-4">Data</th><th>Usuário</th><th>Ação</th><th>Recurso</th><th>IP</th></tr></thead><tbody>{items.map(i=><tr className="border-t" key={i.id}><td className="p-4">{new Date(i.createdAt).toLocaleString("pt-BR")}</td><td>{i.user?.name||"Sistema"}</td><td>{i.action}</td><td>{i.entityType||"—"}</td><td>{i.ipAddress||"—"}</td></tr>)}</tbody></table>{!items.length&&<p className="p-8 text-center">Nenhum evento auditável.</p>}</Card>}
