import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { createServer } from "node:http";
import jwt from "jsonwebtoken";
import { app } from "../../src/app.js";
import { env } from "../../src/config/env.js";
import { prisma, disconnectDatabase } from "../../src/config/prisma.js";

let server,baseUrl,owner,admin,company,otherCompany;
const token=(user)=>jwt.sign({sub:user.id,role:user.role,email:user.email},env.JWT_SECRET,{expiresIn:"1h"});
async function call(path,{user,headers={},...init}={}){const requestHeaders=new Headers(headers);if(user)requestHeaders.set("authorization",`Bearer ${token(user)}`);if(init.body&&!requestHeaders.has("content-type"))requestHeaders.set("content-type","application/json");const response=await fetch(`${baseUrl}${path}`,{...init,headers:requestHeaders});return {response,body:await response.json().catch(()=>({}))};}
before(async()=>{owner=await prisma.user.create({data:{name:"Subscription HTTP Owner",email:`owner-${crypto.randomUUID()}@test.local`,passwordHash:"x",role:"OWNER"}});admin=await prisma.user.create({data:{name:"Subscription HTTP Admin",email:`admin-${crypto.randomUUID()}@test.local`,passwordHash:"x",role:"ADMIN"}});company=await prisma.company.create({data:{ownerId:owner.id,legalName:"Subscription HTTP Company",cnpj:String(Math.floor(Math.random()*9e13+1e13)),uf:"SP",city:"Sao Paulo",environment:"homologation"}});otherCompany=await prisma.company.create({data:{ownerId:admin.id,legalName:"Other HTTP Company",cnpj:String(Math.floor(Math.random()*9e13+1e13)),uf:"SP",city:"Sao Paulo",environment:"homologation"}});server=createServer(app);await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));baseUrl=`http://127.0.0.1:${server.address().port}`;});
after(async()=>{for(const companyId of [company.id,otherCompany.id]){const subscriptions=await prisma.subscription.findMany({where:{companyId},select:{id:true}});const ids=subscriptions.map(({id})=>id);if(ids.length){await prisma.subscriptionUsage.deleteMany({where:{subscriptionId:{in:ids}}});await prisma.subscriptionUsageCounter.deleteMany({where:{subscriptionId:{in:ids}}});await prisma.subscriptionHistory.deleteMany({where:{subscriptionId:{in:ids}}});await prisma.subscription.deleteMany({where:{id:{in:ids}}});}await prisma.company.delete({where:{id:companyId}});}await prisma.user.deleteMany({where:{id:{in:[owner.id,admin.id]}}});await new Promise(resolve=>server.close(resolve));await disconnectDatabase();});

test("subscription HTTP: autenticacao, tenant e catalogo",async()=>{assert.equal((await call(`/api/companies/${company.id}/subscription/catalog`)).response.status,401);const catalog=await call(`/api/companies/${company.id}/subscription/catalog`,{user:owner});assert.equal(catalog.response.status,200);assert.equal(catalog.body.plans.length,4);assert.equal((await call(`/api/companies/${otherCompany.id}/subscription/current`,{user:owner})).response.status,404);});
test("subscription HTTP: current sem assinatura retorna DTO vazio",async()=>{const result=await call(`/api/companies/${company.id}/subscription/current`,{user:owner});assert.equal(result.response.status,200);assert.equal(result.body.subscription,null);});
test("subscription HTTP: criacao manual exige ADMIN e ignora ator externo",async()=>{const payload=JSON.stringify({companyId:company.id,planCode:"PROFESSIONAL",billingCycle:"MONTHLY",trialDays:0,reason:"HTTP test"});assert.equal((await call("/api/internal/subscriptions/manual",{user:owner,method:"POST",headers:{"idempotency-key":"manual-owner"},body:payload})).response.status,403);const created=await call("/api/internal/subscriptions/manual",{user:admin,method:"POST",headers:{"idempotency-key":"manual-admin"},body:payload});assert.equal(created.response.status,201);assert.equal(created.body.subscription.companyId,company.id);const history=await prisma.subscriptionHistory.findFirst({where:{subscriptionId:created.body.subscription.id,idempotencyKey:"manual-admin"}});assert.equal(history.actorId,admin.id);});
test("subscription HTTP: mutacoes exigem Idempotency-Key valida",async()=>{const path=`/api/companies/${company.id}/subscription/change`;const payload=JSON.stringify({targetPlanCode:"BUSINESS",targetBillingCycle:"MONTHLY"});assert.equal((await call(path,{user:owner,method:"POST",body:payload})).response.status,400);assert.equal((await call(path,{user:owner,method:"POST",headers:{"idempotency-key":" ",},body:payload})).response.status,400);assert.equal((await call(path,{user:owner,method:"POST",headers:{"idempotency-key":"x".repeat(161)},body:payload})).response.status,400);});
test("subscription HTTP: upgrade, replay e conflito sao estruturados",async()=>{const path=`/api/companies/${company.id}/subscription/change`;const body=JSON.stringify({targetPlanCode:"BUSINESS",targetBillingCycle:"MONTHLY",reason:"upgrade"});const first=await call(path,{user:owner,method:"POST",headers:{"idempotency-key":"http-change"},body});assert.equal(first.response.status,200);assert.equal(first.body.result,"APPLIED_NOW");const replay=await call(path,{user:owner,method:"POST",headers:{"idempotency-key":"http-change"},body});assert.equal(replay.body.result,"IDEMPOTENT_REPLAY");const conflict=await call(path,{user:owner,method:"POST",headers:{"idempotency-key":"http-change"},body:JSON.stringify({targetPlanCode:"COMPANY",targetBillingCycle:"MONTHLY"})});assert.equal(conflict.response.status,409);assert.equal(conflict.body.code,"SUBSCRIPTION_IDEMPOTENCY_CONFLICT");assert.equal(await prisma.subscriptionHistory.count({where:{idempotencyKey:"http-change"}}),1);});
test("subscription HTTP: payload comercial forjado e companyId no body sao rejeitados",async()=>{const response=await call(`/api/companies/${company.id}/subscription/cancel`,{user:owner,method:"POST",headers:{"idempotency-key":"forged"},body:JSON.stringify({mode:"PERIOD_END",companyId:otherCompany.id,actorId:admin.id,amountCents:1})});assert.equal(response.response.status,400);assert.equal(response.body.code,"SUBSCRIPTION_PAYLOAD_INVALID");});
test("subscription HTTP: downgrade, usage, cancelamento programado e reativacao",async()=>{const change=await call(`/api/companies/${company.id}/subscription/change`,{user:owner,method:"POST",headers:{"idempotency-key":"http-downgrade"},body:JSON.stringify({targetPlanCode:"PROFESSIONAL",targetBillingCycle:"ANNUAL"})});assert.equal(change.response.status,200);assert.equal(change.body.result,"SCHEDULED");const current=await call(`/api/companies/${company.id}/subscription/current`,{user:owner});assert.equal(current.body.plan.code,"BUSINESS");assert.equal(current.body.nextPlan.code,"PROFESSIONAL");const usage=await call(`/api/companies/${company.id}/subscription/usage`,{user:owner});assert.equal(usage.response.status,200);assert.ok(Array.isArray(usage.body.items));const canceled=await call(`/api/companies/${company.id}/subscription/cancel`,{user:owner,method:"POST",headers:{"idempotency-key":"http-cancel"},body:JSON.stringify({mode:"PERIOD_END"})});assert.equal(canceled.body.subscription.cancelAtPeriodEnd,true);const reactivated=await call(`/api/companies/${company.id}/subscription/reactivate`,{user:owner,method:"POST",headers:{"idempotency-key":"http-reactivate"}});assert.equal(reactivated.body.subscription.cancelAtPeriodEnd,false);});
test("subscription HTTP: feature gate retorna 403 estruturado para plano Starter",async()=>{const payload=JSON.stringify({companyId:otherCompany.id,planCode:"STARTER",billingCycle:"MONTHLY",trialDays:0});const created=await call("/api/internal/subscriptions/manual",{user:admin,method:"POST",headers:{"idempotency-key":"starter-other"},body:payload});assert.equal(created.response.status,201);const denied=await call(`/api/companies/${otherCompany.id}/sync/nfe`,{user:admin,method:"POST",body:"{}"});assert.equal(denied.response.status,403);assert.equal(denied.body.code,"SUBSCRIPTION_FEATURE_NOT_AVAILABLE");});
