import pg from "pg";

const DIRECT_URL =
  "postgresql://postgres:PHFABIAN%40%402008@db.dcjsxfobvpqtaygafksi.supabase.co:5432/postgres";

const CFOPS = [
  ["1101", "Compra para industrialização de mercadoria recebida de terceiros", "entrada", "Compra", true, false, false],
  ["1102", "Compra para comercialização de mercadoria recebida de terceiros", "entrada", "Compra", true, false, false],
  ["1103", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", true, false, false],
  ["1104", "Industrialização efetuada por outra empresa", "entrada", "Industrialização", true, false, false],
  ["1111", "Compra para industrialização de mercadoria recebida do exterior", "entrada", "Importação", false, false, true],
  ["1113", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Compra", true, false, false],
  ["1116", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", true, false, false],
  ["1117", "Compra para industrialização por conta e ordem do adquirente", "entrada", "Compra", true, false, false],
  ["1118", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["1120", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["1121", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP, sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["1124", "Industrialização efetuada para a empresa em mercadoria de sua propriedade", "entrada", "Industrialização", true, false, false],
  ["1125", "Industrialização em mercadoria de propriedade do adquirente", "entrada", "Industrialização", true, false, false],
  ["1126", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["1151", "Transferência para industrialização de mercadoria recebida de terceiros", "entrada", "Transferência", true, false, false],
  ["1152", "Transferência para industrialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", true, false, false],
  ["1201", "Devolução de venda de produção do estabelecimento", "entrada", "Devolução", true, false, false],
  ["1202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", "entrada", "Devolução", true, false, false],
  ["1203", "Devolução de venda de produção do estabelecimento, efetuada fora do estabelecimento", "entrada", "Devolução", true, false, false],
  ["1204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "entrada", "Devolução", true, false, false],
  ["1205", "Anulação de valor relativo à prestação de serviço de transporte", "entrada", "Devolução", true, false, false],
  ["1206", "Anulação de valor relativo à venda de produção do estabelecimento quando cobrado em separado", "entrada", "Devolução", true, false, false],
  ["1207", "Anulação de valor relativo à venda de mercadoria adquirida ou recebida de terceiros quando cobrado em separado", "entrada", "Devolução", true, false, false],
  ["1208", "Anulação de valor relativo aos serviços prestados", "entrada", "Devolução", true, false, false],
  ["1209", "Anulação de valor relativo a despesas acessórias", "entrada", "Devolução", true, false, false],
  ["1251", "Devolução de venda de produção do estabelecimento sob o regime de não incidência ou isenção", "entrada", "Devolução", true, false, false],
  ["1252", "Devolução de venda de mercadoria adquirida ou recebida de terceiros sob o regime de não incidência ou isenção", "entrada", "Devolução", true, false, false],
  ["1253", "Devolução de venda de produção do estabelecimento sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["1254", "Devolução de venda de mercadoria adquirida ou recebida de terceiros sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["1255", "Anulação de valor relativo à prestação de serviço de transporte sob o regime de não incidência ou isenção", "entrada", "Devolução", true, false, false],
  ["1256", "Anulação de valor relativo à prestação de serviço de transporte sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["1257", "Anulação de valor relativo à venda de produção do estabelecimento sob o regime de não incidência ou isenção quando cobrado em separado", "entrada", "Devolução", true, false, false],
  ["1301", "Compra para industrialização de mercadoria recebida de terceiros", "entrada", "Compra", false, true, false],
  ["1302", "Compra para comercialização de mercadoria recebida de terceiros", "entrada", "Compra", false, true, false],
  ["1303", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", false, true, false],
  ["1304", "Industrialização efetuada por outra empresa", "entrada", "Industrialização", false, true, false],
  ["1305", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["1306", "Compra para industrialização por conta e ordem do adquirente", "entrada", "Compra", false, true, false],
  ["1311", "Compra para industrialização de mercadoria recebida do exterior", "entrada", "Importação", false, true, true],
  ["1312", "Compra para comercialização de mercadoria recebida do exterior", "entrada", "Importação", false, true, true],
  ["1313", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Compra", false, true, false],
  ["1316", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", false, true, false],
  ["1317", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["1321", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["1351", "Transferência para industrialização de mercadoria recebida de terceiros", "entrada", "Transferência", false, true, false],
  ["1352", "Transferência para industrialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", false, true, false],
  ["1353", "Transferência para comercialização de mercadoria recebida de terceiros", "entrada", "Transferência", false, true, false],
  ["1354", "Transferência para comercialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", false, true, false],
  ["1355", "Transferência para comercialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1356", "Transferência para industrialização de mercadoria produzida pelo estabelecimento em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1360", "Transferência para comercialização de mercadoria produzida pelo estabelecimento em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1401", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["1403", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["1406", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["1407", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["1408", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["1409", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, para entrega futura", "entrada", "Compra", true, false, false],
  ["1410", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, com incidência de IPI", "entrada", "Compra", true, false, false],
  ["1411", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, com imunidade de IPI", "entrada", "Compra", true, false, false],
  ["1414", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, para entrega futura", "entrada", "Compra", true, false, false],
  ["1415", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["1451", "Transferência para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", true, false, false],
  ["1452", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", true, false, false],
  ["1501", "Transferência para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1502", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1503", "Transferência para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1504", "Transferência para comercialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1551", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1552", "Compra para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1553", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1554", "Compra para comercialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1555", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1556", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, para entrega futura", "entrada", "Compra", false, true, false],
  ["1557", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, para entrega futura", "entrada", "Compra", false, true, false],
  ["1601", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1602", "Compra para industrialização de mercadoria produzida pelo estabelecimento sem transitar pelo estabelecimento adquirente, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["1603", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["1604", "Compra para comercialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária, sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["1605", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, por conta e ordem do adquirente", "entrada", "Compra", false, true, false],
  ["1651", "Transferência para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1652", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1653", "Transferência para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1654", "Transferência para comercialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["1655", "Transferência para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1656", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária, em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1660", "Transferência para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["1901", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, sujeita ao regime de substituição tributária do IPI", "entrada", "Compra", true, false, false],
  ["1902", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "Industrialização", true, false, false],
  ["1903", "Retorno de mercadoria remetida para conserto", "entrada", "Remessa", true, false, false],
  ["1904", "Retorno de remessa para venda fora do estabelecimento", "entrada", "Remessa", true, false, false],
  ["1905", "Retorno de remessa para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento)", "entrada", "Remessa", true, false, false],
  ["1906", "Retorno de mercadoria remetida para demonstração", "entrada", "Remessa", true, false, false],
  ["1907", "Retorno de mercadoria remetida para exposição", "entrada", "Remessa", true, false, false],
  ["1908", "Retorno de mercadoria remetida para conserto ou consignação", "entrada", "Remessa", true, false, false],
  ["1909", "Retorno de mercadoria remetida para consignação", "entrada", "Remessa", true, false, false],
  ["1910", "Retorno de mercadoria remetida para demonstração (mercadoria recebida para demonstração)", "entrada", "Remessa", true, false, false],
  ["1911", "Retorno de mercadoria remetida para consignação ou demonstração", "entrada", "Remessa", true, false, false],
  ["1912", "Retorno de mercadoria remetida para consignação ou demonstração (mercadoria recebida para consignação ou demonstração)", "entrada", "Remessa", true, false, false],
  ["1913", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["1914", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1915", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1916", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["1917", "Retorno de mercadoria remetida para venda fora do estabelecimento, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1918", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1919", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["1920", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1921", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), sujeita ao regime de substituição tributária, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["1922", "Retorno de mercadoria remetida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["1923", "Retorno de mercadoria remetida para conserto, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["1924", "Retorno de mercadoria remetida para industrialização sob o regime de drawback", "entrada", "Industrialização", true, false, false],
  ["1925", "Retorno de mercadoria remetida para industrialização sob o regime de drawback, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["1930", "Entrada de mercadoria recebida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["1931", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback", "entrada", "Industrialização", true, false, false],
  ["1932", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["1933", "Entrada de mercadoria recebida para industrialização por encomenda, sujeita ao regime de substituição tributária do IPI", "entrada", "Industrialização", true, false, false],
  ["1934", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback, sujeita ao regime de substituição tributária do IPI", "entrada", "Industrialização", true, false, false],
  ["1949", "Retorno de mercadoria remetida para venda fora do estabelecimento", "entrada", "Remessa", false, true, false],
  ["1950", "Retorno de mercadoria remetida para industrialização sob o regime de drawback", "entrada", "Industrialização", false, true, false],
  ["1951", "Retorno de mercadoria remetida para conserto, consignação ou demonstração", "entrada", "Remessa", false, true, false],
  ["1952", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["1953", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["1960", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["1961", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "Industrialização", false, true, false],
  ["1962", "Retorno de mercadoria remetida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", false, true, false],
  ["1963", "Entrada de mercadoria recebida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", false, true, false],
  ["1964", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback", "entrada", "Industrialização", false, true, false],
  ["1965", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback, sujeita ao regime de substituição tributária", "entrada", "Industrialização", false, true, false],
  ["1966", "Retorno de mercadoria remetida para conserto, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["2101", "Compra para industrialização de mercadoria recebida de terceiros", "entrada", "Compra", true, false, false],
  ["2102", "Compra para comercialização de mercadoria recebida de terceiros", "entrada", "Compra", true, false, false],
  ["2103", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", true, false, false],
  ["2104", "Industrialização efetuada por outra empresa", "entrada", "Industrialização", true, false, false],
  ["2106", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["2107", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, com incidência de IPI", "entrada", "Compra", true, false, false],
  ["2108", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["2111", "Compra para industrialização de mercadoria recebida do exterior", "entrada", "Importação", true, false, true],
  ["2113", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Compra", true, false, false],
  ["2114", "Compra para industrialização de mercadoria recebida de terceiros, para entrega futura", "entrada", "Compra", true, false, false],
  ["2116", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", true, false, false],
  ["2117", "Compra para industrialização por conta e ordem do adquirente", "entrada", "Compra", true, false, false],
  ["2118", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["2120", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["2124", "Industrialização efetuada para a empresa em mercadoria de sua propriedade", "entrada", "Industrialização", true, false, false],
  ["2125", "Industrialização em mercadoria de propriedade do adquirente", "entrada", "Industrialização", true, false, false],
  ["2151", "Transferência para industrialização de mercadoria recebida de terceiros", "entrada", "Transferência", true, false, false],
  ["2152", "Transferência para industrialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", true, false, false],
  ["2201", "Devolução de venda de produção do estabelecimento", "entrada", "Devolução", true, false, false],
  ["2202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros", "entrada", "Devolução", true, false, false],
  ["2203", "Devolução de venda de produção do estabelecimento, efetuada fora do estabelecimento", "entrada", "Devolução", true, false, false],
  ["2204", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "entrada", "Devolução", true, false, false],
  ["2210", "Devolução de venda de produção do estabelecimento sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["2211", "Devolução de venda de mercadoria adquirida ou recebida de terceiros sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["2251", "Devolução de venda de produção do estabelecimento sob o regime de não incidência ou isenção", "entrada", "Devolução", true, false, false],
  ["2252", "Devolução de venda de mercadoria adquirida ou recebida de terceiros sob o regime de não incidência ou isenção", "entrada", "Devolução", true, false, false],
  ["2253", "Devolução de venda de produção do estabelecimento sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["2254", "Devolução de venda de mercadoria adquirida ou recebida de terceiros sob o Simples Nacional", "entrada", "Devolução", true, false, false],
  ["2301", "Compra para industrialização de mercadoria recebida de terceiros", "entrada", "Compra", false, true, false],
  ["2302", "Compra para comercialização de mercadoria recebida de terceiros", "entrada", "Compra", false, true, false],
  ["2303", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", false, true, false],
  ["2304", "Industrialização efetuada por outra empresa", "entrada", "Industrialização", false, true, false],
  ["2305", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["2306", "Compra para industrialização por conta e ordem do adquirente", "entrada", "Compra", false, true, false],
  ["2311", "Compra para industrialização de mercadoria recebida do exterior", "entrada", "Importação", false, true, true],
  ["2312", "Compra para comercialização de mercadoria recebida do exterior", "entrada", "Importação", false, true, true],
  ["2313", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Compra", false, true, false],
  ["2316", "Compra para industrialização originada de encomenda para recebimento futuro", "entrada", "Compra", false, true, false],
  ["2317", "Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["2321", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente", "entrada", "Compra", false, true, false],
  ["2351", "Transferência para industrialização de mercadoria recebida de terceiros", "entrada", "Transferência", false, true, false],
  ["2352", "Transferência para industrialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", false, true, false],
  ["2353", "Transferência para comercialização de mercadoria recebida de terceiros", "entrada", "Transferência", false, true, false],
  ["2354", "Transferência para comercialização de mercadoria produzida pelo estabelecimento", "entrada", "Transferência", false, true, false],
  ["2355", "Transferência para comercialização de mercadoria recebida de terceiros, em substituição a outro CFOP", "entrada", "Transferência", false, true, false],
  ["2401", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["2403", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["2406", "Compra para industrialização de mercadoria recebida de terceiros sem transitar pelo estabelecimento adquirente, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["2407", "Compra para industrialização de mercadoria recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "entrada", "Compra", true, false, false],
  ["2408", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária, em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente", "entrada", "Compra", true, false, false],
  ["2501", "Transferência para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", true, false, false],
  ["2502", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", true, false, false],
  ["2503", "Transferência para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["2504", "Transferência para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, true, false],
  ["2551", "Compra para industrialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["2552", "Compra para industrialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["2553", "Compra para comercialização de mercadoria recebida de terceiros, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["2554", "Compra para comercialização de mercadoria produzida pelo estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Compra", false, true, false],
  ["2901", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "Industrialização", true, false, false],
  ["2902", "Retorno de mercadoria remetida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["2903", "Retorno de mercadoria remetida para conserto", "entrada", "Remessa", true, false, false],
  ["2904", "Retorno de remessa para venda fora do estabelecimento", "entrada", "Remessa", true, false, false],
  ["2905", "Retorno de mercadoria remetida para demonstração", "entrada", "Remessa", true, false, false],
  ["2906", "Retorno de mercadoria remetida para exposição", "entrada", "Remessa", true, false, false],
  ["2907", "Retorno de mercadoria remetida para consignação", "entrada", "Remessa", true, false, false],
  ["2908", "Retorno de mercadoria remetida para conserto ou consignação, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["2909", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["2910", "Retorno de mercadoria remetida para venda fora do estabelecimento, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["2911", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["2912", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["2913", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, na hipótese de rescisão do contrato", "entrada", "Remessa", true, false, false],
  ["2914", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["2915", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento)", "entrada", "Remessa", true, false, false],
  ["2916", "Retorno de mercadoria remetida para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), sujeita ao regime de substituição tributária", "entrada", "Remessa", true, false, false],
  ["2920", "Retorno de mercadoria remetida para industrialização sob o regime de drawback", "entrada", "Industrialização", true, false, false],
  ["2921", "Retorno de mercadoria remetida para industrialização sob o regime de drawback, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["2930", "Entrada de mercadoria recebida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", true, false, false],
  ["2931", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback", "entrada", "Industrialização", true, false, false],
  ["2949", "Retorno de mercadoria remetida para venda fora do estabelecimento", "entrada", "Remessa", false, true, false],
  ["2950", "Retorno de mercadoria remetida para industrialização sob o regime de drawback", "entrada", "Industrialização", false, true, false],
  ["2951", "Retorno de mercadoria remetida para conserto, consignação ou demonstração", "entrada", "Remessa", false, true, false],
  ["2952", "Retorno de mercadoria remetida para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["2953", "Retorno de mercadoria remetida para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["2961", "Retorno de mercadoria remetida para industrialização por encomenda", "entrada", "Industrialização", false, true, false],
  ["2962", "Retorno de mercadoria remetida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", false, true, false],
  ["2963", "Entrada de mercadoria recebida para industrialização por encomenda, sujeita ao regime de substituição tributária", "entrada", "Industrialização", false, true, false],
  ["2964", "Entrada de mercadoria recebida para industrialização por encomenda, sob o regime de drawback", "entrada", "Industrialização", false, true, false],
  ["2966", "Retorno de mercadoria remetida para conserto, sujeita ao regime de substituição tributária", "entrada", "Remessa", false, true, false],
  ["3101", "Compra para industrialização de mercadoria recebida de terceiros", "entrada", "Importação", false, false, true],
  ["3102", "Compra para comercialização de mercadoria recebida de terceiros, importada do exterior", "entrada", "Importação", false, false, true],
  ["3103", "Compra para industrialização de mercadoria recebida de terceiros, importada do exterior, por conta e ordem do adquirente", "entrada", "Importação", false, false, true],
  ["3104", "Industrialização efetuada por outra empresa, importada do exterior", "entrada", "Importação", false, false, true],
  ["3105", "Compra para industrialização de mercadoria recebida de terceiros, importada do exterior, sem transitar pelo estabelecimento adquirente", "entrada", "Importação", false, false, true],
  ["3126", "Compra para industrialização de mercadoria recebida de terceiros, importada do exterior, sem transitar pelo estabelecimento adquirente, com imunidade de IPI", "entrada", "Importação", false, false, true],
  ["3127", "Compra para industrialização de mercadoria recebida de terceiros, importada do exterior, por conta e ordem do adquirente, com imunidade de IPI", "entrada", "Importação", false, false, true],
  ["3201", "Devolução de venda de produção do estabelecimento, exportada ao exterior", "entrada", "Devolução", false, false, true],
  ["3202", "Devolução de venda de mercadoria adquirida ou recebida de terceiros, exportada ao exterior", "entrada", "Devolução", false, false, true],
  ["3211", "Devolução de venda de produção do estabelecimento, exportada ao exterior, sob o Simples Nacional", "entrada", "Devolução", false, false, true],
  ["3503", "Transferência para comercialização de mercadoria recebida de terceiros, importada do exterior, sujeita ao regime de substituição tributária", "entrada", "Transferência", false, false, true],
  ["3551", "Compra para industrialização de mercadoria recebida de terceiros, importada do exterior, sujeita ao regime de substituição tributária", "entrada", "Importação", false, false, true],
  ["3553", "Compra para comercialização de mercadoria recebida de terceiros, importada do exterior, sujeita ao regime de substituição tributária", "entrada", "Importação", false, false, true],
  ["5101", "Venda de produção do estabelecimento", "saída", "Venda", true, false, false],
  ["5102", "Venda de mercadoria adquirida ou recebida de terceiros", "saída", "Venda", true, false, false],
  ["5103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", "saída", "Venda", true, false, false],
  ["5104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "saída", "Venda", true, false, false],
  ["5105", "Venda de mercadoria adquirida de terceiros, entregue ao destinatário por conta e ordem do adquirente", "saída", "Venda", true, false, false],
  ["5106", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", true, false, false],
  ["5108", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus", "saída", "Venda", true, false, false],
  ["5109", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus", "saída", "Venda", true, false, false],
  ["5110", "Venda de produção do estabelecimento, destinada à Área de Livre Comércio", "saída", "Venda", true, false, false],
  ["5111", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Área de Livre Comércio", "saída", "Venda", true, false, false],
  ["5112", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus, sob o regime de substituição tributária", "saída", "Venda", true, false, false],
  ["5114", "Venda de produção do estabelecimento, com imunidade do IPI", "saída", "Venda", true, false, false],
  ["5115", "Venda de mercadoria de fabricação própria, remetida anteriormente em consignação industrial", "saída", "Venda", true, false, false],
  ["5116", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", true, false, false],
  ["5117", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", "saída", "Venda", true, false, false],
  ["5118", "Venda de produção do estabelecimento, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", true, false, false],
  ["5119", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", true, false, false],
  ["5120", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", true, false, false],
  ["5122", "Venda de produção do estabelecimento, remetida anteriormente em consignação industrial", "saída", "Venda", true, false, false],
  ["5123", "Venda de produção do estabelecimento, remetida anteriormente em consignação industrial, com imunidade do IPI", "saída", "Venda", true, false, false],
  ["5124", "Industrialização efetuada para outra empresa", "saída", "Industrialização", true, false, false],
  ["5125", "Industrialização efetuada para outra empresa, em mercadoria de propriedade do adquirente", "saída", "Industrialização", true, false, false],
  ["5151", "Transferência de produção do estabelecimento", "saída", "Transferência", true, false, false],
  ["5152", "Transferência de mercadoria adquirida ou recebida de terceiros", "saída", "Transferência", true, false, false],
  ["5153", "Transferência de produção do estabelecimento, em substituição a outro CFOP", "saída", "Transferência", true, false, false],
  ["5155", "Transferência de produção do estabelecimento, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", true, false, false],
  ["5156", "Transferência de mercadoria adquirida ou recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", true, false, false],
  ["5201", "Devolução de compra para industrialização", "saída", "Devolução", true, false, false],
  ["5202", "Devolução de compra para comercialização", "saída", "Devolução", true, false, false],
  ["5205", "Anulação de valor relativo à prestação de serviço de transporte", "saída", "Devolução", true, false, false],
  ["5206", "Anulação de valor relativo à venda de produção do estabelecimento quando cobrado em separado", "saída", "Devolução", true, false, false],
  ["5207", "Anulação de valor relativo à venda de mercadoria adquirida ou recebida de terceiros quando cobrado em separado", "saída", "Devolução", true, false, false],
  ["5208", "Anulação de valor relativo aos serviços prestados", "saída", "Devolução", true, false, false],
  ["5209", "Anulação de valor relativo a despesas acessórias", "saída", "Devolução", true, false, false],
  ["5210", "Devolução de compra para industrialização sob o Simples Nacional", "saída", "Devolução", true, false, false],
  ["5211", "Devolução de compra para comercialização sob o Simples Nacional", "saída", "Devolução", true, false, false],
  ["5251", "Devolução de compra para industrialização sob o regime de não incidência ou isenção", "saída", "Devolução", true, false, false],
  ["5252", "Devolução de compra para comercialização sob o regime de não incidência ou isenção", "saída", "Devolução", true, false, false],
  ["5253", "Devolução de compra para industrialização sob o Simples Nacional", "saída", "Devolução", true, false, false],
  ["5254", "Devolução de compra para comercialização sob o Simples Nacional", "saída", "Devolução", true, false, false],
  ["5301", "Venda de produção do estabelecimento", "saída", "Venda", false, true, false],
  ["5302", "Venda de mercadoria adquirida ou recebida de terceiros", "saída", "Venda", false, true, false],
  ["5303", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", "saída", "Venda", false, true, false],
  ["5304", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "saída", "Venda", false, true, false],
  ["5305", "Venda de mercadoria adquirida de terceiros, entregue ao destinatário por conta e ordem do adquirente", "saída", "Venda", false, true, false],
  ["5306", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["5307", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus", "saída", "Venda", false, true, false],
  ["5308", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus", "saída", "Venda", false, true, false],
  ["5309", "Venda de produção do estabelecimento, destinada à Área de Livre Comércio", "saída", "Venda", false, true, false],
  ["5310", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Área de Livre Comércio", "saída", "Venda", false, true, false],
  ["5311", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus, sob o regime de substituição tributária", "saída", "Venda", false, true, false],
  ["5312", "Venda de produção do estabelecimento, remetida anteriormente em consignação industrial", "saída", "Venda", false, true, false],
  ["5313", "Venda de mercadoria adquirida ou recebida de terceiros, remetida anteriormente em consignação industrial", "saída", "Venda", false, true, false],
  ["5314", "Venda de produção do estabelecimento, com imunidade do IPI", "saída", "Venda", false, true, false],
  ["5315", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["5316", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["5317", "Venda de produção do estabelecimento, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["5318", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["5319", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["5320", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["5321", "Venda de produção do estabelecimento, remetida anteriormente em consignação industrial, com imunidade do IPI", "saída", "Venda", false, true, false],
  ["5322", "Venda de mercadoria adquirida ou recebida de terceiros, com imunidade do IPI", "saída", "Venda", false, true, false],
  ["5324", "Industrialização efetuada para outra empresa", "saída", "Industrialização", false, true, false],
  ["5325", "Industrialização efetuada para outra empresa, em mercadoria de propriedade do adquirente", "saída", "Industrialização", false, true, false],
  ["5351", "Transferência de produção do estabelecimento", "saída", "Transferência", false, true, false],
  ["5352", "Transferência de mercadoria adquirida ou recebida de terceiros", "saída", "Transferência", false, true, false],
  ["5353", "Transferência de produção do estabelecimento, em substituição a outro CFOP", "saída", "Transferência", false, true, false],
  ["5354", "Transferência de produção do estabelecimento, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["5355", "Transferência de mercadoria adquirida ou recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["5356", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["5401", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", true, false, false],
  ["5402", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", true, false, false],
  ["5403", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", true, false, false],
  ["5405", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", true, false, false],
  ["5408", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", true, false, false],
  ["5409", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", true, false, false],
  ["5410", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com incidência de IPI", "saída", "Venda", true, false, false],
  ["5411", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com imunidade de IPI", "saída", "Venda", true, false, false],
  ["5412", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", true, false, false],
  ["5413", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", true, false, false],
  ["5414", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, com incidência de IPI", "saída", "Venda", true, false, false],
  ["5415", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com incidência de IPI", "saída", "Venda", true, false, false],
  ["5416", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, com imunidade de IPI", "saída", "Venda", true, false, false],
  ["5420", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", true, false, false],
  ["5451", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Transferência", true, false, false],
  ["5452", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", true, false, false],
  ["5501", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["5502", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["5503", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["5504", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["5550", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["5551", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", false, true, false],
  ["5552", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["5553", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", false, true, false],
  ["5554", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com incidência de IPI", "saída", "Venda", false, true, false],
  ["5555", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, com incidência de IPI", "saída", "Venda", false, true, false],
  ["5556", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com imunidade de IPI", "saída", "Venda", false, true, false],
  ["5557", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, com imunidade de IPI", "saída", "Venda", false, true, false],
  ["5558", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com incidência de IPI", "saída", "Venda", false, true, false],
  ["5560", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, com imunidade de IPI", "saída", "Venda", false, true, false],
  ["5601", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["5602", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["5603", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Transferência", false, true, false],
  ["5605", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária, com imunidade de IPI", "saída", "Transferência", false, true, false],
  ["5651", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária, em substituição a outro CFOP", "saída", "Transferência", false, true, false],
  ["5652", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, em substituição a outro CFOP", "saída", "Transferência", false, true, false],
  ["5901", "Remessa para industrialização por encomenda", "saída", "Remessa", true, false, false],
  ["5902", "Retorno de mercadoria utilizada na industrialização por encomenda", "saída", "Remessa", true, false, false],
  ["5903", "Remessa para conserto", "saída", "Remessa", true, false, false],
  ["5904", "Retorno de mercadoria remetida para conserto", "saída", "Remessa", true, false, false],
  ["5905", "Remessa para venda fora do estabelecimento", "saída", "Remessa", true, false, false],
  ["5906", "Remessa para demonstração", "saída", "Remessa", true, false, false],
  ["5907", "Remessa para exposição", "saída", "Remessa", true, false, false],
  ["5908", "Remessa para consignação", "saída", "Remessa", true, false, false],
  ["5909", "Remessa para bonificação", "saída", "Bonificação", true, false, false],
  ["5910", "Remessa em bonificação, doação ou brinde", "saída", "Bonificação", true, false, false],
  ["5911", "Remessa para armazém geral", "saída", "Remessa", true, false, false],
  ["5912", "Remessa para depósito fechado", "saída", "Remessa", true, false, false],
  ["5913", "Retorno de mercadoria remetida para armazém geral", "saída", "Remessa", true, false, false],
  ["5914", "Retorno de mercadoria remetida para depósito fechado", "saída", "Remessa", true, false, false],
  ["5915", "Remessa de mercadoria para conserto", "saída", "Remessa", true, false, false],
  ["5916", "Retorno de mercadoria remetida para conserto", "saída", "Remessa", true, false, false],
  ["5917", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Remessa", true, false, false],
  ["5918", "Remessa para venda fora do estabelecimento, na hipótese de rescisão do contrato", "saída", "Remessa", true, false, false],
  ["5919", "Remessa para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento)", "saída", "Remessa", true, false, false],
  ["5920", "Remessa para venda fora do estabelecimento (mercadoria recebida para venda fora do estabelecimento), sujeita ao regime de substituição tributária", "saída", "Remessa", true, false, false],
  ["5921", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária, na hipótese de rescisão do contrato", "saída", "Remessa", true, false, false],
  ["5922", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária", "saída", "Industrialização", true, false, false],
  ["5923", "Remessa para conserto, sujeita ao regime de substituição tributária", "saída", "Remessa", true, false, false],
  ["5924", "Remessa para industrialização sob o regime de drawback", "saída", "Industrialização", true, false, false],
  ["5925", "Remessa para industrialização sob o regime de drawback, sujeita ao regime de substituição tributária", "saída", "Industrialização", true, false, false],
  ["5926", "Remessa para industrialização por encomenda, com incidência de IPI", "saída", "Industrialização", true, false, false],
  ["5927", "Remessa para industrialização por encomenda, com imunidade de IPI", "saída", "Industrialização", true, false, false],
  ["5928", "Remessa de mercadoria para armazém geral, sujeita ao regime de substituição tributária", "saída", "Remessa", true, false, false],
  ["5929", "Remessa de mercadoria para depósito fechado, sujeita ao regime de substituição tributária", "saída", "Remessa", true, false, false],
  ["5931", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária do IPI", "saída", "Industrialização", true, false, false],
  ["5932", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária do IPI e do ICMS", "saída", "Industrialização", true, false, false],
  ["5933", "Remessa para industrialização sob o regime de drawback, sujeita ao regime de substituição tributária do IPI", "saída", "Industrialização", true, false, false],
  ["5949", "Remessa para venda fora do estabelecimento", "saída", "Remessa", false, true, false],
  ["5950", "Remessa para industrialização sob o regime de drawback", "saída", "Industrialização", false, true, false],
  ["5951", "Remessa para conserto, consignação ou demonstração", "saída", "Remessa", false, true, false],
  ["5952", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["5953", "Remessa para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["5960", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["5961", "Remessa para industrialização por encomenda", "saída", "Industrialização", false, true, false],
  ["5962", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária", "saída", "Industrialização", false, true, false],
  ["5963", "Remessa para industrialização por encomenda, com incidência de IPI", "saída", "Industrialização", false, true, false],
  ["5964", "Remessa para industrialização por encomenda, com imunidade de IPI", "saída", "Industrialização", false, true, false],
  ["5966", "Remessa para conserto, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6101", "Venda de produção do estabelecimento", "saída", "Venda", false, true, false],
  ["6102", "Venda de mercadoria adquirida ou recebida de terceiros", "saída", "Venda", false, true, false],
  ["6103", "Venda de produção do estabelecimento, efetuada fora do estabelecimento", "saída", "Venda", false, true, false],
  ["6104", "Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento", "saída", "Venda", false, true, false],
  ["6105", "Venda de mercadoria adquirida de terceiros, entregue ao destinatário por conta e ordem do adquirente", "saída", "Venda", false, true, false],
  ["6106", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["6107", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus", "saída", "Venda", false, true, false],
  ["6108", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus", "saída", "Venda", false, true, false],
  ["6109", "Venda de produção do estabelecimento, destinada à Área de Livre Comércio", "saída", "Venda", false, true, false],
  ["6110", "Venda de mercadoria adquirida ou recebida de terceiros, destinada à Área de Livre Comércio", "saída", "Venda", false, true, false],
  ["6111", "Venda de produção do estabelecimento, destinada à Zona Franca de Manaus, sob o regime de substituição tributária", "saída", "Venda", false, true, false],
  ["6112", "Venda de produção do estabelecimento, remetida anteriormente em consignação industrial", "saída", "Venda", false, true, false],
  ["6113", "Venda de mercadoria adquirida ou recebida de terceiros, remetida anteriormente em consignação industrial", "saída", "Venda", false, true, false],
  ["6114", "Venda de produção do estabelecimento, com imunidade do IPI", "saída", "Venda", false, true, false],
  ["6115", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["6116", "Venda de produção do estabelecimento, originada de encomenda para entrega futura", "saída", "Venda", false, true, false],
  ["6117", "Venda de produção do estabelecimento, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["6118", "Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["6119", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["6120", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["6124", "Industrialização efetuada para outra empresa", "saída", "Industrialização", false, true, false],
  ["6125", "Industrialização efetuada para outra empresa, em mercadoria de propriedade do adquirente", "saída", "Industrialização", false, true, false],
  ["6126", "Industrialização efetuada para outra empresa, em mercadoria de propriedade do adquirente, com imunidade de IPI", "saída", "Industrialização", false, true, false],
  ["6151", "Transferência de produção do estabelecimento", "saída", "Transferência", false, true, false],
  ["6152", "Transferência de mercadoria adquirida ou recebida de terceiros", "saída", "Transferência", false, true, false],
  ["6153", "Transferência de produção do estabelecimento, em substituição a outro CFOP", "saída", "Transferência", false, true, false],
  ["6154", "Transferência de produção do estabelecimento, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6155", "Transferência de mercadoria adquirida ou recebida de terceiros, em substituição a outro CFOP, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6156", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6201", "Devolução de compra para industrialização", "saída", "Devolução", false, true, false],
  ["6202", "Devolução de compra para comercialização", "saída", "Devolução", false, true, false],
  ["6205", "Anulação de valor relativo à prestação de serviço de transporte", "saída", "Devolução", false, true, false],
  ["6206", "Anulação de valor relativo à venda de produção do estabelecimento quando cobrado em separado", "saída", "Devolução", false, true, false],
  ["6207", "Anulação de valor relativo à venda de mercadoria adquirida ou recebida de terceiros quando cobrado em separado", "saída", "Devolução", false, true, false],
  ["6208", "Anulação de valor relativo aos serviços prestados", "saída", "Devolução", false, true, false],
  ["6209", "Anulação de valor relativo a despesas acessórias", "saída", "Devolução", false, true, false],
  ["6210", "Devolução de compra para industrialização sob o Simples Nacional", "saída", "Devolução", false, true, false],
  ["6211", "Devolução de compra para comercialização sob o Simples Nacional", "saída", "Devolução", false, true, false],
  ["6251", "Devolução de compra para industrialização sob o regime de não incidência ou isenção", "saída", "Devolução", false, true, false],
  ["6252", "Devolução de compra para comercialização sob o regime de não incidência ou isenção", "saída", "Devolução", false, true, false],
  ["6253", "Devolução de compra para industrialização sob o Simples Nacional", "saída", "Devolução", false, true, false],
  ["6254", "Devolução de compra para comercialização sob o Simples Nacional", "saída", "Devolução", false, true, false],
  ["6401", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["6402", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["6403", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["6404", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["6408", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["6409", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["6410", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com incidência de IPI", "saída", "Venda", false, true, false],
  ["6411", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, com imunidade de IPI", "saída", "Venda", false, true, false],
  ["6451", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6452", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6501", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["6502", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Venda", false, true, false],
  ["6503", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Venda", false, true, false],
  ["6504", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído", "saída", "Venda", false, true, false],
  ["6550", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["6551", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", false, true, false],
  ["6552", "Venda de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária, na condição de contribuinte substituto, para entrega futura", "saída", "Venda", false, true, false],
  ["6553", "Venda de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituído, para entrega futura", "saída", "Venda", false, true, false],
  ["6601", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6602", "Transferência de mercadoria adquirida ou recebida de terceiros, sujeita ao regime de substituição tributária", "saída", "Transferência", false, true, false],
  ["6603", "Transferência de produção do estabelecimento, sujeita ao regime de substituição tributária, na condição de contribuinte substituto", "saída", "Transferência", false, true, false],
  ["6901", "Remessa para industrialização por encomenda", "saída", "Remessa", false, true, false],
  ["6902", "Retorno de mercadoria utilizada na industrialização por encomenda", "saída", "Remessa", false, true, false],
  ["6903", "Remessa para conserto", "saída", "Remessa", false, true, false],
  ["6904", "Retorno de mercadoria remetida para conserto", "saída", "Remessa", false, true, false],
  ["6905", "Remessa para venda fora do estabelecimento", "saída", "Remessa", false, true, false],
  ["6906", "Remessa para demonstração", "saída", "Remessa", false, true, false],
  ["6907", "Remessa para exposição", "saída", "Remessa", false, true, false],
  ["6908", "Remessa para consignação", "saída", "Remessa", false, true, false],
  ["6909", "Remessa para bonificação", "saída", "Bonificação", false, true, false],
  ["6910", "Remessa em bonificação, doação ou brinde", "saída", "Bonificação", false, true, false],
  ["6911", "Remessa para armazém geral", "saída", "Remessa", false, true, false],
  ["6912", "Remessa para depósito fechado", "saída", "Remessa", false, true, false],
  ["6913", "Retorno de mercadoria remetida para armazém geral", "saída", "Remessa", false, true, false],
  ["6914", "Retorno de mercadoria remetida para depósito fechado", "saída", "Remessa", false, true, false],
  ["6915", "Remessa de mercadoria para conserto", "saída", "Remessa", false, true, false],
  ["6916", "Retorno de mercadoria remetida para conserto", "saída", "Remessa", false, true, false],
  ["6917", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6918", "Remessa para venda fora do estabelecimento, na hipótese de rescisão do contrato", "saída", "Remessa", false, true, false],
  ["6922", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária", "saída", "Industrialização", false, true, false],
  ["6923", "Remessa para conserto, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6924", "Remessa para industrialização sob o regime de drawback", "saída", "Industrialização", false, true, false],
  ["6925", "Remessa para industrialização sob o regime de drawback, sujeita ao regime de substituição tributária", "saída", "Industrialização", false, true, false],
  ["6929", "Remessa de mercadoria para depósito fechado, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6949", "Remessa para venda fora do estabelecimento", "saída", "Remessa", false, true, false],
  ["6950", "Remessa para industrialização sob o regime de drawback", "saída", "Industrialização", false, true, false],
  ["6951", "Remessa para conserto, consignação ou demonstração", "saída", "Remessa", false, true, false],
  ["6952", "Remessa para venda fora do estabelecimento, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6953", "Remessa para conserto, consignação ou demonstração, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["6961", "Remessa para industrialização por encomenda", "saída", "Industrialização", false, true, false],
  ["6962", "Remessa para industrialização por encomenda, sujeita ao regime de substituição tributária", "saída", "Industrialização", false, true, false],
  ["6966", "Remessa para conserto, sujeita ao regime de substituição tributária", "saída", "Remessa", false, true, false],
  ["7101", "Venda de produção do estabelecimento, exportada ao exterior", "saída", "Exportação", false, false, true],
  ["7102", "Venda de mercadoria adquirida ou recebida de terceiros, exportada ao exterior", "saída", "Exportação", false, false, true],
  ["7105", "Venda de produção do estabelecimento, exportada ao exterior, com imunidade de IPI", "saída", "Exportação", false, false, true],
  ["7106", "Venda de produção do estabelecimento, exportada ao exterior, sob o regime de drawback", "saída", "Exportação", false, false, true],
  ["7107", "Venda de mercadoria adquirida ou recebida de terceiros, exportada ao exterior, sob o regime de drawback", "saída", "Exportação", false, false, true],
  ["7108", "Venda de mercadoria adquirida ou recebida de terceiros, exportada ao exterior, com imunidade de IPI", "saída", "Exportação", false, false, true],
  ["7127", "Industrialização efetuada para outra empresa, exportada ao exterior", "saída", "Industrialização", false, false, true],
  ["7500", "Transferência de produção do estabelecimento, exportada ao exterior", "saída", "Transferência", false, false, true],
  ["7501", "Exportação de mercadoria recebida com fim específico de exportação", "saída", "Exportação", false, false, true],
  ["7502", "Exportação de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação", "saída", "Exportação", false, false, true],
  ["7503", "Exportação de produção do estabelecimento, com fim específico de exportação", "saída", "Exportação", false, false, true],
  ["7504", "Exportação de mercadoria recebida com fim específico de exportação, com imunidade de IPI", "saída", "Exportação", false, false, true],
  ["7510", "Exportação de produção do estabelecimento, com imunidade de IPI", "saída", "Exportação", false, false, true],
  ["7511", "Exportação de mercadoria adquirida ou recebida de terceiros, com imunidade de IPI", "saída", "Exportação", false, false, true],
  ["7989", "Outra saída de mercadoria ou prestação de serviço não especificado nos códigos anteriores", "saída", "Outro", true, false, false],
  ["7990", "Outra saída de mercadoria ou prestação de serviço não especificado nos códigos anteriores", "saída", "Outro", false, true, false],
  ["7999", "Outra saída de mercadoria ou prestação de serviço não especificado nos códigos anteriores", "saída", "Outro", false, false, true],
];

async function migrate() {
  const client = new pg.Client({ connectionString: DIRECT_URL });
  await client.connect();

  try {
    await client.query(`ALTER TABLE products ADD COLUMN IF NOT EXISTS cfop_preferencial VARCHAR(10)`);
    console.log("OK: cfop_preferencial column added");
  } catch (e) {
    console.log("SKIP: cfop_preferencial -", e.message);
  }

  const oldCols = ["cfop_interno", "cfop_externo", "cfop_devolucao", "cfop_remessa", "cfop_bonificacao", "cfop_transferencia"];
  for (const col of oldCols) {
    try {
      await client.query(`ALTER TABLE products DROP COLUMN IF EXISTS ${col}`);
      console.log("OK: dropped", col);
    } catch (e) {
      console.log("SKIP: drop", col, "-", e.message);
    }
  }

  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS cfops (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        codigo VARCHAR(4) NOT NULL,
        descricao VARCHAR(500) NOT NULL,
        tipo VARCHAR(10) NOT NULL,
        operacao VARCHAR(80),
        dentro_estado BOOLEAN NOT NULL DEFAULT FALSE,
        interestadual BOOLEAN NOT NULL DEFAULT FALSE,
        exterior BOOLEAN NOT NULL DEFAULT FALSE,
        ativo BOOLEAN NOT NULL DEFAULT TRUE,
        observacoes VARCHAR(500),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    console.log("OK: cfops table created");
  } catch (e) {
    console.log("SKIP: cfops table -", e.message);
  }

  try {
    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS cfops_codigo_idx ON cfops (codigo)`);
    await client.query(`CREATE INDEX IF NOT EXISTS cfops_descricao_idx ON cfops USING gin (descricao gin_trgm_ops)`);
    await client.query(`CREATE INDEX IF NOT EXISTS cfops_operacao_idx ON cfops (operacao)`);
    console.log("OK: cfops indexes created");
  } catch (e) {
    try {
      await client.query(`CREATE INDEX IF NOT EXISTS cfops_descricao_idx ON cfops (descricao)`);
      console.log("OK: cfops fallback descricao index created");
    } catch (e2) {
      console.log("SKIP: cfops descricao index -", e2.message);
    }
    try {
      await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS cfops_codigo_idx ON cfops (codigo)`);
      await client.query(`CREATE INDEX IF NOT EXISTS cfops_operacao_idx ON cfops (operacao)`);
    } catch (e3) {
      console.log("SKIP: cfops indexes -", e3.message);
    }
  }

  const { rows: existing } = await client.query("SELECT COUNT(*) as cnt FROM cfops");
  if (Number(existing[0].cnt) === 0) {
    console.log("Seeding CFOPs...");
    for (const [codigo, descricao, tipo, operacao, dentroEstado, interestadual, exterior] of CFOPS) {
      await client.query(
        `INSERT INTO cfops (codigo, descricao, tipo, operacao, dentro_estado, interestadual, exterior)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (codigo) DO NOTHING`,
        [codigo, descricao, tipo, operacao, dentroEstado, interestadual, exterior]
      );
    }
    console.log(`OK: seeded ${CFOPS.length} CFOPs`);
  } else {
    console.log(`SKIP: cfops already has ${existing[0].cnt} rows, skipping seed`);
  }

  await client.end();
  console.log("Migration complete.");
}

migrate();
