import { prisma } from "../../config/prisma.js";
import { getPlanByCode } from "./subscription-plan.service.js";
import { calculateNextPeriod, calculateTrialPeriod } from "./subscription-period.service.js";
import { createSubscriptionHistory, findReplay, snapshot } from "./subscription-history.service.js";
import { SubscriptionAlreadyActiveError, SubscriptionChangeNotAllowedError, SubscriptionConfigurationError, SubscriptionConcurrentModificationError, SubscriptionInvalidStateError, SubscriptionNotFoundError } from "./subscription.errors.js";

const CURRENT_STATUSES = ["ACTIVE", "TRIALING", "PAST_DUE", "SUSPENDED"];
const usable = (status) => ["ACTIVE", "TRIALING"].includes(status);
function requiredKey(value) { if (typeof value !== "string" || !value.trim() || value.length > 160) throw new SubscriptionConfigurationError({ reason: "idempotency_key_invalid" }); return value; }
const dto = (subscription, replay=false, type=null) => ({ subscription: { id:subscription.id, companyId:subscription.companyId, status:subscription.status, billingCycle:subscription.billingCycle, provider:subscription.provider, planId:subscription.planId, planPriceId:subscription.planPriceId, trialStartedAt:subscription.trialStartedAt, trialEndsAt:subscription.trialEndsAt, currentPeriodStart:subscription.currentPeriodStart, currentPeriodEnd:subscription.currentPeriodEnd, cancelAtPeriodEnd:subscription.cancelAtPeriodEnd, canceledAt:subscription.canceledAt, endedAt:subscription.endedAt, nextPlanId:subscription.nextPlanId, nextPlanPriceId:subscription.nextPlanPriceId, nextPlanEffectiveAt:subscription.nextPlanEffectiveAt }, operation:{ type, idempotentReplay:replay } });

async function current(tx, companyId) { const subscription=await tx.subscription.findFirst({where:{companyId,status:{in:CURRENT_STATUSES}},include:{currentPlan:true,currentPrice:true}}); if(!subscription)throw new SubscriptionNotFoundError({companyId}); return subscription; }
async function companyReplay(tx,companyId,idempotencyKey,changeType,intent){const history=await tx.subscriptionHistory.findFirst({where:{companyId,idempotencyKey},include:{subscription:true}});if(!history)return null;await findReplay(tx,history.subscriptionId,idempotencyKey,changeType,intent);return dto(history.subscription,true,changeType);}
const plan = (code, cycle, db) => getPlanByCode({planCode:code,billingCycle:cycle,db});

export async function conditionalUpdate(tx, subscription, data, operation, idempotencyKey=null, intent=null) {
  const where={id:subscription.id,companyId:subscription.companyId,status:subscription.status,planId:subscription.planId,planPriceId:subscription.planPriceId,billingCycle:subscription.billingCycle,cancelAtPeriodEnd:subscription.cancelAtPeriodEnd,canceledAt:subscription.canceledAt,endedAt:subscription.endedAt,nextPlanId:subscription.nextPlanId,nextPlanPriceId:subscription.nextPlanPriceId,nextPlanEffectiveAt:subscription.nextPlanEffectiveAt};
  const result=await tx.subscription.updateMany({where,data});
  if(result.count===1)return {subscription:await tx.subscription.findUnique({where:{id:subscription.id}}),idempotentReplay:false};
  if(idempotencyKey){const replay=await findReplay(tx,subscription.id,idempotencyKey,operation,intent);if(replay)return {subscription:await tx.subscription.findUnique({where:{id:subscription.id}}),idempotentReplay:true};}
  throw new SubscriptionConcurrentModificationError({subscriptionId:subscription.id,companyId:subscription.companyId,operation,expectedState:snapshot(subscription)});
}

async function replayCreateAfterRace({db,companyId,idempotencyKey,intent,error}) { if(error?.code!=="P2002"&&error?.code!=="SUBSCRIPTION_CONCURRENT_MODIFICATION")throw error; const existing=await db.subscription.findFirst({where:{companyId,status:{in:CURRENT_STATUSES}}}); if(!existing)throw error; const replay=await findReplay(db,existing.id,idempotencyKey,intent.changeType,intent); if(replay)return dto(existing,true,replay.changeType); throw new SubscriptionAlreadyActiveError({companyId}); }

export async function createManualSubscription({companyId,planCode,billingCycle="MONTHLY",trialDays=0,actorId,requestId,idempotencyKey,reason,now=new Date(),db=prisma}) {
  requiredKey(idempotencyKey); const changeType=trialDays?"TRIAL_STARTED":"CREATED"; const intent={changeType,planCode,billingCycle,trialDays};
  try{return await db.$transaction(async tx=>{const existing=await tx.subscription.findFirst({where:{companyId,status:{in:CURRENT_STATUSES}}});if(existing){const replay=await findReplay(tx,existing.id,idempotencyKey,changeType,intent);if(replay)return dto(existing,true,changeType);throw new SubscriptionAlreadyActiveError({companyId});}const selected=await plan(planCode,billingCycle,tx);const period=trialDays?calculateTrialPeriod({now,trialDays}):calculateNextPeriod({periodStart:now,billingCycle});const subscription=await tx.subscription.create({data:{companyId,planId:selected.id,planPriceId:selected.price.id,status:trialDays?"TRIALING":"ACTIVE",billingCycle,provider:"MANUAL",...period}});await createSubscriptionHistory({tx,subscription,idempotencyKey,actorId,requestId,changeType,reason,nextState:snapshot(subscription,planCode),intent,effectiveAt:now});return dto(subscription,false,changeType);});}catch(error){return replayCreateAfterRace({db,companyId,idempotencyKey,intent,error});}
}

async function change({companyId,targetPlanCode,targetBillingCycle,actorId,requestId,idempotencyKey,reason,now=new Date(),db=prisma,mode}) {
  requiredKey(idempotencyKey); const intent={changeType:mode,targetPlanCode,targetBillingCycle};
  return db.$transaction(async tx=>{const prior=await companyReplay(tx,companyId,idempotencyKey,mode,intent);if(prior)return prior;const source=await current(tx,companyId);if(!usable(source.status))throw new SubscriptionInvalidStateError({status:source.status});const selected=await plan(targetPlanCode,targetBillingCycle,tx);if(selected.id===source.planId&&targetBillingCycle===source.billingCycle)throw new SubscriptionChangeNotAllowedError({reason:"same_plan"});const immediate=selected.displayOrder>source.currentPlan.displayOrder&&selected.id!==source.planId;if(mode==="UPGRADED"&&!immediate)throw new SubscriptionChangeNotAllowedError({reason:"not_upgrade"});if(mode==="DOWNGRADE_SCHEDULED"&&immediate)throw new SubscriptionChangeNotAllowedError({reason:"not_downgrade"});const data=immediate?{planId:selected.id,planPriceId:selected.price.id,billingCycle:targetBillingCycle,nextPlanId:null,nextPlanPriceId:null,nextPlanEffectiveAt:null}:{nextPlanId:selected.id,nextPlanPriceId:selected.price.id,nextPlanEffectiveAt:source.currentPeriodEnd};const mutation=await conditionalUpdate(tx,source,data,mode,idempotencyKey,intent);if(mutation.idempotentReplay)return dto(mutation.subscription,true,mode);await createSubscriptionHistory({tx,subscription:mutation.subscription,idempotencyKey,actorId,requestId,changeType:mode,reason,previousState:snapshot(source,source.currentPlan.code),nextState:snapshot(mutation.subscription,selected.code),intent,effectiveAt:immediate?now:source.currentPeriodEnd});return dto(mutation.subscription,false,mode);});
}
export const upgradeSubscription=(input)=>change({...input,mode:"UPGRADED"});
export const schedulePlanChange=(input)=>change({...input,mode:"DOWNGRADE_SCHEDULED"});
export async function changeSubscriptionPlan(input){const db=input.db??prisma;const previous=await db.subscriptionHistory.findFirst({where:{companyId:input.companyId,idempotencyKey:input.idempotencyKey}});if(previous?.changeType==="UPGRADED")return upgradeSubscription(input);if(previous?.changeType==="DOWNGRADE_SCHEDULED")return schedulePlanChange(input);const source=await db.subscription.findFirst({where:{companyId:input.companyId,status:{in:CURRENT_STATUSES}},include:{currentPlan:true}});if(!source)throw new SubscriptionNotFoundError({companyId:input.companyId});const selected=await plan(input.targetPlanCode,input.targetBillingCycle,db);return selected.displayOrder>source.currentPlan.displayOrder&&selected.id!==source.planId?upgradeSubscription(input):schedulePlanChange(input);}

export async function applyScheduledPlanChange({subscriptionId,actorId,requestId,idempotencyKey,now=new Date(),db=prisma}) {
  requiredKey(idempotencyKey); const intent={changeType:"DOWNGRADED",subscriptionId};
  return db.$transaction(async tx=>{const source=await tx.subscription.findUnique({where:{id:subscriptionId},include:{currentPlan:true}});if(!source)throw new SubscriptionNotFoundError({subscriptionId});const replay=await findReplay(tx,source.id,idempotencyKey,"DOWNGRADED",intent);if(replay)return dto(source,true,"DOWNGRADED");if(!source.nextPlanId||!source.nextPlanPriceId||!source.nextPlanEffectiveAt||now<source.nextPlanEffectiveAt)throw new SubscriptionInvalidStateError({subscriptionId});const price=await tx.subscriptionPlanPrice.findUnique({where:{id:source.nextPlanPriceId}});const period=calculateNextPeriod({periodStart:source.nextPlanEffectiveAt,billingCycle:price.billingCycle});const mutation=await conditionalUpdate(tx,source,{planId:source.nextPlanId,planPriceId:source.nextPlanPriceId,billingCycle:price.billingCycle,...period,nextPlanId:null,nextPlanPriceId:null,nextPlanEffectiveAt:null},"DOWNGRADED",idempotencyKey,intent);if(mutation.idempotentReplay)return dto(mutation.subscription,true,"DOWNGRADED");await createSubscriptionHistory({tx,subscription:mutation.subscription,idempotencyKey,actorId,requestId,changeType:"DOWNGRADED",previousState:snapshot(source,source.currentPlan.code),nextState:snapshot(mutation.subscription),intent,effectiveAt:source.nextPlanEffectiveAt});return dto(mutation.subscription,false,"DOWNGRADED");});
}

export async function cancelSubscription({companyId,cancelAtPeriodEnd=true,actorId,requestId,idempotencyKey,reason,now=new Date(),db=prisma}) {
  requiredKey(idempotencyKey); const intent={changeType:"CANCELED",cancelAtPeriodEnd};
  return db.$transaction(async tx=>{const prior=await companyReplay(tx,companyId,idempotencyKey,"CANCELED",intent);if(prior)return prior;const source=await current(tx,companyId);if(!usable(source.status))throw new SubscriptionInvalidStateError({status:source.status});const data=cancelAtPeriodEnd?{cancelAtPeriodEnd:true,canceledAt:now,nextPlanId:null,nextPlanPriceId:null,nextPlanEffectiveAt:null}:{status:"CANCELED",cancelAtPeriodEnd:false,canceledAt:now,endedAt:now,nextPlanId:null,nextPlanPriceId:null,nextPlanEffectiveAt:null};const mutation=await conditionalUpdate(tx,source,data,"CANCELED",idempotencyKey,intent);if(mutation.idempotentReplay)return dto(mutation.subscription,true,"CANCELED");await createSubscriptionHistory({tx,subscription:mutation.subscription,idempotencyKey,actorId,requestId,changeType:"CANCELED",reason,previousState:snapshot(source),nextState:snapshot(mutation.subscription),intent,effectiveAt:cancelAtPeriodEnd?source.currentPeriodEnd:now});return dto(mutation.subscription,false,"CANCELED");});
}

export async function reactivateSubscription({companyId,actorId,requestId,idempotencyKey,reason,now=new Date(),db=prisma}) {
  requiredKey(idempotencyKey); const intent={changeType:"REACTIVATED"};
  return db.$transaction(async tx=>{const prior=await companyReplay(tx,companyId,idempotencyKey,"REACTIVATED",intent);if(prior)return prior;const source=await current(tx,companyId);if(!usable(source.status)||!source.cancelAtPeriodEnd||now>=source.currentPeriodEnd)throw new SubscriptionInvalidStateError({status:source.status});const mutation=await conditionalUpdate(tx,source,{cancelAtPeriodEnd:false,canceledAt:null},"REACTIVATED",idempotencyKey,intent);if(mutation.idempotentReplay)return dto(mutation.subscription,true,"REACTIVATED");await createSubscriptionHistory({tx,subscription:mutation.subscription,idempotencyKey,actorId,requestId,changeType:"REACTIVATED",reason,previousState:snapshot(source),nextState:snapshot(mutation.subscription),intent,effectiveAt:now});return dto(mutation.subscription,false,"REACTIVATED");});
}
