ALTER TABLE "payables" ALTER COLUMN "nfe_entry_id" DROP NOT NULL;
ALTER TABLE "payables" ALTER COLUMN "status" SET DEFAULT 'PENDING';
ALTER TABLE "payables" ADD COLUMN "description" VARCHAR(255);
ALTER TABLE "payables" ADD COLUMN "category_id" UUID;
ALTER TABLE "payables" ADD COLUMN "cost_center_id" UUID;
ALTER TABLE "payables" ADD COLUMN "financial_account_id" UUID;
ALTER TABLE "payables" ADD COLUMN "competence_date" TIMESTAMP(3);
ALTER TABLE "payables" ADD COLUMN "issue_date" TIMESTAMP(3);
ALTER TABLE "payables" ADD COLUMN "discount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "payables" ADD COLUMN "interest" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "payables" ADD COLUMN "fine" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "payables" ADD COLUMN "paid_amount" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "payables" ADD COLUMN "total_installments" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "payables" ADD COLUMN "external_key" VARCHAR(180);
ALTER TABLE "payables" ADD COLUMN "attachment_url" TEXT;
ALTER TABLE "payables" ADD COLUMN "notes" TEXT;
ALTER TABLE "payables" ADD COLUMN "recurrence" VARCHAR(30);
UPDATE "payables" SET "status"='PENDING' WHERE "status"='OPEN';
CREATE UNIQUE INDEX "payables_company_id_external_key_installment_number_key" ON "payables"("company_id","external_key","installment_number");

CREATE TABLE "receivables" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"client_id" UUID,"client_name" TEXT,"description" TEXT NOT NULL,"category_id" UUID,"cost_center_id" UUID,"financial_account_id" UUID,"competence_date" TIMESTAMP(3),"issue_date" TIMESTAMP(3),"due_date" TIMESTAMP(3) NOT NULL,"amount" DECIMAL(15,2) NOT NULL,"discount" DECIMAL(15,2) NOT NULL DEFAULT 0,"interest" DECIMAL(15,2) NOT NULL DEFAULT 0,"fine" DECIMAL(15,2) NOT NULL DEFAULT 0,"received_amount" DECIMAL(15,2) NOT NULL DEFAULT 0,"receipt_method" TEXT,"installment_number" TEXT NOT NULL DEFAULT '1',"total_installments" INTEGER NOT NULL DEFAULT 1,"status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',"source" VARCHAR(30) NOT NULL DEFAULT 'MANUAL',"external_key" VARCHAR(180),"attachment_url" TEXT,"notes" TEXT,"recurrence" VARCHAR(30),"received_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "receivables_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "receivables_company_id_external_key_installment_number_key" ON "receivables"("company_id","external_key","installment_number");
CREATE INDEX "receivables_company_id_status_due_date_idx" ON "receivables"("company_id","status","due_date");

CREATE TABLE "financial_categories" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" TEXT NOT NULL,"type" VARCHAR(30) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "financial_categories_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "financial_categories_company_id_name_type_key" ON "financial_categories"("company_id","name","type");
CREATE INDEX "financial_categories_company_id_active_idx" ON "financial_categories"("company_id","active");
CREATE TABLE "cost_centers" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" TEXT NOT NULL,"code" VARCHAR(40) NOT NULL,"description" TEXT,"responsible" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "cost_centers_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "cost_centers_company_id_code_key" ON "cost_centers"("company_id","code");
CREATE INDEX "cost_centers_company_id_active_idx" ON "cost_centers"("company_id","active");
CREATE TABLE "financial_accounts" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"name" TEXT NOT NULL,"type" VARCHAR(30) NOT NULL,"bank" TEXT,"branch" TEXT,"masked_account" TEXT,"initial_balance" DECIMAL(15,2) NOT NULL DEFAULT 0,"initial_balance_date" TIMESTAMP(3) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "financial_accounts_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "financial_accounts_company_id_name_key" ON "financial_accounts"("company_id","name");
CREATE INDEX "financial_accounts_company_id_active_idx" ON "financial_accounts"("company_id","active");
CREATE TABLE "financial_transactions" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"financial_account_id" UUID,"payable_id" UUID,"receivable_id" UUID,"type" VARCHAR(20) NOT NULL,"amount" DECIMAL(15,2) NOT NULL,"occurred_at" TIMESTAMP(3) NOT NULL,"description" TEXT,"source" VARCHAR(30) NOT NULL,"external_key" VARCHAR(180),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "financial_transactions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "financial_transactions_company_id_external_key_key" ON "financial_transactions"("company_id","external_key");
CREATE INDEX "financial_transactions_company_id_occurred_at_idx" ON "financial_transactions"("company_id","occurred_at");
CREATE TABLE "financial_reconciliations" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"transaction_id" UUID,"external_reference" TEXT,"expected_amount" DECIMAL(15,2) NOT NULL,"actual_amount" DECIMAL(15,2),"expected_date" TIMESTAMP(3),"actual_date" TIMESTAMP(3),"status" VARCHAR(30) NOT NULL DEFAULT 'PENDING',"divergence_code" VARCHAR(50),"justification" TEXT,"evidence" JSONB,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "financial_reconciliations_pkey" PRIMARY KEY ("id"));
CREATE INDEX "financial_reconciliations_company_id_status_idx" ON "financial_reconciliations"("company_id","status");
CREATE TABLE "billings" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"receivable_id" UUID,"type" VARCHAR(30) NOT NULL,"amount" DECIMAL(15,2) NOT NULL,"due_date" TIMESTAMP(3) NOT NULL,"status" VARCHAR(30) NOT NULL DEFAULT 'CREATED',"provider_reference" TEXT,"idempotency_key" TEXT NOT NULL,"payload" JSONB,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "billings_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "billings_company_id_idempotency_key_key" ON "billings"("company_id","idempotency_key");
CREATE INDEX "billings_company_id_status_due_date_idx" ON "billings"("company_id","status","due_date");
CREATE TABLE "bank_integrations" ("id" UUID NOT NULL,"company_id" UUID NOT NULL,"provider" VARCHAR(30) NOT NULL,"status" VARCHAR(40) NOT NULL DEFAULT 'CONFIGURATION_REQUIRED',"encrypted_credentials" TEXT,"credential_fingerprint" VARCHAR(64),"last_sync_at" TIMESTAMP(3),"last_error" TEXT,"active" BOOLEAN NOT NULL DEFAULT false,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "bank_integrations_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "bank_integrations_company_id_provider_key" ON "bank_integrations"("company_id","provider");
CREATE INDEX "bank_integrations_company_id_status_idx" ON "bank_integrations"("company_id","status");

ALTER TABLE "receivables" ADD CONSTRAINT "receivables_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "financial_categories" ADD CONSTRAINT "financial_categories_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "cost_centers" ADD CONSTRAINT "cost_centers_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "financial_accounts" ADD CONSTRAINT "financial_accounts_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "financial_transactions" ADD CONSTRAINT "financial_transactions_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "financial_reconciliations" ADD CONSTRAINT "financial_reconciliations_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "billings" ADD CONSTRAINT "billings_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "bank_integrations" ADD CONSTRAINT "bank_integrations_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
