import {Router} from "express";
import {z} from "zod";
import {prisma} from "../../config/prisma.js";
import {AppError} from "../../utils/app-error.js";
import {asyncHandler,sendSuccess} from "../../utils/response.js";
import {writeAudit,writeFinancialAudit} from "../audit/audit.service.js";
import {accountSchema,allocationSchema,cancellationSchema,categorySchema,centerSchema,listSchema,moneySchema,payableSchema,receivableSchema,reversalSchema,settlementSchema} from "./financial.schemas.js";
import {balance,cashFlow,cancelEntry,createInstallments,dashboard,listEntries,reopenEntry,reverseSettlement,settle,updateEntry} from "./financial.service.js";
import {financialNotFound,viewerForbidden} from "./financial-errors.js";
import {moneyString,sumMoney} from "./money.js";
import {actOnReconciliation,classifyReconciliation} from "./reconciliation.service.js";
import {createBilling} from "./billing.service.js";
import {configureBank,safeBank} from "./bank-integration.service.js";

const router=Router({mergeParams:true});
const context=request=>request.companyContext;
const permits=(request,permission)=>{const c=context(request),permissions=c.permissions||[];return permissions.includes("*")||permissions.includes(permission)||(permission==="financial:read"&&permissions.includes("financial:write"))};
const read=request=>{if(!permits(request,"financial:read"))throw new AppError("Permissão financeira de leitura necessária.","FINANCIAL_PERMISSION_REQUIRED",403)};
const write=request=>{if(context(request).role==="VIEWER"||!permits(request,"financial:write"))throw viewerForbidden()};
const entity=async(model,request,id,client=prisma)=>{const value=await client[model].findFirst({where:{id,companyId:context(request).companyId}});if(!value)throw financialNotFound(model);return value};

router.use((request,_response,next)=>{read(request);next()});
router.get("/dashboard",asyncHandler(async(r,s)=>{const q=z.object({from:z.coerce.date(),to:z.coerce.date()}).parse(r.query);sendSuccess(s,await dashboard(context(r).companyId,q.from,q.to))}));

for(const[path,model,schema]of[["payables","payable",payableSchema],["receivables","receivable",receivableSchema]]){
  router.get(`/${path}`,asyncHandler(async(r,s)=>sendSuccess(s,await listEntries(model,context(r).companyId,listSchema.parse(r.query)))));
  router.post(`/${path}`,asyncHandler(async(r,s)=>{write(r);sendSuccess(s,{data:await createInstallments(model,context(r),schema.parse(r.body),r)},201)}));
  router.get(`/${path}/:id`,asyncHandler(async(r,s)=>{const value=await entity(model,r,r.params.id);sendSuccess(s,{...value,balance:moneyString(balance(value)),history:await prisma.financialEvent.findMany({where:{companyId:context(r).companyId,entityType:model,entityId:value.id},orderBy:{createdAt:"desc"}}),allocations:await prisma.financialAllocation.findMany({where:{companyId:context(r).companyId,[`${model}Id`]:value.id,active:true}}),attachments:await prisma.financialAttachment.findMany({where:{companyId:context(r).companyId,[`${model}Id`]:value.id,removedAt:null}})})}));
  router.patch(`/${path}/:id`,asyncHandler(async(r,s)=>{write(r);sendSuccess(s,await updateEntry(model,context(r),r.params.id,schema.partial().omit({installments:true}).parse(r.body),r))}));
  router.post(`/${path}/:id/settle`,asyncHandler(async(r,s)=>{write(r);try{sendSuccess(s,await settle(model,context(r),r.params.id,settlementSchema.parse(r.body),r))}catch(error){if(["SETTLEMENT_EXCEEDS_BALANCE","P2034"].includes(error?.code)){await prisma.$transaction(tx=>writeFinancialAudit({client:tx,request:r,action:`${model}.settlement_rejected`,companyId:context(r).companyId,entityType:model,entityId:r.params.id,justification:error.message,metadata:{code:error.code}}))}throw error}}));
  router.post(`/${path}/:id/reverse`,asyncHandler(async(r,s)=>{write(r);const body=reversalSchema.parse(r.body);sendSuccess(s,await reverseSettlement(model,context(r),r.params.id,body.reason,r))}));
  router.post(`/${path}/:id/cancel`,asyncHandler(async(r,s)=>{write(r);const body=cancellationSchema.parse(r.body);sendSuccess(s,await cancelEntry(model,context(r),r.params.id,body.reason,r))}));
  router.post(`/${path}/:id/reopen`,asyncHandler(async(r,s)=>{write(r);const body=cancellationSchema.parse(r.body);sendSuccess(s,await reopenEntry(model,context(r),r.params.id,body.reason,r))}));
  router.delete(`/${path}/:id`,asyncHandler(async()=>{throw new AppError("Exclusão física de título financeiro não é permitida; use cancelamento com justificativa.","FINANCIAL_PHYSICAL_DELETE_FORBIDDEN",409)}));
  router.put(`/${path}/:id/allocations`,asyncHandler(async(r,s)=>{write(r);const items=z.array(allocationSchema).min(1).parse(r.body?.items);const value=await prisma.$transaction(async tx=>{const title=await entity(model,r,r.params.id,tx),total=sumMoney(items.map(x=>x.amount));if(!total.equals(title.amount))throw new AppError("Rateios devem fechar exatamente 100% do valor do título.","FINANCIAL_ALLOCATION_MISMATCH",422);for(const item of items){const center=await tx.costCenter.findFirst({where:{id:item.costCenterId,companyId:context(r).companyId,active:true}});if(!center)throw new AppError("Centro de custo inválido para a empresa.","FINANCIAL_COST_CENTER_INVALID",422)}await tx.financialAllocation.updateMany({where:{companyId:context(r).companyId,[`${model}Id`]:title.id,active:true},data:{active:false}});const rows=[];for(const item of items)rows.push(await tx.financialAllocation.create({data:{companyId:context(r).companyId,[`${model}Id`]:title.id,costCenterId:item.costCenterId,amount:item.amount}}));await writeFinancialAudit({client:tx,request:r,action:`${model}.allocations_replaced`,companyId:context(r).companyId,entityType:model,entityId:title.id,afterState:rows,metadata:{total:moneyString(total)}});return rows});sendSuccess(s,{data:value})}));
  router.post(`/${path}/:id/attachments`,asyncHandler(async(r,s)=>{write(r);const body=z.object({fileName:z.string().min(1).max(255),storageKey:z.string().min(1).max(2000),contentHash:z.string().regex(/^[a-f0-9]{64}$/i)}).parse(r.body);const value=await prisma.$transaction(async tx=>{const title=await entity(model,r,r.params.id,tx),attachment=await tx.financialAttachment.create({data:{companyId:context(r).companyId,[`${model}Id`]:title.id,...body}});await writeFinancialAudit({client:tx,request:r,action:`${model}.attachment_added`,companyId:context(r).companyId,entityType:model,entityId:title.id,afterState:attachment});return attachment});sendSuccess(s,value,201)}));
  router.delete(`/${path}/:id/attachments/:attachmentId`,asyncHandler(async(r,s)=>{write(r);const reason=cancellationSchema.parse(r.body).reason,value=await prisma.$transaction(async tx=>{const title=await entity(model,r,r.params.id,tx),before=await tx.financialAttachment.findFirst({where:{id:r.params.attachmentId,companyId:context(r).companyId,[`${model}Id`]:title.id,removedAt:null}});if(!before)throw financialNotFound("attachment");const after=await tx.financialAttachment.update({where:{id:before.id},data:{removedAt:new Date(),removedBy:context(r).userId}});await writeFinancialAudit({client:tx,request:r,action:`${model}.attachment_removed`,companyId:context(r).companyId,entityType:model,entityId:title.id,beforeState:before,afterState:after,justification:reason});return after});sendSuccess(s,value)}));
}

router.get("/cash-flow",asyncHandler(async(r,s)=>{const q=z.object({from:z.coerce.date(),to:z.coerce.date(),group:z.enum(["DAILY","WEEKLY","MONTHLY"]).default("DAILY")}).parse(r.query);sendSuccess(s,await cashFlow(context(r).companyId,q.from,q.to))}));

for(const[path,model,schema]of[["categories","financialCategory",categorySchema],["cost-centers","costCenter",centerSchema],["accounts","financialAccount",accountSchema]]){
  router.get(`/${path}`,asyncHandler(async(r,s)=>sendSuccess(s,{data:await prisma[model].findMany({where:{companyId:context(r).companyId},orderBy:model==="financialAccount"?[{active:"desc"},{createdAt:"desc"}]:{createdAt:"desc"}})})));
  router.post(`/${path}`,asyncHandler(async(r,s)=>{write(r);const value=await prisma.$transaction(async tx=>{const row=await tx[model].create({data:{...schema.parse(r.body),companyId:context(r).companyId}});await writeFinancialAudit({client:tx,request:r,action:`${model}.created`,companyId:context(r).companyId,entityType:model,entityId:row.id,afterState:row});return row});sendSuccess(s,value,201)}));
  router.patch(`/${path}/:id`,asyncHandler(async(r,s)=>{write(r);const value=await prisma.$transaction(async tx=>{const before=await entity(model,r,r.params.id,tx),after=await tx[model].update({where:{id:before.id},data:schema.partial().parse(r.body)});await writeFinancialAudit({client:tx,request:r,action:`${model}.updated`,companyId:context(r).companyId,entityType:model,entityId:before.id,beforeState:before,afterState:after});return after});sendSuccess(s,value)}));
  router.delete(`/${path}/:id`,asyncHandler(async(r,s)=>{write(r);const value=await prisma.$transaction(async tx=>{const before=await entity(model,r,r.params.id,tx),after=await tx[model].update({where:{id:before.id},data:{active:false}});await writeFinancialAudit({client:tx,request:r,action:`${model}.inactivated`,companyId:context(r).companyId,entityType:model,entityId:before.id,beforeState:before,afterState:after,justification:"Inativação solicitada por usuário"});return after});sendSuccess(s,value)}));
  if(model==="financialAccount"){
    router.post(`/${path}/:id/activate`,asyncHandler(async(r,s)=>{write(r);const value=await prisma.$transaction(async tx=>{const before=await entity(model,r,r.params.id,tx),after=await tx[model].update({where:{id:before.id},data:{active:true}});await writeFinancialAudit({client:tx,request:r,action:`${model}.activated`,companyId:context(r).companyId,entityType:model,entityId:before.id,beforeState:before,afterState:after});return after});sendSuccess(s,value)}));
    router.post(`/${path}/:id/deactivate`,asyncHandler(async(r,s)=>{write(r);const value=await prisma.$transaction(async tx=>{const before=await entity(model,r,r.params.id,tx),after=await tx[model].update({where:{id:before.id},data:{active:false}});await writeFinancialAudit({client:tx,request:r,action:`${model}.deactivated`,companyId:context(r).companyId,entityType:model,entityId:before.id,beforeState:before,afterState:after});return after});sendSuccess(s,value)}));
  }
}

router.get("/events",asyncHandler(async(r,s)=>sendSuccess(s,{data:await prisma.financialEvent.findMany({where:{companyId:context(r).companyId},orderBy:{createdAt:"desc"},take:100})})));
router.get("/reconciliations",asyncHandler(async(r,s)=>sendSuccess(s,{data:await prisma.financialReconciliation.findMany({where:{companyId:context(r).companyId,...(r.query.status?{status:String(r.query.status)}:{})},orderBy:{createdAt:"desc"}})})));
router.post("/reconciliations",asyncHandler(async(r,s)=>{write(r);const b=z.object({transactionId:z.string().uuid().nullable().optional(),externalReference:z.string().optional(),expectedAmount:moneySchema,actualAmount:moneySchema.nullable().optional(),expectedDate:z.coerce.date().nullable().optional(),actualDate:z.coerce.date().nullable().optional(),evidence:z.record(z.string(),z.unknown()).optional()}).parse(r.body),c=classifyReconciliation(b.expectedAmount,b.actualAmount,b.expectedDate,b.actualDate),value=await prisma.$transaction(async tx=>{const row=await tx.financialReconciliation.create({data:{...b,companyId:context(r).companyId,status:c.status,divergenceCode:c.code}});await writeFinancialAudit({client:tx,request:r,action:"reconciliation.created",companyId:context(r).companyId,entityType:"FinancialReconciliation",entityId:row.id,afterState:row,metadata:{classification:c}});return row});sendSuccess(s,value,201)}));
router.post("/reconciliations/:id/:action",asyncHandler(async(r,s)=>{write(r);sendSuccess(s,await actOnReconciliation(context(r).companyId,r.params.id,r.params.action,r.body||{}))}));
router.get("/billings",asyncHandler(async(r,s)=>sendSuccess(s,{data:await prisma.billing.findMany({where:{companyId:context(r).companyId},orderBy:{createdAt:"desc"}})})));
router.post("/billings",asyncHandler(async(r,s)=>{write(r);const b=z.object({receivableId:z.string().uuid().nullable().optional(),type:z.enum(["PIX","BOLETO","MANUAL","PAYMENT_LINK"]),amount:z.coerce.number().positive(),dueDate:z.coerce.date(),idempotencyKey:z.string().min(8)}).parse(r.body);sendSuccess(s,await createBilling(context(r).companyId,b),201)}));
router.get("/bank-integrations",asyncHandler(async(r,s)=>sendSuccess(s,{data:(await prisma.bankIntegration.findMany({where:{companyId:context(r).companyId}})).map(safeBank)})));
router.post("/bank-integrations/:provider/configure",asyncHandler(async(r,s)=>{write(r);const credentials=z.record(z.string(),z.string().min(1)).parse(r.body?.credentials);sendSuccess(s,safeBank(await configureBank(context(r).companyId,r.params.provider.toUpperCase(),credentials)))}));

export{router as financialRouter};
