import {randomUUID} from "node:crypto";
import {prisma} from "../../config/prisma.js";
import {AppError} from "../../utils/app-error.js";
import {writeFinancialAudit} from "../audit/audit.service.js";
import {financialRepository} from "./financial.repository.js";
import {financialNotFound,invalidSettlement} from "./financial-errors.js";
import {money,moneyString,sumMoney,zero,Decimal} from "./money.js";

export const balance=x=>Decimal.max(zero(),money(x.amount).plus(x.interest||0).plus(x.fine||0).minus(x.discount||0).minus(x.paidAmount??x.receivedAmount??0));
const serializeEntry=x=>({...x,status:x.status==="PENDING"&&x.dueDate<new Date()?"OVERDUE":x.status,amount:moneyString(x.amount),discount:moneyString(x.discount),interest:moneyString(x.interest),fine:moneyString(x.fine),...(x.paidAmount!==undefined?{paidAmount:moneyString(x.paidAmount)}:{}),...(x.receivedAmount!==undefined?{receivedAmount:moneyString(x.receivedAmount)}:{}),balance:moneyString(balance(x))});

export async function listEntries(model,companyId,q){const overdue=q.status==="OVERDUE";const where={...(overdue?{status:"PENDING",dueDate:{lt:new Date()}}:q.status?{status:q.status}:{}),...(q.source?{source:q.source}:{}),...(q.q?{OR:[{description:{contains:q.q,mode:"insensitive"}},...(model==="payable"?[{supplierName:{contains:q.q,mode:"insensitive"}}]:[{clientName:{contains:q.q,mode:"insensitive"}}])]}:{})};const[data,total]=await financialRepository.list(model,companyId,where,q.page,q.pageSize);return{data:data.map(serializeEntry),pagination:{...q,total,totalPages:Math.ceil(total/q.pageSize)}}}

export async function createInstallments(model,context,body,request,{auditWriter=writeFinancialAudit}={}){const count=body.installments,total=money(body.amount),base=total.div(count).toDecimalPlaces(2,Decimal.ROUND_DOWN),externalKey=body.externalKey||`MANUAL:${randomUUID()}`;return prisma.$transaction(async tx=>{const rows=[];for(let i=1;i<=count;i++){const amount=i===count?total.minus(base.times(count-1)):base,due=new Date(body.dueDate);due.setUTCMonth(due.getUTCMonth()+i-1);const common={companyId:context.companyId,description:body.description,dueDate:due,amount,categoryId:body.categoryId,costCenterId:body.costCenterId,financialAccountId:body.financialAccountId,competenceDate:body.competenceDate,issueDate:body.issueDate,discount:body.discount,interest:body.interest,fine:body.fine,installmentNumber:String(i),totalInstallments:count,source:body.source,externalKey,attachmentUrl:body.attachmentUrl,notes:body.notes,recurrence:body.recurrence};const row=await tx[model].upsert({where:{companyId_externalKey_installmentNumber:{companyId:context.companyId,externalKey,installmentNumber:String(i)}},create:{...common,...(model==="payable"?{supplierId:body.supplierId,supplierName:body.supplierName,supplierCnpj:body.supplierCnpj,paymentMethod:body.paymentMethod}:{clientId:body.clientId,clientName:body.clientName,receiptMethod:body.receiptMethod})},update:{}});rows.push(row);await auditWriter({client:tx,request,action:`${model}.created`,companyId:context.companyId,entityType:model,entityId:row.id,afterState:row,metadata:{installment:i,totalInstallments:count},idempotencyKey:`${externalKey}:${i}`})}return rows.map(serializeEntry)})}

export async function updateEntry(model,context,id,data,request){return prisma.$transaction(async tx=>{const before=await tx[model].findFirst({where:{id,companyId:context.companyId}});if(!before)throw financialNotFound(model);const after=await tx[model].update({where:{id},data});await writeFinancialAudit({client:tx,request,action:`${model}.updated`,companyId:context.companyId,entityType:model,entityId:id,beforeState:before,afterState:after});return serializeEntry(after)})}

export async function cancelEntry(model,context,id,reason,request){return prisma.$transaction(async tx=>{const before=await tx[model].findFirst({where:{id,companyId:context.companyId}});if(!before)throw financialNotFound(model);if(balance(before).lessThan(money(before.amount).plus(before.interest||0).plus(before.fine||0).minus(before.discount||0)))throw invalidSettlement("Título liquidado ou parcialmente liquidado exige reversão antes do cancelamento.");const after=await tx[model].update({where:{id},data:{status:"CANCELED",canceledAt:new Date(),canceledBy:context.userId,cancellationReason:reason}});await writeFinancialAudit({client:tx,request,action:`${model}.canceled`,companyId:context.companyId,entityType:model,entityId:id,beforeState:before,afterState:after,justification:reason});return serializeEntry(after)})}

export async function reopenEntry(model,context,id,reason,request){return prisma.$transaction(async tx=>{const before=await tx[model].findFirst({where:{id,companyId:context.companyId}});if(!before)throw financialNotFound(model);if(before.status!=="CANCELED")throw new AppError("Apenas contas canceladas podem ser reabertas.","FINANCIAL_REOPEN_INVALID_STATE",422);const settledField=model==="payable"?"paidAmount":"receivedAmount";if(money(before[settledField]).greaterThan(0))throw new AppError("Conteúdo liquidado exige estorno prévio à reabertura.","FINANCIAL_REOPEN_PENDING_SETTLEMENT",422);const due=new Date(before.dueDate),isOverdue=due<new Date(),after=await tx[model].update({where:{id},data:{status:isOverdue?"OVERDUE":"PENDING",canceledAt:null,canceledBy:null,cancellationReason:null}});await writeFinancialAudit({client:tx,request,action:`${model}.reopened`,companyId:context.companyId,entityType:model,entityId:id,beforeState:before,afterState:after,justification:reason,metadata:{previousStatus:before.status,dueDate:before.dueDate}});return serializeEntry(after)})}

export async function settle(model,context,id,body,request){const field=model==="payable"?"paidAmount":"receivedAmount";for(let attempt=0;attempt<3;attempt++){try{return await prisma.$transaction(async tx=>{const before=await tx[model].findFirst({where:{id,companyId:context.companyId}});if(!before)throw financialNotFound(model);const remaining=balance(before),amount=money(body.amount);if(amount.greaterThan(remaining))throw invalidSettlement();const done=amount.equals(remaining),status=model==="payable"?(done?"PAID":"PARTIALLY_PAID"):(done?"RECEIVED":"PARTIALLY_RECEIVED"),after=await tx[model].update({where:{id},data:{[field]:{increment:amount},status,...(done?{[model==="payable"?"paidAt":"receivedAt"]:body.date}:{}),...(model==="payable"?{paymentMethod:body.method}:{receiptMethod:body.method})}});const movement=await tx.financialTransaction.create({data:{companyId:context.companyId,financialAccountId:body.financialAccountId||before.financialAccountId,...(model==="payable"?{payableId:id}:{receivableId:id}),type:model==="payable"?"OUTFLOW":"INFLOW",amount,occurredAt:body.date,description:before.description,source:model.toUpperCase(),externalKey:`${model}:${id}:${moneyString(money(before[field]).plus(amount))}`}});await writeFinancialAudit({client:tx,request,action:`${model}.${done?"settled":"partially_settled"}`,companyId:context.companyId,entityType:model,entityId:id,beforeState:before,afterState:after,metadata:{movementId:movement.id,amount:moneyString(amount)}});return serializeEntry(after)},{isolationLevel:"Serializable"})}catch(error){if(error?.code!=="P2034"||attempt===2)throw error}}}

export async function reverseSettlement(model,context,id,reason,request){const field=model==="payable"?"paidAmount":"receivedAmount";return prisma.$transaction(async tx=>{const before=await tx[model].findFirst({where:{id,companyId:context.companyId}});if(!before)throw financialNotFound(model);const settled=money(before[field]);if(settled.isZero())throw invalidSettlement("Título não possui valor liquidado para reversão.");const after=await tx[model].update({where:{id},data:{[field]:zero(),status:before.dueDate<new Date()?"OVERDUE":"PENDING",[model==="payable"?"paidAt":"receivedAt"]:null}});const movement=await tx.financialTransaction.create({data:{companyId:context.companyId,financialAccountId:before.financialAccountId,...(model==="payable"?{payableId:id}:{receivableId:id}),type:model==="payable"?"INFLOW":"OUTFLOW",amount:settled,occurredAt:new Date(),description:`Reversão: ${before.description||id}`,source:"REVERSAL",externalKey:`reversal:${model}:${id}:${randomUUID()}`}});await writeFinancialAudit({client:tx,request,action:`${model}.reversed`,companyId:context.companyId,entityType:model,entityId:id,beforeState:before,afterState:after,justification:reason,metadata:{movementId:movement.id,amount:moneyString(settled)}});return serializeEntry(after)})}

export async function dashboard(companyId,from,to){const range={gte:from,lte:to};const[p,r,t,g,m]=await Promise.all([prisma.payable.findMany({where:{companyId,dueDate:range,status:{not:"CANCELED"}}}),prisma.receivable.findMany({where:{companyId,dueDate:range,status:{not:"CANCELED"}}}),prisma.financialTransaction.findMany({where:{companyId,occurredAt:range}}),prisma.taxGuide.count({where:{companyId,status:{in:["PENDING","ISSUED","OVERDUE"]}}}),prisma.financialReconciliation.count({where:{companyId,status:{in:["PENDING","DIVERGENT","PARTIALLY_MATCHED"]}}})]);const inflow=sumMoney(t.filter(x=>x.type==="INFLOW").map(x=>x.amount)),outflow=sumMoney(t.filter(x=>x.type==="OUTFLOW").map(x=>x.amount)),toReceive=sumMoney(r.map(balance)),toPay=sumMoney(p.map(balance)),result=inflow.minus(outflow);return{currentBalance:moneyString(result),toReceive:moneyString(toReceive),toPay:moneyString(toPay),received:moneyString(inflow),paid:moneyString(outflow),overdue:p.filter(x=>x.status==="OVERDUE").length+r.filter(x=>x.status==="OVERDUE").length,dueSoon:p.filter(x=>x.status==="PENDING").length+r.filter(x=>x.status==="PENDING").length,projectedBalance:moneyString(result.plus(toReceive).minus(toPay)),revenue:moneyString(inflow),expenses:moneyString(outflow),result:moneyString(result),delinquency:r.length?moneyString(sumMoney(r.filter(x=>x.status==="OVERDUE").map(balance)).div(sumMoney(r.map(x=>x.amount))).times(100)):"0.00",pendingTaxGuides:g,pendingMarketplaceReconciliations:m,series:t.map(x=>({date:x.occurredAt,type:x.type,amount:moneyString(x.amount),source:x.source}))}}

export async function cashFlow(companyId,from,to){const[tx,pay,rec,accounts]=await Promise.all([prisma.financialTransaction.findMany({where:{companyId,occurredAt:{gte:from,lte:to}},orderBy:{occurredAt:"asc"}}),prisma.payable.findMany({where:{companyId,dueDate:{gte:from,lte:to},status:{not:"CANCELED"}}}),prisma.receivable.findMany({where:{companyId,dueDate:{gte:from,lte:to},status:{not:"CANCELED"}}}),prisma.financialAccount.aggregate({_sum:{initialBalance:true},where:{companyId,active:true}})]);const initial=money(accounts._sum.initialBalance||0);let accumulated=initial;const movements=[...tx.map(x=>({date:x.occurredAt,kind:"ACTUAL",type:x.type,amount:money(x.amount),description:x.description})),...pay.map(x=>({date:x.dueDate,kind:"FORECAST",type:"OUTFLOW",amount:balance(x),description:x.description})),...rec.map(x=>({date:x.dueDate,kind:"FORECAST",type:"INFLOW",amount:balance(x),description:x.description}))].sort((a,b)=>a.date-b.date).map(x=>{accumulated=x.type==="INFLOW"?accumulated.plus(x.amount):accumulated.minus(x.amount);return{...x,amount:moneyString(x.amount),balance:moneyString(accumulated)}});return{initialBalance:moneyString(initial),movements,endingBalance:moneyString(accumulated)}}
