import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { prisma, disconnectDatabase } from "../../src/config/prisma.js";
import { createManualSubscription, upgradeSubscription, schedulePlanChange, applyScheduledPlanChange, cancelSubscription, reactivateSubscription } from "../../src/modules/subscription/subscription-lifecycle.service.js";
import { recordUsage, releaseUsage } from "../../src/modules/subscription/subscription-usage.service.js";

let owner;
const companyIds=[];
const key=(prefix)=>`${prefix}-${crypto.randomUUID()}`;
const now=new Date("2026-07-21T12:00:00.000Z");
async function makeCompany(){const company=await prisma.company.create({data:{ownerId:owner.id,legalName:key("Subscription Remaining"),cnpj:String(Math.floor(Math.random()*9e13+1e13)),uf:"SP",city:"Sao Paulo",environment:"homologation"}});companyIds.push(company.id);return company;}
async function create(company,planCode="PROFESSIONAL",billingCycle="MONTHLY"){return createManualSubscription({companyId:company.id,planCode,billingCycle,idempotencyKey:key("create"),now,db:prisma});}
async function histories(subscriptionId,where={}){return prisma.subscriptionHistory.findMany({where:{subscriptionId,...where}});}
async function state(subscriptionId){return prisma.subscription.findUnique({where:{id:subscriptionId},include:{currentPrice:true,nextPrice:true}});}
function fulfilled(results){return results.filter((result)=>result.status==="fulfilled");}
function rejected(results){return results.filter((result)=>result.status==="rejected");}
function assertStructured(result){assert.ok(["SUBSCRIPTION_CONCURRENT_MODIFICATION","SUBSCRIPTION_INVALID_STATE","SUBSCRIPTION_NOT_FOUND"].includes(result.reason?.code),`erro concorrente nao estruturado: ${result.reason?.code}`);}

before(async()=>{owner=await prisma.user.create({data:{name:key("Remaining User"),email:`${key("remaining")}@test.local`,passwordHash:"x"}});});
after(async()=>{for(const companyId of companyIds){const subscriptions=await prisma.subscription.findMany({where:{companyId},select:{id:true}});const subscriptionIds=subscriptions.map(({id})=>id);if(subscriptionIds.length){await prisma.subscriptionUsage.deleteMany({where:{subscriptionId:{in:subscriptionIds}}});await prisma.subscriptionUsageCounter.deleteMany({where:{subscriptionId:{in:subscriptionIds}}});await prisma.subscriptionHistory.deleteMany({where:{subscriptionId:{in:subscriptionIds}}});await prisma.subscription.deleteMany({where:{id:{in:subscriptionIds}}});}await prisma.company.delete({where:{id:companyId}});}await prisma.user.delete({where:{id:owner.id}});await disconnectDatabase();});

test("concorrencia: upgrades diferentes produzem um vencedor em cinco corridas",async()=>{for(let run=0;run<5;run+=1){const company=await makeCompany();const created=await create(company);const keyA=key("business");const keyB=key("company");const results=await Promise.allSettled([upgradeSubscription({companyId:company.id,targetPlanCode:"BUSINESS",targetBillingCycle:"MONTHLY",idempotencyKey:keyA,db:prisma}),upgradeSubscription({companyId:company.id,targetPlanCode:"COMPANY",targetBillingCycle:"MONTHLY",idempotencyKey:keyB,db:prisma})]);assert.equal(fulfilled(results).length,1);assert.equal(rejected(results).length,1);assertStructured(rejected(results)[0]);const final=await state(created.subscription.id);assert.equal(final.currentPrice.planId,final.planId);assert.equal(final.currentPrice.billingCycle,final.billingCycle);assert.equal((await histories(final.id,{changeType:"UPGRADED"})).length,1);const winnerKey=results[0].status==="fulfilled"?keyA:keyB;const loserKey=winnerKey===keyA?keyB:keyA;assert.equal((await histories(final.id,{idempotencyKey:winnerKey})).length,1);assert.equal((await histories(final.id,{idempotencyKey:loserKey})).length,0);}});

test("concorrencia: agendamentos diferentes e downgrade versus lateral nao sobrescrevem",async()=>{for(const targets of [["PROFESSIONAL","STARTER"],["PROFESSIONAL","COMPANY"]]){const company=await makeCompany();const created=await create(company,"COMPANY","MONTHLY");const keys=[key("schedule-a"),key("schedule-b")];const calls=[schedulePlanChange({companyId:company.id,targetPlanCode:targets[0],targetBillingCycle:"MONTHLY",idempotencyKey:keys[0],db:prisma}),schedulePlanChange({companyId:company.id,targetPlanCode:targets[1],targetBillingCycle:targets[1]==="COMPANY"?"ANNUAL":"MONTHLY",idempotencyKey:keys[1],db:prisma})];const results=await Promise.allSettled(calls);assert.equal(fulfilled(results).length,1);assert.equal(rejected(results).length,1);assertStructured(rejected(results)[0]);const final=await state(created.subscription.id);assert.equal(final.planId,created.subscription.planId);assert.equal(final.nextPrice.planId,final.nextPlanId);assert.equal(final.nextPlanEffectiveAt.getTime(),final.currentPeriodEnd.getTime());assert.equal((await histories(final.id,{changeType:"DOWNGRADE_SCHEDULED"})).length,1);const loser=results[0].status==="rejected"?keys[0]:keys[1];assert.equal((await histories(final.id,{idempotencyKey:loser})).length,0);}});

test("concorrencia: aplicacao agendada mesma chave faz replay e chaves diferentes aplicam uma vez",async()=>{for(const sameKey of [true,false]){const company=await makeCompany();const created=await create(company,"BUSINESS");await schedulePlanChange({companyId:company.id,targetPlanCode:"PROFESSIONAL",targetBillingCycle:"MONTHLY",idempotencyKey:key("schedule"),db:prisma});const scheduled=await state(created.subscription.id);const keys=sameKey?[key("apply"),null]:[key("apply-a"),key("apply-b")];keys[1]??=keys[0];const results=await Promise.allSettled(keys.map((idempotencyKey)=>applyScheduledPlanChange({subscriptionId:scheduled.id,idempotencyKey,now:scheduled.nextPlanEffectiveAt,db:prisma})));const applied=await state(scheduled.id);assert.equal((await histories(scheduled.id,{changeType:"DOWNGRADED"})).length,1);assert.equal(applied.currentPeriodStart.getTime(),scheduled.nextPlanEffectiveAt.getTime());assert.equal(applied.nextPlanId,null);assert.equal(applied.nextPlanPriceId,null);assert.equal(applied.nextPlanEffectiveAt,null);if(sameKey){assert.equal(fulfilled(results).length,2);assert.deepEqual(fulfilled(results).map(({value})=>value.operation.idempotentReplay).sort(),[false,true]);assert.equal((await histories(scheduled.id,{idempotencyKey:keys[0]})).length,1);}else{assert.equal(fulfilled(results).length,1);assert.equal(rejected(results).length,1);assertStructured(rejected(results)[0]);}}});

test("concorrencia: cancelamentos e rollback imediato mantem estado integral",async()=>{const same=await makeCompany();const created=await create(same);const sameKey=key("cancel-same");const sameResults=await Promise.allSettled([cancelSubscription({companyId:same.id,cancelAtPeriodEnd:false,idempotencyKey:sameKey,db:prisma}),cancelSubscription({companyId:same.id,cancelAtPeriodEnd:false,idempotencyKey:sameKey,db:prisma})]);assert.equal(fulfilled(sameResults).length,2);assert.deepEqual(fulfilled(sameResults).map(({value})=>value.operation.idempotentReplay).sort(),[false,true]);assert.equal((await histories(created.subscription.id,{idempotencyKey:sameKey})).length,1);
  const different=await makeCompany();const differentCreated=await create(different);const differentResults=await Promise.allSettled([cancelSubscription({companyId:different.id,cancelAtPeriodEnd:false,idempotencyKey:key("cancel-a"),db:prisma}),cancelSubscription({companyId:different.id,cancelAtPeriodEnd:false,idempotencyKey:key("cancel-b"),db:prisma})]);assert.equal(fulfilled(differentResults).length,1);assert.equal((await histories(differentCreated.subscription.id,{changeType:"CANCELED"})).length,1);const final=await state(differentCreated.subscription.id);assert.equal(final.status,"CANCELED");assert.equal(final.cancelAtPeriodEnd,false);assert.ok(final.endedAt);
  const mixed=await makeCompany();const mixedCreated=await create(mixed);const mixedResults=await Promise.allSettled([cancelSubscription({companyId:mixed.id,cancelAtPeriodEnd:true,idempotencyKey:key("scheduled"),db:prisma}),cancelSubscription({companyId:mixed.id,cancelAtPeriodEnd:false,idempotencyKey:key("immediate"),db:prisma})]);assert.equal(fulfilled(mixedResults).length,1);const mixedFinal=await state(mixedCreated.subscription.id);assert.equal(mixedFinal.status==="CANCELED"&&mixedFinal.cancelAtPeriodEnd,false);assert.equal((await histories(mixedFinal.id,{changeType:"CANCELED"})).length,1);
  const rollback=await makeCompany();const rollbackCreated=await create(rollback);const before=await state(rollbackCreated.subscription.id);const rollbackKey=key("cancel-rollback");await assert.rejects(()=>cancelSubscription({companyId:rollback.id,cancelAtPeriodEnd:false,idempotencyKey:rollbackKey,actorId:crypto.randomUUID(),db:prisma}));const afterState=await state(before.id);for(const field of ["status","planId","planPriceId","billingCycle","cancelAtPeriodEnd","canceledAt","endedAt"])assert.deepEqual(afterState[field],before[field]);assert.equal((await histories(before.id,{idempotencyKey:rollbackKey})).length,0);});

test("concorrencia: reativacoes fazem replay, rejeitam segunda mutacao e nao criam estado impossivel",async()=>{for(const sameKey of [true,false]){const company=await makeCompany();const created=await create(company);await cancelSubscription({companyId:company.id,cancelAtPeriodEnd:true,idempotencyKey:key("prepare-cancel"),db:prisma});const keys=sameKey?[key("reactivate"),null]:[key("reactivate-a"),key("reactivate-b")];keys[1]??=keys[0];const results=await Promise.allSettled(keys.map((idempotencyKey)=>reactivateSubscription({companyId:company.id,idempotencyKey,db:prisma})));const final=await state(created.subscription.id);assert.equal(final.cancelAtPeriodEnd,false);assert.equal(final.canceledAt,null);assert.equal((await histories(final.id,{changeType:"REACTIVATED"})).length,1);if(sameKey){assert.equal(fulfilled(results).length,2);assert.deepEqual(fulfilled(results).map(({value})=>value.operation.idempotentReplay).sort(),[false,true]);}else assert.equal(fulfilled(results).length,1);}
  const company=await makeCompany();const created=await create(company);await cancelSubscription({companyId:company.id,cancelAtPeriodEnd:true,idempotencyKey:key("prepare"),db:prisma});const results=await Promise.allSettled([reactivateSubscription({companyId:company.id,idempotencyKey:key("reactivate"),db:prisma}),cancelSubscription({companyId:company.id,cancelAtPeriodEnd:false,idempotencyKey:key("immediate"),db:prisma})]);assert.equal(fulfilled(results).length,1);const final=await state(created.subscription.id);assert.equal(final.status==="CANCELED"&&final.cancelAtPeriodEnd,false);assert.equal((await histories(final.id,{changeType:{in:["REACTIVATED","CANCELED"]}})).length,2);});

test("concorrencia e rollback de usage preservam soma exata do ledger",async()=>{const company=await makeCompany();const created=await create(company);const subscriptionId=created.subscription.id;const sameKey=key("usage-same");const sameResults=await Promise.allSettled([recordUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:3,sourceType:"DOC",sourceId:"same",idempotencyKey:sameKey,db:prisma}),recordUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:3,sourceType:"DOC",sourceId:"same",idempotencyKey:sameKey,db:prisma})]);assert.equal(fulfilled(sameResults).length,2);assert.deepEqual(fulfilled(sameResults).map(({value})=>value.idempotentReplay).sort(),[false,true]);assert.equal(await prisma.subscriptionUsage.count({where:{subscriptionId,idempotencyKey:sameKey}}),1);
  await Promise.all([recordUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:2,sourceType:"DOC",sourceId:"a",idempotencyKey:key("usage-a"),db:prisma}),recordUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:4,sourceType:"DOC",sourceId:"b",idempotencyKey:key("usage-b"),db:prisma})]);await Promise.allSettled([releaseUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:5,idempotencyKey:key("release-a"),db:prisma}),releaseUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:5,idempotencyKey:key("release-b"),db:prisma})]);const ledger=await prisma.subscriptionUsage.findMany({where:{subscriptionId,usageCode:"NFE"}});const counter=await prisma.subscriptionUsageCounter.findFirst({where:{subscriptionId,usageCode:"NFE"}});assert.equal(counter.quantity,ledger.reduce((sum,event)=>sum+event.quantity,0));assert.ok(counter.quantity>=0);
  const beforeCount=await prisma.subscriptionUsageCounter.count({where:{subscriptionId,usageCode:"BROKEN"}});const circular={};circular.self=circular;await assert.rejects(()=>recordUsage({subscriptionId,companyId:company.id,usageCode:"BROKEN",quantity:1,idempotencyKey:key("ledger-fail"),metadata:circular,db:prisma}));assert.equal(await prisma.subscriptionUsageCounter.count({where:{subscriptionId,usageCode:"BROKEN"}}),beforeCount);
  const subscription=await state(subscriptionId);const overflow=await prisma.subscriptionUsageCounter.create({data:{subscriptionId,companyId:company.id,usageCode:"OVERFLOW",periodStart:subscription.currentPeriodStart,periodEnd:subscription.currentPeriodEnd,quantity:2147483647}});const overflowKey=key("counter-fail");await assert.rejects(()=>recordUsage({subscriptionId,companyId:company.id,usageCode:"OVERFLOW",quantity:1,idempotencyKey:overflowKey,db:prisma}));assert.equal(await prisma.subscriptionUsage.count({where:{idempotencyKey:overflowKey}}),0);assert.equal((await prisma.subscriptionUsageCounter.findUnique({where:{id:overflow.id}})).quantity,2147483647);
  const beforeNegative=counter.quantity;const negativeKey=key("negative");await assert.rejects(()=>releaseUsage({subscriptionId,companyId:company.id,usageCode:"NFE",quantity:beforeNegative+1,idempotencyKey:negativeKey,db:prisma}),{code:"SUBSCRIPTION_USAGE_CONFLICT"});assert.equal(await prisma.subscriptionUsage.count({where:{idempotencyKey:negativeKey}}),0);assert.equal((await prisma.subscriptionUsageCounter.findUnique({where:{id:counter.id}})).quantity,beforeNegative);});

test("idempotencia: mesma chave com intencoes diferentes gera conflito sem segunda mutacao",async()=>{const company=await makeCompany();const created=await create(company);const shared=key("intent");await upgradeSubscription({companyId:company.id,targetPlanCode:"BUSINESS",targetBillingCycle:"MONTHLY",idempotencyKey:shared,db:prisma});const first=await state(created.subscription.id);await assert.rejects(()=>cancelSubscription({companyId:company.id,cancelAtPeriodEnd:false,idempotencyKey:shared,db:prisma}),{code:"SUBSCRIPTION_IDEMPOTENCY_CONFLICT"});await assert.rejects(()=>upgradeSubscription({companyId:company.id,targetPlanCode:"COMPANY",targetBillingCycle:"MONTHLY",idempotencyKey:shared,db:prisma}),{code:"SUBSCRIPTION_IDEMPOTENCY_CONFLICT"});assert.equal((await histories(first.id,{idempotencyKey:shared})).length,1);assert.equal((await state(first.id)).planId,first.planId);
  const cancelCompany=await makeCompany();const cancelCreated=await create(cancelCompany);const cancelKey=key("cancel-intent");await cancelSubscription({companyId:cancelCompany.id,cancelAtPeriodEnd:true,idempotencyKey:cancelKey,db:prisma});await assert.rejects(()=>cancelSubscription({companyId:cancelCompany.id,cancelAtPeriodEnd:false,idempotencyKey:cancelKey,db:prisma}),{code:"SUBSCRIPTION_IDEMPOTENCY_CONFLICT"});assert.equal((await histories(cancelCreated.subscription.id,{idempotencyKey:cancelKey})).length,1);
  const scheduleCompany=await makeCompany();const scheduleCreated=await create(scheduleCompany,"BUSINESS");const scheduleKey=key("schedule-intent");await schedulePlanChange({companyId:scheduleCompany.id,targetPlanCode:"PROFESSIONAL",targetBillingCycle:"MONTHLY",idempotencyKey:scheduleKey,db:prisma});await assert.rejects(()=>schedulePlanChange({companyId:scheduleCompany.id,targetPlanCode:"STARTER",targetBillingCycle:"MONTHLY",idempotencyKey:scheduleKey,db:prisma}),{code:"SUBSCRIPTION_IDEMPOTENCY_CONFLICT"});assert.equal((await histories(scheduleCreated.subscription.id,{idempotencyKey:scheduleKey})).length,1);const scheduled=await state(scheduleCreated.subscription.id);const applyKey=key("apply-intent");await applyScheduledPlanChange({subscriptionId:scheduled.id,idempotencyKey:applyKey,now:scheduled.nextPlanEffectiveAt,db:prisma});await assert.rejects(()=>cancelSubscription({companyId:scheduleCompany.id,cancelAtPeriodEnd:true,idempotencyKey:applyKey,db:prisma}),{code:"SUBSCRIPTION_IDEMPOTENCY_CONFLICT"});assert.equal((await histories(scheduled.id,{idempotencyKey:applyKey})).length,1);});
