import assert from "node:assert/strict";
import test,{after,before} from "node:test";
import {prisma,disconnectDatabase} from "../../src/config/prisma.js";
import {createManualSubscription,schedulePlanChange,cancelSubscription} from "../../src/modules/subscription/subscription-lifecycle.service.js";
import {reconcileSubscription} from "../../src/modules/subscription/subscription-reconciliation.service.js";
let owner;const companies=[];const fixed=new Date("2026-01-31T10:00:00Z");const k=()=>crypto.randomUUID();
async function company(){const item=await prisma.company.create({data:{ownerId:owner.id,legalName:`Reconcile ${k()}`,cnpj:String(Math.floor(Math.random()*9e13+1e13)),uf:"SP",city:"Sao Paulo",environment:"homologation"}});companies.push(item.id);return item;}
async function create(item,options={}){return createManualSubscription({companyId:item.id,planCode:options.planCode??"PROFESSIONAL",billingCycle:"MONTHLY",trialDays:options.trialDays??0,idempotencyKey:k(),now:fixed,db:prisma});}
before(async()=>{owner=await prisma.user.create({data:{name:"Reconcile",email:`${k()}@test.local`,passwordHash:"x"}});});
after(async()=>{for(const companyId of companies){const rows=await prisma.subscription.findMany({where:{companyId},select:{id:true}});const ids=rows.map(x=>x.id);await prisma.subscriptionHistory.deleteMany({where:{subscriptionId:{in:ids}}});await prisma.subscription.deleteMany({where:{id:{in:ids}}});await prisma.company.delete({where:{id:companyId}});}await prisma.user.delete({where:{id:owner.id}});await disconnectDatabase();});
test("reconciliation: cancelamento vencido precede mudanca agendada",async()=>{const c=await company();const created=await create(c,{planCode:"BUSINESS"});await schedulePlanChange({companyId:c.id,targetPlanCode:"PROFESSIONAL",targetBillingCycle:"MONTHLY",idempotencyKey:k(),db:prisma});await cancelSubscription({companyId:c.id,cancelAtPeriodEnd:true,idempotencyKey:k(),now:fixed,db:prisma});const at=new Date("2026-03-01T10:00:00Z");await reconcileSubscription({companyId:c.id,now:at,db:prisma});const final=await prisma.subscription.findUnique({where:{id:created.subscription.id}});assert.equal(final.status,"CANCELED");assert.equal(final.planId,created.subscription.planId);assert.equal(final.nextPlanId,null);});
test("reconciliation: trial vencido expira sem cobranca",async()=>{const c=await company();const created=await create(c,{trialDays:14});const result=await reconcileSubscription({companyId:c.id,now:new Date("2026-02-20T10:00:00Z"),db:prisma});assert.deepEqual(result.actions,["TRIAL_EXPIRED"]);const final=await prisma.subscription.findUnique({where:{id:created.subscription.id}});assert.equal(final.status,"EXPIRED");assert.equal(final.provider,"MANUAL");assert.equal(await prisma.billingProviderEvent.count({where:{subscriptionId:final.id}}),0);});
test("reconciliation: aplica agendamento vencido uma vez",async()=>{const c=await company();const created=await create(c,{planCode:"BUSINESS"});await schedulePlanChange({companyId:c.id,targetPlanCode:"PROFESSIONAL",targetBillingCycle:"MONTHLY",idempotencyKey:k(),db:prisma});const source=await prisma.subscription.findUnique({where:{id:created.subscription.id}});await reconcileSubscription({companyId:c.id,now:source.nextPlanEffectiveAt,db:prisma});await reconcileSubscription({companyId:c.id,now:source.nextPlanEffectiveAt,db:prisma});assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:source.id,changeType:"DOWNGRADED"}}),1);});
test("reconciliation: renovacao MANUAL usa calendario civil",async()=>{const c=await company();const created=await create(c);await reconcileSubscription({companyId:c.id,now:new Date("2026-04-01T10:00:00Z"),db:prisma});const final=await prisma.subscription.findUnique({where:{id:created.subscription.id}});assert.equal(final.currentPeriodStart.toISOString(),"2026-03-28T10:00:00.000Z");assert.equal(final.currentPeriodEnd.toISOString(),"2026-04-28T10:00:00.000Z");assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:final.id,changeType:"RENEWED"}}),1);});
