import assert from "node:assert/strict";
import test, { after, before } from "node:test";
import { prisma, disconnectDatabase } from "../../src/config/prisma.js";
import { createManualSubscription, upgradeSubscription, schedulePlanChange, applyScheduledPlanChange, cancelSubscription, reactivateSubscription } from "../../src/modules/subscription/subscription-lifecycle.service.js";
import { recordUsage, releaseUsage } from "../../src/modules/subscription/subscription-usage.service.js";

const ids = []; let owner; let plans;
const unique = (value) => `${value}-${crypto.randomUUID().slice(0, 8)}`;
async function company() { const c = await prisma.company.create({ data:{ ownerId:owner.id, legalName:unique("Subscription Test"), cnpj:String(Math.floor(Math.random()*9e13+1e13)), uf:"SP", city:"Sao Paulo", environment:"homologation" } }); ids.push(c.id); return c; }
async function sub(c, planCode="PROFESSIONAL", cycle="MONTHLY", key=unique("create"), trialDays=0) { return createManualSubscription({companyId:c.id,planCode,billingCycle:cycle,idempotencyKey:key,trialDays,db:prisma,now:new Date("2026-07-21T12:00:00Z")}); }
before(async () => { owner=await prisma.user.create({data:{name:unique("Sub User"),email:`${unique("subscription")}@test.local`,passwordHash:"x"}}); plans=await prisma.subscriptionPlan.findMany({orderBy:{displayOrder:"asc"}}); assert.ok(plans.length >= 2, "catalogo de planos deve estar seedado"); });
after(async () => { for (const companyId of ids) { const subscriptions=await prisma.subscription.findMany({where:{companyId},select:{id:true}}); const subscriptionIds=subscriptions.map((item)=>item.id); if(subscriptionIds.length){await prisma.subscriptionUsage.deleteMany({where:{subscriptionId:{in:subscriptionIds}}}); await prisma.subscriptionUsageCounter.deleteMany({where:{subscriptionId:{in:subscriptionIds}}}); await prisma.subscriptionHistory.deleteMany({where:{subscriptionId:{in:subscriptionIds}}}); await prisma.subscription.deleteMany({where:{id:{in:subscriptionIds}}});} await prisma.company.delete({where:{id:companyId}}); } await prisma.user.delete({where:{id:owner.id}}); await disconnectDatabase(); });

test("PostgreSQL: criacao ACTIVE/TRIALING, replay e segunda assinatura bloqueada", async () => { const c=await company(); const created=await sub(c); assert.equal(created.subscription.status,"ACTIVE"); const replay=await sub(c,"PROFESSIONAL","MONTHLY",created.operation.type ? "ignored" : "x").catch(e=>e); assert.equal(replay.code,"SUBSCRIPTION_ALREADY_ACTIVE"); const c2=await company(); const key=unique("same"); const first=await sub(c2,"PROFESSIONAL","MONTHLY",key,14); const again=await sub(c2,"PROFESSIONAL","MONTHLY",key,14); assert.equal(first.subscription.status,"TRIALING"); assert.equal(again.operation.idempotentReplay,true); });

test("PostgreSQL: upgrade, downgrade, aplicacao e replay", async () => { const c=await company(); const created=await sub(c,"PROFESSIONAL"); const upgradeTarget=plans.find(p=>p.displayOrder>plans.find(x=>x.id===created.subscription.planId).displayOrder); const upgraded=await upgradeSubscription({companyId:c.id,targetPlanCode:upgradeTarget.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("upgrade"),db:prisma}); assert.equal(upgraded.subscription.planId,upgradeTarget.id); const downgrade=plans.find(p=>p.displayOrder<upgradeTarget.displayOrder); const scheduled=await schedulePlanChange({companyId:c.id,targetPlanCode:downgrade.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("down"),db:prisma}); assert.equal(scheduled.subscription.nextPlanId,downgrade.id); await assert.rejects(()=>applyScheduledPlanChange({subscriptionId:scheduled.subscription.id,idempotencyKey:unique("early"),now:new Date(),db:prisma})); const applied=await applyScheduledPlanChange({subscriptionId:scheduled.subscription.id,idempotencyKey:unique("apply"),now:scheduled.subscription.nextPlanEffectiveAt,db:prisma}); assert.equal(applied.subscription.planId,downgrade.id); });

test("PostgreSQL: cancelamento, reativacao, usage e rollback por actor invalido", async () => { const c=await company(); const created=await sub(c); const scheduled=await cancelSubscription({companyId:c.id,cancelAtPeriodEnd:true,idempotencyKey:unique("cancel"),db:prisma}); assert.equal(scheduled.subscription.cancelAtPeriodEnd,true); const active=await reactivateSubscription({companyId:c.id,idempotencyKey:unique("reactivate"),db:prisma}); assert.equal(active.subscription.cancelAtPeriodEnd,false); const usage=await recordUsage({subscriptionId:created.subscription.id,companyId:c.id,usageCode:"NFE",quantity:2,idempotencyKey:unique("usage"),db:prisma}); const replay=await recordUsage({subscriptionId:created.subscription.id,companyId:c.id,usageCode:"NFE",quantity:2,idempotencyKey:usage.idempotencyKey,db:prisma}); assert.equal(replay.idempotentReplay,true); await releaseUsage({subscriptionId:created.subscription.id,companyId:c.id,usageCode:"NFE",quantity:1,idempotencyKey:unique("release"),db:prisma}); await assert.rejects(()=>recordUsage({subscriptionId:created.subscription.id,companyId:c.id,usageCode:"NFE",quantity:-1,idempotencyKey:unique("bad"),db:prisma}),{code:"SUBSCRIPTION_CONFIGURATION_ERROR"}); const beforeSub=await prisma.subscription.findUnique({where:{id:created.subscription.id}}); const target=plans.find(p=>p.displayOrder>plans.find(x=>x.id===beforeSub.planId).displayOrder); await assert.rejects(()=>upgradeSubscription({companyId:c.id,targetPlanCode:target.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("rollback"),actorId:crypto.randomUUID(),db:prisma})); const afterSub=await prisma.subscription.findUnique({where:{id:created.subscription.id}}); assert.equal(afterSub.planId,beforeSub.planId); });

test("PostgreSQL: concorrencia de criacao mesma chave e upgrade versus cancelamento", async () => { const c=await company(); const idempotencyKey=unique("parallel"); const results=await Promise.allSettled([sub(c,"PROFESSIONAL","MONTHLY",idempotencyKey),sub(c,"PROFESSIONAL","MONTHLY",idempotencyKey)]); assert.equal(results.filter(r=>r.status==="fulfilled").length,2); assert.deepEqual(results.map(({value})=>value.operation.idempotentReplay).sort(),[false,true]); const subscription=await prisma.subscription.findFirst({where:{companyId:c.id}}); assert.ok(subscription); assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:subscription.id,idempotencyKey}}),1); const target=plans.find(p=>p.displayOrder>plans.find(x=>x.id===subscription.planId).displayOrder); const race=await Promise.allSettled([upgradeSubscription({companyId:c.id,targetPlanCode:target.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("up"),db:prisma}),cancelSubscription({companyId:c.id,cancelAtPeriodEnd:false,idempotencyKey:unique("stop"),db:prisma})]); assert.equal(race.filter(r=>r.status==="fulfilled").length,1); assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:subscription.id}}),2); });

test("PostgreSQL: upgrade versus cancelamento permanece consistente em cinco execucoes", async () => { for(let index=0; index<5; index+=1){ const c=await company(); const created=await sub(c); const target=plans.find(p=>p.displayOrder>plans.find(x=>x.id===created.subscription.planId).displayOrder); const settled=await Promise.allSettled([upgradeSubscription({companyId:c.id,targetPlanCode:target.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("upgrade-race"),db:prisma}),cancelSubscription({companyId:c.id,cancelAtPeriodEnd:false,idempotencyKey:unique("cancel-race"),db:prisma})]); assert.equal(settled.filter((result)=>result.status==="fulfilled").length,1); const finalState=await prisma.subscription.findUnique({where:{id:created.subscription.id}}); assert.ok(["ACTIVE","CANCELED"].includes(finalState.status)); assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:created.subscription.id}}),2); } });

test("PostgreSQL: rollback de create ACTIVE e TRIALING nao deixa assinatura", async () => { for(const trialDays of [0,14]){ const c=await company(); await assert.rejects(()=>createManualSubscription({companyId:c.id,planCode:"PROFESSIONAL",billingCycle:"MONTHLY",trialDays,idempotencyKey:unique("create-rollback"),actorId:crypto.randomUUID(),db:prisma})); assert.equal(await prisma.subscription.count({where:{companyId:c.id}}),0); assert.equal(await prisma.subscriptionHistory.count({where:{companyId:c.id}}),0); assert.equal((await sub(c,"PROFESSIONAL","MONTHLY",unique("retry"),trialDays)).subscription.status,trialDays?"TRIALING":"ACTIVE"); } });

test("PostgreSQL: rollback de schedule, apply, cancel e reativacao preserva snapshot", async () => { const c=await company(); const created=await sub(c,"BUSINESS"); const original=await prisma.subscription.findUnique({where:{id:created.subscription.id}}); const lower=plans.find(p=>p.displayOrder<plans.find(x=>x.id===original.planId).displayOrder); await assert.rejects(()=>schedulePlanChange({companyId:c.id,targetPlanCode:lower.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("schedule-rollback"),actorId:crypto.randomUUID(),db:prisma})); assert.deepEqual(await prisma.subscription.findUnique({where:{id:original.id}}),original); await schedulePlanChange({companyId:c.id,targetPlanCode:lower.code,targetBillingCycle:"MONTHLY",idempotencyKey:unique("schedule"),db:prisma}); const scheduled=await prisma.subscription.findUnique({where:{id:original.id}}); await assert.rejects(()=>applyScheduledPlanChange({subscriptionId:original.id,idempotencyKey:unique("apply-rollback"),actorId:crypto.randomUUID(),now:scheduled.nextPlanEffectiveAt,db:prisma})); assert.deepEqual(await prisma.subscription.findUnique({where:{id:original.id}}),scheduled); await assert.rejects(()=>cancelSubscription({companyId:c.id,cancelAtPeriodEnd:true,idempotencyKey:unique("cancel-rollback"),actorId:crypto.randomUUID(),db:prisma})); assert.deepEqual(await prisma.subscription.findUnique({where:{id:original.id}}),scheduled); const canceled=await cancelSubscription({companyId:c.id,cancelAtPeriodEnd:true,idempotencyKey:unique("cancel"),db:prisma}); const beforeReactivate=await prisma.subscription.findUnique({where:{id:original.id}}); await assert.rejects(()=>reactivateSubscription({companyId:c.id,idempotencyKey:unique("reactivate-rollback"),actorId:crypto.randomUUID(),db:prisma})); assert.deepEqual(await prisma.subscription.findUnique({where:{id:original.id}}),beforeReactivate.subscription??beforeReactivate); assert.equal(await prisma.subscriptionHistory.count({where:{subscriptionId:original.id,changeType:"REACTIVATED"}}),0); assert.equal(canceled.subscription.cancelAtPeriodEnd,true); });
