ALTER TABLE "clients"
ADD COLUMN "whatsapp" VARCHAR(20),
ADD COLUMN "site" VARCHAR(255),
ADD COLUMN "contato_financeiro" VARCHAR(255),
ADD COLUMN "contato_fiscal" VARCHAR(255),
ADD COLUMN "porte" VARCHAR(60),
ADD COLUMN "capital_social" VARCHAR(40),
ADD COLUMN "data_abertura" TIMESTAMP(6),
ADD COLUMN "situacao_motivo" VARCHAR(200),
ADD COLUMN "optante_simples" BOOLEAN,
ADD COLUMN "mei" BOOLEAN,
ADD COLUMN "empresa_publica" BOOLEAN,
ADD COLUMN "filial" BOOLEAN,
ADD COLUMN "matriz" BOOLEAN,
ADD COLUMN "crt" VARCHAR(2),
ADD COLUMN "indicador_ie" VARCHAR(2),
ADD COLUMN "ie_status" VARCHAR(40),
ADD COLUMN "im_status" VARCHAR(40),
ADD COLUMN "tipo_contribuinte" VARCHAR(60),
ADD COLUMN "contribuinte_icms" BOOLEAN,
ADD COLUMN "contribuinte_iss" BOOLEAN,
ADD COLUMN "substituicao_tributaria" BOOLEAN,
ADD COLUMN "retencoes" JSONB,
ADD COLUMN "cnae_secundarios" JSONB,
ADD COLUMN "risco_fiscal_cnae" VARCHAR(20),
ADD COLUMN "atividades_permitidas" JSONB,
ADD COLUMN "atividades_incompativeis" JSONB,
ADD COLUMN "pais" VARCHAR(80),
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "fiscal_ai" JSONB,
ADD COLUMN "score_cadastro" SMALLINT,
ADD COLUMN "score_detalhes" JSONB,
ADD COLUMN "reforma_prep" JSONB,
ADD COLUMN "historico_json" JSONB,
ADD COLUMN "ultima_consulta" TIMESTAMP(6);
