-- Keep a clean database created from migrations compatible with Product in schema.prisma.
ALTER TABLE "products"
  ADD COLUMN "barcode" VARCHAR(20),
  ADD COLUMN "brand" VARCHAR(160),
  ADD COLUMN "weight" DECIMAL(10,4),
  ADD COLUMN "length" DECIMAL(10,4),
  ADD COLUMN "width" DECIMAL(10,4),
  ADD COLUMN "height" DECIMAL(10,4),
  ADD COLUMN "ncm_description" VARCHAR(500),
  ADD COLUMN "ex_tipi" VARCHAR(10),
  ADD COLUMN "origem_mercadoria" SMALLINT,
  ADD COLUMN "anp" VARCHAR(20),
  ADD COLUMN "tipo_item" SMALLINT,
  ADD COLUMN "grupo_tributario" VARCHAR(80),
  ADD COLUMN "cst_csosn_padrao" VARCHAR(10),
  ADD COLUMN "cfop_preferencial" VARCHAR(10),
  ADD COLUMN "icms_padrao" DECIMAL(5,2),
  ADD COLUMN "icms_st_padrao" DECIMAL(5,2),
  ADD COLUMN "mva_padrao" DECIMAL(5,2),
  ADD COLUMN "ipi_padrao" DECIMAL(5,2),
  ADD COLUMN "pis_padrao" DECIMAL(5,2),
  ADD COLUMN "cofins_padrao" DECIMAL(5,2),
  ADD COLUMN "iss_padrao" DECIMAL(5,2),
  ADD COLUMN "beneficio_fiscal_cod" VARCHAR(30),
  ADD COLUMN "beneficio_red_base" DECIMAL(5,2),
  ADD COLUMN "beneficio_diferimento" BOOLEAN DEFAULT false,
  ADD COLUMN "beneficio_isencao" BOOLEAN DEFAULT false,
  ADD COLUMN "obs_fiscal" VARCHAR(500),
  ADD COLUMN "cost_price" DECIMAL(15,2),
  ADD COLUMN "stock_min" INTEGER,
  ADD COLUMN "stock_max" INTEGER,
  ADD COLUMN "fiscal_ai" JSONB,
  ADD COLUMN "score_produto" INTEGER,
  ADD COLUMN "historico_json" JSONB;

CREATE INDEX "products_company_id_ncm_idx" ON "products"("company_id", "ncm");
