import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../config/prisma.js";
import { buildFiscalBookPreparation, getFiscalBookPreparation, listFiscalBookPreparations } from "../../services/fiscal-book-preparation.service.js";
import { generateFiscalExport, getFiscalExport, listFiscalExports, validateFiscalExport } from "../../services/fiscal-export.service.js";
import { AppError } from "../../utils/app-error.js";
import { asyncHandler, sendSuccess } from "../../utils/response.js";
import { writeAudit } from "../audit/audit.service.js";

const router = Router({ mergeParams: true });
const uuid = z.string().uuid();
const statuses = z.enum(["PENDING", "ISSUED", "PAID", "OVERDUE", "CANCELED"]);
const guide = z.object({ taxType:z.enum(["DAS","DARF","GNRE","DARE","GARE","ISS","ICMS","PIS","COFINS"]),reference:z.string().trim().min(4).max(20),dueDate:z.coerce.date(),amount:z.coerce.number().nonnegative(),closingId:z.string().uuid().nullable().optional(),digitLine:z.string().trim().max(100).nullable().optional(),barcode:z.string().trim().max(100).nullable().optional(),attachmentUrl:z.string().url().max(2000).nullable().optional(),notes:z.string().trim().max(5000).nullable().optional() });
const writable=(r)=>{if(r.user.role==="VIEWER")throw new AppError("Usuário VIEWER possui acesso somente para consulta.","FORBIDDEN",403);};
const audit=(r,action,type,entityId,metadata={})=>writeAudit({request:r,action:`fiscal_compliance.${action}`,companyId:r.company.id,entityType:type,entityId,metadata});

router.get("/preparations",asyncHandler(async(r,s)=>sendSuccess(s,await listFiscalBookPreparations(r.company.id))));
router.post("/preparations",asyncHandler(async(r,s)=>{writable(r);const closingId=uuid.parse(r.body?.closingId);const value=await buildFiscalBookPreparation(r.company.id,closingId,{userId:r.user.id});await audit(r,"preparation.created","FiscalBookPreparation",value.id,{closingId});sendSuccess(s,value,201);}));
router.get("/preparations/:preparationId",asyncHandler(async(r,s)=>sendSuccess(s,await getFiscalBookPreparation(r.company.id,r.params.preparationId))));
router.post("/preparations/:preparationId/rebuild",asyncHandler(async(r,s)=>{writable(r);const old=await getFiscalBookPreparation(r.company.id,r.params.preparationId);const value=await buildFiscalBookPreparation(r.company.id,old.monthlyTaxClosingId,{userId:r.user.id});await audit(r,"preparation.rebuilt","FiscalBookPreparation",value.id);sendSuccess(s,value);}));
router.post("/preparations/:preparationId/issues/:issueId/:action",asyncHandler(async(r,s)=>{writable(r);const p=await getFiscalBookPreparation(r.company.id,r.params.preparationId);const i=await prisma.fiscalBookIssue.findFirst({where:{id:r.params.issueId,preparationId:p.id,companyId:r.company.id}});if(!i)throw new AppError("Inconsistência não encontrada.","FISCAL_BOOK_ISSUE_NOT_FOUND",404);if(!["resolve","ignore"].includes(r.params.action))throw new AppError("Ação inválida.","INVALID_ACTION",400);if(r.params.action==="ignore"&&i.severity==="BLOCKING")throw new AppError("Inconsistência bloqueante não pode ser ignorada.","FISCAL_BOOK_BLOCKING_ISSUE",403);const reason=z.string().trim().min(1).max(5000).safeParse(r.body?.reason);if(r.params.action==="ignore"&&!reason.success)throw new AppError("Justificativa obrigatória.","JUSTIFICATION_REQUIRED",422);const value=await prisma.fiscalBookIssue.update({where:{id:i.id},data:r.params.action==="resolve"?{status:"RESOLVED",resolvedAt:new Date(),resolvedByUserId:r.user.id}:{status:"IGNORED",ignoreReason:reason.data}});await audit(r,`issue.${r.params.action}`,"FiscalBookIssue",i.id,{preparationId:p.id,reason:reason.data});sendSuccess(s,value);}));
router.get("/exports",asyncHandler(async(r,s)=>sendSuccess(s,await listFiscalExports(r.company.id,null,r.query))));
router.post("/exports/validate",asyncHandler(async(r,s)=>sendSuccess(s,await validateFiscalExport(r.company.id,null,uuid.parse(r.body?.preparationId)))));
router.post("/exports",asyncHandler(async(r,s)=>{writable(r);const body=z.object({preparationId:z.string().uuid(),type:z.enum(["SPED_FISCAL","SINTEGRA"])}).parse(r.body);const value=await generateFiscalExport(r.company.id,null,body.preparationId,body.type,{userId:r.user.id});await audit(r,"export.generated","FiscalExport",value.id,{type:value.type,hash:value.contentHash});sendSuccess(s,value,201);}));
router.get("/exports/:exportId/download",asyncHandler(async(r,s)=>{const value=await getFiscalExport(r.company.id,null,r.params.exportId,true);await audit(r,"export.downloaded","FiscalExport",value.id,{hash:value.contentHash});s.type("text/plain").attachment(value.fileName).send(value.content);}));

router.get("/forecast",asyncHandler(async(r,s)=>{const q=z.object({year:z.coerce.number().int().min(2006).max(2100),month:z.coerce.number().int().min(1).max(12)}).parse(r.query);const prev=new Date(Date.UTC(q.year,q.month-2,1));const rows=await prisma.monthlyTaxClosing.findMany({where:{companyId:r.company.id,OR:[{periodYear:q.year,periodMonth:q.month},{periodYear:prev.getUTCFullYear(),periodMonth:prev.getUTCMonth()+1}]}});const c=rows.find(x=>x.periodYear===q.year&&x.periodMonth===q.month);if(!c)throw new AppError("Gere o fechamento do período para calcular a previsão.","FORECAST_CLOSING_REQUIRED",422);const p=rows.find(x=>x.id!==c.id);const components={ICMS:Number(c.icmsTotal),IPI:Number(c.ipiTotal),PIS:Number(c.pisTotal),COFINS:Number(c.cofinsTotal),ISS:Number(c.snapshot?.taxes?.highlighted?.iss||0),SIMPLES:Number(c.snapshot?.taxes?.highlighted?.simples||0),RETENCOES:Number(c.snapshot?.taxes?.highlighted?.retentions||0)};const total=Object.values(components).reduce((a,b)=>a+b,0);const previousTotal=p?Number(p.estimatedTaxTotal):null;sendSuccess(s,{kind:"ESTIMATE",disclaimer:"Estimativa gerencial; não substitui apuração ou guia oficial.",period:q,regime:c.taxSettingsSnapshot?.taxRegime||r.company.taxRegime,components,total,previousTotal,variation:previousTotal?(total-previousTotal)/previousTotal:null,evidence:{closingId:c.id,status:c.status,inbound:Number(c.inboundTotal),outbound:Number(c.outboundTotal),freight:Number(c.freightTotal),documents:c.includedDocuments}});}));

router.get("/guides",asyncHandler(async(r,s)=>{const page=Math.max(1,Number(r.query.page||1)),pageSize=Math.min(100,Math.max(1,Number(r.query.pageSize||20)));await prisma.taxGuide.updateMany({where:{companyId:r.company.id,status:{in:["PENDING","ISSUED"]},dueDate:{lt:new Date()}},data:{status:"OVERDUE"}});const where={companyId:r.company.id,...(r.query.status?{status:statuses.parse(r.query.status)}:{}),...(r.query.reference?{reference:{contains:String(r.query.reference),mode:"insensitive"}}:{})};const[data,total]=await prisma.$transaction([prisma.taxGuide.findMany({where,orderBy:{dueDate:"asc"},skip:(page-1)*pageSize,take:pageSize}),prisma.taxGuide.count({where})]);sendSuccess(s,{data,pagination:{page,pageSize,total,totalPages:Math.ceil(total/pageSize)}});}));
router.post("/guides",asyncHandler(async(r,s)=>{writable(r);const body=guide.parse(r.body);if(body.closingId&&!(await prisma.monthlyTaxClosing.findFirst({where:{id:body.closingId,companyId:r.company.id}})))throw new AppError("Fechamento não encontrado.","MONTHLY_CLOSING_NOT_FOUND",404);const value=await prisma.taxGuide.create({data:{...body,companyId:r.company.id,createdById:r.user.id}});await audit(r,"guide.created","TaxGuide",value.id,{status:value.status});sendSuccess(s,value,201);}));
router.patch("/guides/:guideId",asyncHandler(async(r,s)=>{writable(r);const old=await prisma.taxGuide.findFirst({where:{id:r.params.guideId,companyId:r.company.id}});if(!old)throw new AppError("Guia não encontrada.","TAX_GUIDE_NOT_FOUND",404);const body=guide.partial().extend({status:statuses.optional(),paymentDate:z.coerce.date().nullable().optional()}).parse(r.body);const value=await prisma.taxGuide.update({where:{id:old.id},data:{...body,...(body.status==="PAID"&&!body.paymentDate?{paymentDate:new Date()}:{})}});await audit(r,"guide.updated","TaxGuide",value.id,{before:old,after:value});sendSuccess(s,value);}));
router.get("/guides/:guideId/history",asyncHandler(async(r,s)=>{const value=await prisma.taxGuide.findFirst({where:{id:r.params.guideId,companyId:r.company.id}});if(!value)throw new AppError("Guia não encontrada.","TAX_GUIDE_NOT_FOUND",404);sendSuccess(s,{data:await prisma.auditLog.findMany({where:{companyId:r.company.id,entityType:"TaxGuide",entityId:value.id},orderBy:{createdAt:"desc"}})});}));
export { router as fiscalComplianceRouter };
