BEGIN;
CREATE TABLE "fiscal_book_preparations" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "company_id" UUID NOT NULL, "office_id" UUID, "monthly_tax_closing_id" UUID NOT NULL UNIQUE REFERENCES "monthly_tax_closings"("id") ON DELETE CASCADE, "period_year" INTEGER NOT NULL, "period_month" INTEGER NOT NULL, "status" VARCHAR(30) NOT NULL DEFAULT 'DRAFT', "snapshot_hash" VARCHAR(64), "source_closing_approved_at" TIMESTAMP(3), "generated_at" TIMESTAMP(3), "generated_by_user_id" UUID, "invalidated_at" TIMESTAMP(3), "invalidated_reason" TEXT, "documents_count" INTEGER NOT NULL DEFAULT 0, "items_count" INTEGER NOT NULL DEFAULT 0, "issues_count" INTEGER NOT NULL DEFAULT 0, "blocking_issues_count" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "fiscal_book_preparation_documents" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "preparation_id" UUID NOT NULL REFERENCES "fiscal_book_preparations"("id") ON DELETE CASCADE, "company_id" UUID NOT NULL, "source_type" VARCHAR(10) NOT NULL, "source_document_id" UUID, "operation_group" VARCHAR(30) NOT NULL, "access_key" VARCHAR(44), "model" VARCHAR(10), "series" VARCHAR(10), "number" VARCHAR(30), "emission_date" TIMESTAMP(3), "participant_document" VARCHAR(20), "participant_name" TEXT, "cfop" VARCHAR(10), "total_amount" DECIMAL(15,2), "icms_amount" DECIMAL(15,2), "ipi_amount" DECIMAL(15,2), "pis_amount" DECIMAL(15,2), "cofins_amount" DECIMAL(15,2), "freight_amount" DECIMAL(15,2), "source_origin" VARCHAR(30), UNIQUE("preparation_id", "source_document_id"));
CREATE TABLE "fiscal_book_preparation_items" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "preparation_document_id" UUID NOT NULL REFERENCES "fiscal_book_preparation_documents"("id") ON DELETE CASCADE, "item_number" INTEGER NOT NULL, "product_code" TEXT, "description" TEXT, "ncm" VARCHAR(20), "cest" VARCHAR(20), "cfop" VARCHAR(10), "cst" VARCHAR(10), "csosn" VARCHAR(10), "unit" VARCHAR(10), "quantity" DECIMAL(15,4), "unit_value" DECIMAL(15,4), "total_value" DECIMAL(15,2), UNIQUE("preparation_document_id", "item_number"));
CREATE TABLE "fiscal_book_issues" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "preparation_id" UUID NOT NULL REFERENCES "fiscal_book_preparations"("id") ON DELETE CASCADE, "company_id" UUID NOT NULL, "severity" VARCHAR(20) NOT NULL, "code" VARCHAR(80) NOT NULL, "title" TEXT NOT NULL, "message" TEXT NOT NULL, "recommendation" TEXT, "source_type" VARCHAR(10), "source_document_id" UUID, "source_item_id" UUID, "record_reference" VARCHAR(20), "field_name" TEXT, "status" VARCHAR(20) NOT NULL DEFAULT 'OPEN', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolved_at" TIMESTAMP(3), "resolved_by_user_id" UUID, "ignore_reason" TEXT);
CREATE INDEX "fiscal_book_preparations_company_period_status_idx" ON "fiscal_book_preparations"("company_id","period_year","period_month","status");
CREATE INDEX "fiscal_book_preparation_documents_preparation_group_idx" ON "fiscal_book_preparation_documents"("preparation_id","operation_group");
CREATE INDEX "fiscal_book_issues_preparation_severity_status_idx" ON "fiscal_book_issues"("preparation_id","severity","status");
COMMIT;
