"use client";
import { useState } from "react";
import { Edit, Plus, Power, Trash2 } from "lucide-react";
import { Card } from "@/components/ui/card"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Badge } from "@/components/ui/badge"; import { notify } from "@/components/toast-viewport"; import { formatCurrency } from "@/lib/utils";
import { useServices, useServiceMutation, type ServiceCatalog, type ServiceInput } from "@/lib/services/services";
const empty: ServiceInput = { code:"",description:"",municipalCode:"",nationalCode:"",serviceListItem:null,municipality:"",municipalityIbgeCode:"",cnae:null,issRate:0,issWithheld:false,operationNature:null,enforceability:null,incidenceLocation:null,inssRate:0,irRate:0,csllRate:0,pisRate:0,cofinsRate:0,otherWithholdingRate:0,defaultValue:0,active:true };
export function ServicesView() {
 const [q,setQ]=useState(""); const [page,setPage]=useState(1); const [active,setActive]=useState(""); const [form,setForm]=useState<ServiceInput>(empty); const [editing,setEditing]=useState<string|null>(null); const [open,setOpen]=useState(false);
 const query=useServices(q,page,active); const mutation=useServiceMutation();
 const field=(key:keyof ServiceInput,label:string,type="text")=><Input label={label} type={type} value={String(form[key]??"")} onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})}/>;
 const save=async()=>{try{await mutation.mutateAsync({op:editing?"update":"create",id:editing||undefined,data:form});notify({title:editing?"Serviço atualizado":"Serviço criado",tone:"success"});setForm(empty);setEditing(null);setOpen(false);}catch(e){notify({title:"Não foi possível salvar",description:e instanceof Error?e.message:"Erro",tone:"error"});}};
 const edit=(s:ServiceCatalog)=>{setEditing(s.id);setForm({...s});setOpen(true);};
 const remove=async(s:ServiceCatalog)=>{if(!confirm(`Excluir o serviço ${s.description}?`))return;try{await mutation.mutateAsync({op:"delete",id:s.id});notify({title:"Serviço excluído",tone:"success"});}catch(e){notify({title:"Exclusão bloqueada",description:e instanceof Error?e.message:"Erro",tone:"error"});}};
 return <div className="space-y-4"><div className="flex justify-between"><div><h1 className="text-2xl font-extrabold">Serviços</h1><p className="text-sm text-subtle">Catálogo fiscal compatível com emissão de NFS-e.</p></div><Button variant="lime" onClick={()=>{setForm(empty);setEditing(null);setOpen(true)}}><Plus className="h-4 w-4"/>Novo serviço</Button></div>
 <Card className="flex flex-wrap gap-3 p-4"><Input className="max-w-md" placeholder="Buscar descrição, código ou código nacional" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select className="rounded-xl border px-3" value={active} onChange={e=>setActive(e.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></Card>
 {open&&<Card className="p-4"><h2 className="mb-3 font-bold">{editing?"Editar serviço":"Novo serviço"}</h2><div className="grid gap-3 md:grid-cols-3">{field("description","Descrição")}{field("code","Código interno")}{field("municipalCode","Código municipal")}{field("nationalCode","Código nacional")}{field("serviceListItem","Item da lista")}{field("municipality","Município")}{field("municipalityIbgeCode","Código IBGE")}{field("cnae","CNAE")}{field("issRate","Alíquota ISS","number")}{field("defaultValue","Valor padrão","number")}{field("inssRate","INSS","number")}{field("irRate","IR","number")}{field("csllRate","CSLL","number")}{field("pisRate","PIS","number")}{field("cofinsRate","COFINS","number")}<label className="flex items-center gap-2"><input type="checkbox" checked={form.issWithheld} onChange={e=>setForm({...form,issWithheld:e.target.checked})}/>ISS retido</label></div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="lime" disabled={mutation.isPending} onClick={save}>Salvar</Button></div></Card>}
 {query.isLoading?<Card className="h-72 animate-pulse bg-muted"/>:query.error?<Card className="p-8 text-center"><p>{query.error.message}</p><Button className="mt-3" onClick={()=>query.refetch()}>Tentar novamente</Button></Card>:<Card className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr>{["Serviço","Código","Município","ISS","Valor","Status","Ações"].map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{query.data?.data.length?query.data.data.map(s=><tr className="border-t" key={s.id}><td className="p-3 font-bold">{s.description}<p className="text-xs text-subtle">{s.nationalCode}</p></td><td className="p-3">{s.code}</td><td className="p-3">{s.municipality} · {s.municipalityIbgeCode}</td><td className="p-3">{s.issRate}% {s.issWithheld&&<Badge>Retido</Badge>}</td><td className="p-3">{formatCurrency(Number(s.defaultValue))}</td><td className="p-3"><Badge variant={s.active?"success":"neutral"}>{s.active?"Ativo":"Inativo"}</Badge></td><td className="p-3"><Button size="icon" variant="ghost" onClick={()=>edit(s)}><Edit className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>mutation.mutate({op:"toggle",id:s.id,active:!s.active})}><Power className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>remove(s)}><Trash2 className="h-4 w-4"/></Button></td></tr>):<tr><td colSpan={7} className="p-8 text-center text-subtle">Nenhum serviço cadastrado.</td></tr>}</tbody></table><div className="flex justify-end gap-2 border-t p-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</Button><span className="p-2 text-xs">Página {page}</span><Button variant="outline" disabled={(query.data?.data.length||0)<20} onClick={()=>setPage(page+1)}>Próxima</Button></div></Card>}</div>;
}
