import crypto from "node:crypto";
import { prisma } from "../config/prisma.js";
import { AppError } from "../utils/app-error.js";

const eligible = new Set(["REAL_SEFAZ", "MANUAL_IMPORT", "ERP_IMPORT"]);
const empty = (value) => value == null || value === "";
const issue = (code, title, fieldName, sourceDocumentId, sourceItemId = null, severity = "ERROR") => ({ code, title, message: `${title}: dado não disponível no snapshot de origem.`, recommendation: "Corrija o documento fiscal de origem e gere novo fechamento aprovado.", fieldName, sourceDocumentId, sourceItemId, severity, sourceType: sourceItemId ? "NFE" : null, recordReference: sourceItemId ? "C170" : "C100" });

export async function buildFiscalBookPreparation(companyId, closingId, actor = {}) {
  const closing = await prisma.monthlyTaxClosing.findFirst({ where: { id: closingId, companyId }, include: { items: { include: { document: { include: { items: true } } } } } });
  if (!closing) throw new AppError("Fechamento não encontrado.", "MONTHLY_CLOSING_NOT_FOUND", 404);
  if (closing.status !== "APPROVED") throw new AppError("A pré-escrituração exige fechamento mensal aprovado.", "FISCAL_BOOK_CLOSING_NOT_APPROVED", 422);
  const documents = closing.items.filter((entry) => entry.document && eligible.has(entry.source) && !entry.document.isCancelled && !["INUTILIZADO", "INUTILIZADA"].includes(String(entry.document.status || "").toUpperCase()));
  const content = JSON.stringify(documents.map((entry) => [entry.documentId, entry.category, entry.amount]));
  const preparation = await prisma.fiscalBookPreparation.upsert({ where: { monthlyTaxClosingId: closing.id }, create: { companyId, officeId: actor.officeId || closing.officeId, monthlyTaxClosingId: closing.id, periodYear: closing.periodYear, periodMonth: closing.periodMonth, status: "PROCESSING", snapshotHash: crypto.createHash("sha256").update(content).digest("hex"), sourceClosingApprovedAt: closing.approvedAt, generatedAt: new Date(), generatedByUserId: actor.userId || null }, update: { status: "PROCESSING", invalidatedAt: null, invalidatedReason: null, generatedAt: new Date(), generatedByUserId: actor.userId || null } });
  const issues = []; const preparationDocuments = [];
  for (const entry of documents) { const document = entry.document; const sourceType = document.documentType === "CTE" ? "CTE" : "NFE"; const pd = { preparationId: preparation.id, companyId, sourceType, sourceDocumentId: document.id, operationGroup: entry.category, accessKey: document.accessKey, model: document.model, series: document.series, number: document.invoiceNumber, emissionDate: document.emissionDate, participantDocument: document.operationDirection === "OUTBOUND" ? document.recipientCnpj : document.issuerCnpj, participantName: document.operationDirection === "OUTBOUND" ? document.recipientName : document.issuerName, cfop: document.cfop, totalAmount: document.totalAmount, icmsAmount: document.icmsAmount, ipiAmount: document.ipiAmount, pisAmount: document.pisAmount, cofinsAmount: document.cofinsAmount, freightAmount: document.freightAmount, sourceOrigin: document.source };
    for (const [field, code, title] of [["accessKey","ACCESS_KEY_REQUIRED","Chave de acesso"],["model","MODEL_REQUIRED","Modelo"],["series","SERIES_REQUIRED","Série"],["invoiceNumber","NUMBER_REQUIRED","Número"],["emissionDate","EMISSION_DATE_REQUIRED","Data de emissão"],["cfop","CFOP_REQUIRED","CFOP"],["totalAmount","TOTAL_REQUIRED","Total do documento"]]) if (empty(document[field])) issues.push(issue(code,title,field,document.id));
    if (empty(pd.participantDocument) || empty(pd.participantName)) issues.push(issue("PARTICIPANT_REQUIRED","Participante fiscal","participant",document.id));
    preparationDocuments.push({ pd, items: sourceType === "NFE" ? document.items : [] }); }
  const settingsValid = Boolean(closing.taxSettingsSnapshot?.fiscalConfigComplete); if (!settingsValid) issues.push({ code: "TAX_SETTINGS_REQUIRED", title: "Configuração tributária necessária", message: "O fechamento aprovado não possui snapshot tributário completo.", recommendation: "Complete a configuração tributária e aprove novo fechamento.", severity: "BLOCKING", sourceType: null, recordReference: "0000" });
  await prisma.$transaction(async (tx) => { await tx.fiscalBookPreparationItem.deleteMany({ where: { preparationDocument: { preparationId: preparation.id } } }); await tx.fiscalBookPreparationDocument.deleteMany({ where: { preparationId: preparation.id } }); await tx.fiscalBookIssue.deleteMany({ where: { preparationId: preparation.id } }); for (const row of preparationDocuments) { const created = await tx.fiscalBookPreparationDocument.create({ data: row.pd }); for (const item of row.items) { await tx.fiscalBookPreparationItem.create({ data: { preparationDocumentId: created.id, itemNumber: item.itemNumber, productCode: item.productCode, description: item.description, ncm: item.ncm, cfop: item.cfop, cst: item.cst, csosn: item.csosn, unit: item.unit, quantity: item.quantity, unitValue: item.unitValue, totalValue: item.totalValue } }); for (const [field, code, title] of [["ncm","NCM_REQUIRED","NCM"],["cfop","CFOP_REQUIRED","CFOP"],["unit","UNIT_REQUIRED","Unidade"]]) if (empty(item[field])) issues.push(issue(code,title,field,row.pd.sourceDocumentId,item.id)); if (empty(item.cst) && empty(item.csosn)) issues.push(issue("CST_CSOSN_REQUIRED","CST ou CSOSN","cst/csosn",row.pd.sourceDocumentId,item.id)); } } const blocking = issues.filter((item) => item.severity === "BLOCKING").length; await tx.fiscalBookIssue.createMany({ data: issues.map((item) => ({ ...item, preparationId: preparation.id, companyId })) }); await tx.fiscalBookPreparation.update({ where: { id: preparation.id }, data: { documentsCount: preparationDocuments.length, itemsCount: preparationDocuments.reduce((n,row)=>n+row.items.length,0), issuesCount: issues.length, blockingIssuesCount: blocking, status: blocking ? "BLOCKED" : issues.length ? "HAS_ISSUES" : "READY" } }); });
  return getFiscalBookPreparation(companyId, preparation.id);
}
export async function getFiscalBookPreparation(companyId, id) { const value = await prisma.fiscalBookPreparation.findFirst({ where: { id, companyId }, include: { documents: { include: { items: true } }, issues: true } }); if (!value) throw new AppError("Pré-escrituração não encontrada.", "FISCAL_BOOK_PREPARATION_NOT_FOUND", 404); return value; }
export async function listFiscalBookPreparations(companyId) { return { data: await prisma.fiscalBookPreparation.findMany({ where: { companyId }, orderBy: { generatedAt: "desc" } }) }; }
